### PR TITLE
calibre: enable tests

### PR DESCRIPTION
**Pull request by risicle**
## Description of changes

Only a little bit of fighting needed.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by LeSuisse — APPROVED** [review]
Thanks for dealing with that.


Result of `nixpkgs-review pr 338867` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>calibre</li>
    <li>unbook</li>
  </ul>
</details>

**Comment by LunNova** [comment]
Seeing apparently spurious failures of `test_websocket_basic`, may need excluded.

**Comment by risicle** [comment]
@LunNova platform?

**Comment by LeSuisse** [comment]
Indeed, I did not get it on my initial rebuild when I merged this but I can see it on Linux x86_64

**Comment by LunNova** [comment]
x86_64-linux, `nix build github:nixos/nixpkgs/2e877812edf1581cc8df065feb57ed704d6fb7e6#calibre --rebuild --no-link` fails ~50% of the time

```
======================================================================
FAIL: test_websocket_basic (calibre.srv.tests.web_sockets.WebSocketTest.test_websocket_basic)
Test basic interaction with the websocket server
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/calibre-7.16.0/src/calibre/srv/tests/web_sockets.py", line 282, in test_websocket_basic
    isf_test(frags, close_code=INCONSISTENT_DATA, send_close=False, ignore_send_failures=True)
  File "/build/calibre-7.16.0/src/calibre/srv/tests/web_sockets.py", line 219, in simple_test
    self.assertGreaterEqual(len(control_frames), 1)
AssertionError: 0 not greater than or equal to 1

Stdout:
calibre server listening on 127.0.0.1:39505
Too large control frame from client
RSV bits set in frame from client
RSV bits set in frame from client
RSV bits set in frame from client
RSV bits set in frame from client
RSV bits set in frame from client
RSV bits set in frame from client
Unknown OPCODE from client: 3
Unknown OPCODE from client: 4
Unknown OPCODE from client: 5
Unknown OPCODE from client: 6
Unknown OPCODE from client: 7
Unknown OPCODE from client: 11
Unknown OPCODE from client: 12
Unknown OPCODE from client: 13
Unknown OPCODE from client: 14
Unknown OPCODE from client: 15
Fragmented control frame from client
Fragmented control frame from client
Too large control frame from client
Client sent continuation frame with no message to continue
Client sent continuation frame with no message to continue
Client sent continuation frame with no message to continue
Client sent continuation frame with non-zero opcode
Client sent undecodeable UTF-8
Client sent undecodeable UTF-8

----------------------------------------------------------------------
Ran 332 tests in 25.258s

FAILED (failures=1, skipped=9)
```

**Comment by risicle** [comment]
Hmm, cannot reproduce myself, but I guess we should add it to the exclusions.

**Pull request merged**
