### PR TITLE
nixos/version: make versions in /etc/os-release less verbose

### LINKED ISSUE #127654: version in /etc/os-release is verbose
The NixOS version in `/etc/os-release` is way more verbose than [intended](https://www.freedesktop.org/software/systemd/man/os-release.html#Information%20about%20the%20version%20of%20the%20operating%20system) (and in other distros).  One likely consequence is #99677, but the issue is general (I encountered it elsewhere).

We have e.g.:
```ini
VERSION="21.05.git.ad4079ba81d (Okapi)"
VERSION_ID="21.05.git.ad4079ba81d"
```
Others have e.g.:
```ini
VERSION="18.04.5 LTS (Bionic Beaver)"
VERSION_ID="18.04"
```

From a quick glance at [the docs](https://www.freedesktop.org/software/systemd/man/os-release.html#Information%20about%20the%20version%20of%20the%20operating%20system), I'd suggest to move the commit hash to other fields, probably `BUILD_ID`.

_Source: `nixos/modules/misc/version.nix`_

### PR DESCRIPTION
**Pull request by vcunat**
Fixes #127654; also see details in there.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
I suppose very few things can be affected by this, so my testing (on 21.05) doesn't really matter much.

**Review by roberth — APPROVED** [review]

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 131967` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages blacklisted:</summary>
  <ul>
    <li>tests.nixos-functions.nixos-test</li>
    <li>tests.nixos-functions.nixosTest-test</li>
    <li>tests.trivial</li>
  </ul>
</details>

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 131967` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>

**Review by davidak — APPROVED** [review]
Change looks good

i'm not sure how to test it. should not break anything

i generally welcome this change as it makes nixos more user friendly :sparkles:

**Pull request merged**
