### PR TITLE
docker: disable socket activation by default

### PR DESCRIPTION
**Pull request by jgillich**
It causes issues for many people, see #11478

### CODE REVIEW

**Comment by Mic92** [comment]
Can you give a configuration, where I can reproduce this issue? What is the state of `systemctl status docker.socket` in this case?

**Comment by jgillich** [comment]
Simply enable docker and then run `systemctl restart docker`. I'm not actually  running NixOS currently, this is just something we should've done a long time ago.

**Comment by Mic92** [comment]
@jgillich I think what you actually want is not to disable socket activation but rather enabling docker daemon on boot, which are too different things. I made a pull request which also brings enable docker live restore (dockerd upgrades without restarting containers): https://github.com/NixOS/nixpkgs/pull/21326

**Comment by Mic92** [comment]
fixed by https://github.com/NixOS/nixpkgs/commit/c23032a8b11d0585c1f1aece1d2b0abd82148e82

**Pull request closed without merging**
