### PR TITLE
glusterfs: 3.10.2 -> 3.12.0

### PR DESCRIPTION
**Pull request by nh2**
Glusterfs 3.12 is the latest stable release.

Changes to the nix files:

* The patch `glusterfs-fix-unsubstituted-autoconf-macros` was deleted
  because the issue was fixed upstream:
  https://bugzilla.redhat.com/show_bug.cgi?id=1450588
* The `glusterd-ganesha.c` part of `glusterfs-use-PATH-instead-of-hardcodes`
  was detleted because `glusterd-ganesha.c` was removed upstream
  without replacement that has the relevant hardcoded paths.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [X] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

I have also tested this upgrade with my own glusterfs-on-nixos cluster setup, an open-source equivalent of which is available at https://github.com/nh2/nixops-gluster-example/.
Normal 3-cluster replicated operation and geo-replication seem to work as expected and as in 3.10.2.

CC @bachp @7c6f434c @fduraffourg @Mic92 @FRidh @wkennington @proger (other committers to glusterfs on nix)

### CODE REVIEW

**Comment by nh2** [comment]
Please don't merge this before #29071.

Merge #29071 first.

Because the paches in there will have to be updated for gluster 3.12.

I'd appreciate a quick merge of #29071 in order to give me some more time to get 3.12 in for NixOS 17.09 :)

**Comment by joachifm** [comment]
@nh2 can this be merged now?

**Comment by nh2** [comment]
@joachifm I need to rebase (I think some patches will have conflicts) and re-test first, but I hope to manage it before end of the month for the 17.09 release.

**Review by 7c6f434c — APPROVED** [review]

**Comment by nh2** [comment]
**Quick summary:** Please merge #29868 first and afterwards merge this.

---

I have rebased this PR on top of #29868.

This PR should wait until #29868 is merged (so that the number of commits is reduced back to 1).

I have tested the 3.10.2 -> 3.12.1 upgrade with my example nixops deployment at https://github.com/nh2/nixops-gluster-example that anybody should be able to reproduce. Specifically, when cherry-picking the commit in this PR on top of the nixpkgs [I link in the README](https://github.com/nh2/nixops-gluster-example/commit/68c1cb700f695a2d82c0cc192bc524522183aa81#diff-04c6e90faac2675aa89e2176d2eec7d8R55), I could perform the upgrade.

The results suggested that a simple `nixops deploy` upgraded the gluster cluster successfully.

The only thing that didn't advance automatically to the new version was the geo-replication session.
This is because gluster unfortunately hardcodes the paths to various binaries into a config file at the time the session is created, namely into `/var/lib/glusterd/geo-replication/NAME/gsyncd.conf`. I upgraded the georep session with

```
nixops ssh-for-each -d gluster-test "perl -p -i -e 's/758q3xl9bfyg20x39nc6zrgnh52q1k75-glusterfs-3.10.2/wprv5aypnrz1nsc1r1ppr4g0bmhc0bgb-glusterfs-3.12.1/g' /var/lib/glusterd/geo-replication/distfs_10.0.1.1_distfs-georep/gsyncd.conf"
```

and this is also how I would recommend other NixOS glusterfs-geo-replication users to upgrade their georep sessions (though I doubt that there are any apart from me currently).

**Comment by joachifm** [comment]
This PR didn't apply cleanly so I just dropped everything except the last commit, assuming the changes in the other PR take precedence.

**Comment by nh2** [comment]
@joachifm Yes, thas was correct, thanks.

All changes before the last commit were already merged with #29868.

**Pull request closed without merging**
