### PR TITLE
[Backport release-24.05] Backport 339264 to release 24.05

### PR DESCRIPTION
**Pull request by rorosen**
## Description of changes

Backport https://github.com/NixOS/nixpkgs/pull/339264 to release 24.05.

k3s_1_27: remove
k3s_1_28: 1.28.12+k3s1 -> 1.28.13+k3s1
k3s_1_29: 1.29.7+k3s2 -> 1.29.8+k3s1
k3s_1_30: 1.30.3+k3s1 -> 1.30.4+k3s1
k3s_1_31: init 1.31.0+k3s1

I removed 1.27 as it's EOL and I guess 24.05 shouldn't provide EOL packages (it's not only EOL but also not the newest patch version). Let me know if 1.27 was on purpose still in 24.05.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

@NixOS/k3s 

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by rorosen** [comment]
The cherry picks checker fails probably because I made some manual changes:

- Do not set the `k3s` alias to `k3s_1_31` on stable
- Remove `images-versions.json` as the builder on stable can't handle it

**Review by marcusramberg — APPROVED** [review]

**Review by wrmilling — APPROVED** [review]
LGTM

Result of `nixpkgs-review pr 340037` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>k3s (k3s_1_30)</li>
    <li>k3s_1_28</li>
    <li>k3s_1_29</li>
    <li>k3s_1_31</li>
  </ul>
</details>

**Comment by fabianhjr** [comment]
Cherry-pick check is failing: https://github.com/NixOS/nixpkgs/actions/runs/10736215337/job/29775134085?pr=340037

**Comment by wrmilling** [comment]
> Cherry-pick check is failing: https://github.com/NixOS/nixpkgs/actions/runs/10736215337/job/29775134085?pr=340037

Thank you for the call-out, in this case it would be expected to fail as the PRs commits will not match exactly. We are not going to be migrating the `k3s` alias on stable to a newer revision as was done on unstable, but we still want the latest revision(s) to be available on stable.

**Pull request merged**
