### PR TITLE
haskell.package-list: dont report broken packages to Hackage

### LINKED ISSUE #243512: List of available haskell packages at hackage should not contain broken packages
The Haskell Hackage database allows distros to report which packages they ship, and include a link. Right now, it seems that nixpkgs reports all haskell packags, including broken ones. This makes for a bad user experience – I might see on hackage that nixos comes with a certain package, and then happily go ahead trying to use it, only later to get the dreaded 
```
error: Package ‘proteaaudio-0.9.4’ in /home/jojo/build/nixpkgs/pkgs/development/haskell-modules/hackage-packages.nix:236858 is marked as broken, refusing to evaluate.
```
error message.

Same actually for repology, reporting packages as available that we know do not build is not great.

### PR DESCRIPTION
**Pull request by nomeata**
###### Description of changes

Claiming that a hackage package is available in nixpkgs when we
explicitly mark it as broken is less helpful, so let's filter them out.

This changes the number of reported packages from 17137 to 10937.

Fixes #243512

###### Things done

Tested `nix-build -A haskell.package-list`.

### CODE REVIEW

**Comment by maralorn** [comment]
Excellent, thank you!

Note, that a lot of packages are not marked broken themselves but are only implicitly broken by one of their dependencies. Compare our broken.yaml, which lists packages which receive the broken flag, with transitive-broken.yaml which contains packages for which we only deactivate the hydra job, so the user sees the real culprit on eval.

If we do this we should hide packages from both lists.

**Comment by nomeata** [comment]
Should I keep the existing workflow, and extend hackage2tex to put a `transitivelyBroken` attribute into `meta`?

Or should I just parse `./pkgs/development/haskell-modules/configuration-hackage2nix/transitive-broken.yaml` directly from `./pkgs/development/haskell-modules/package-list.nix`?

**Comment by sternenseemann** [comment]
You can simply check if `meta.hydraPlatforms or null == []`.On 15. Jul 2023, at 14:40, Joachim Breitner ***@***.***> wrote:﻿
Should I keep the existing workflow, and extend hackage2tex to put a transitivelyBroken attribute into meta?
Or should I just parse ./pkgs/development/haskell-modules/configuration-hackage2nix/transitive-broken.yaml directly from ./pkgs/development/haskell-modules/package-list.nix?

**Comment by nomeata** [comment]
Done. After going from 17137 to 10937 we are now down to 6624.

**Comment by maralorn** [comment]
Yeah, that number is exactly the right ball park.

**Comment by nomeata** [comment]
Doing the same to the repology report at https://repology.org/repositories/statistics/total will drop us below AUR. I wonder if people will like this…  but it’s certainly the right move: https://github.com/repology/repology-updater/issues/1340

**Comment by nomeata** [comment]
Is this a rule that applies outside of haskell packages too, so that Repology should ignore packages with `"hydraPlatforms": []`? Or is in general `broken` the better attribute?

**Comment by maralorn** [comment]
Well, to be fair in theory `hydraPlatforms == []` is an underapproximation. It e.g. applies to unfree software which we cannot cache for licensing reasons but are perfectly fine and working packages, happens e.g. for some games which we have packaged. That is not so much a concern for Haskell because Hackage only accepts Open Source licenses. But it could happen for non-Hackage packages of which we have a few.

The ratio of broken to transitive broken packages in the rest of nixpkgs is unknown to me. My guess is that that we don’t have a lot of transitively broken packages in the rest of nixpkgs. In all parts of the package set which are not autogenerated broken is more thought to be a temporary thing anyway, I guess? If a package is broken for a while we can just drop it.

Besides that I 100% agree that repology should ignore broken packages.

**Comment by nomeata** [comment]
> Besides that I 100% agree that repology should ignore broken packages.

Repology doesn't agree, it seems: https://github.com/repology/repology-updater/issues/1340. Not sure if there are further good arguments.

**Comment by maralorn** [comment]
Well, doesn’t really impact the usability of nixpkgs, so that’s fine by me.

**Comment by nomeata** [comment]
> Excellent, thank you!

@maralorn, care to merge in that case?

**Pull request merged**
