### PR TITLE
Update redis to 3.0.2 (now that 3 is stable, squash it into default)

### PR DESCRIPTION
**Pull request by berdario**
Include fix for http://benmmurphy.github.io/blog/2015/06/04/redis-eval-lua-sandbox-escape/

I just want to note btw that I'm not using redis in my day job anymore (this is the case since Summer 2014, actually), so there might be people better positioned to act as maintainers (though I definitely still want to help, and having to care about this is a good way to remain involved with the Nix project!)

### CODE REVIEW

**Comment by domenkozar** [comment]
Can you resolve conflicts?

**Comment by berdario** [comment]
Uhm, there was no conflict when I first uploaded this... 

I'll do it when I'll get back home 

(why can't git do this on its own?  :/ ) 
-- 
Sent from mobile. Please excuse my brevity.

**Comment by berdario** [comment]
@domenkozar Done

The conflict was due to another commit that updated redis:

https://github.com/NixOS/nixpkgs/commits/master/pkgs/servers/nosql/redis/3.0.nix

it was done 7 days after I opened this pull request

I think we need a better way to tackle security issues.... I opened this PR the very same day that redis-3.0.2 has been released, but since I'm not a committer I couldn't label this as `update-package` and `security`... otherwise just labelling them, and then keeping track of the label would be enough

**Comment by falsifian** [comment]
@domenkozar, what does the "needs-changelog" label mean?

This looks ready to merge, but I'd rather understand what the label means first.

**Comment by domenkozar** [comment]
It means NixOS changelog should mention this bump

**Comment by berdario** [comment]
A small note (assuming that the changelog is needed due to the security fix): redis has already been updated to 3.0.2 on nixpkgs due to the other commit. But maybe updating the changelog after the code has already been updated is not such a big deal?

Anyhow, this pull request still needs to be merged, since the version bump for the same security fix hasn't been done for redis 2.8. This PR solves that by dropping 2.8

Dropping 2.8 is reasonable since:

- it's nix policy to have only 1 stable version (redis3 was added only while it was a RC)
- redis3 is not a huge break over redis2.8, from the release notes:

> Migrating from 2.8 to 3.0
> =========================

>Redis 2.8 is mostly a strict subset of 3.0, you should not have any problem
upgrading your application from 2.8 to 3.0. However this is a list of small
non-backward compatible changes introduced in the 3.0 release:

> * The log format was modified. The prefix of each line included the pid
  in the following format [1234]. Now instead it is 1234:? Where
  '?' is actually the role of the instance. M for master, S for slave, C
  if this process is a saving child (for RDB/AOF), and X for Sentinel.

> * The default maxmemory policy in Redis 3.0 is no longer "volatile-lru" as
  it used to be in 2.8, but "noeviction". The policies behavior is the same
  (but LRU eviction is much more precise in 3.0), so only the default value
  changed. Just make sure to specify in your redis.conf what you mean.

**Comment by falsifian** [comment]
Thanks for the clarification @domenkozar. Are we supposed to update the changelog right now, or is someone going to go through the "needs-changelog" label at some later point just before the next release?

**Pull request merged**
