### PR TITLE
nixos/tests/bcachefs: use multi-disk

### PR DESCRIPTION
**Pull request by Madouura**
###### Motivation for this change
Use multi-disk layout for test, which is the more likely usecase anyway.
Wanted to get encryption working in the test, which it does work on the machine I tested this on, but does not in test vm. I suspect an out-of-date systemd or hardening not allowing a key to be set.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by marijanp** [comment]
@ofborg test bcachefs

**Review by marijanp — COMMENTED** [review]
The changes look good to me. Ofborg tests are also passing. You may want to wait for the approval of @Chiiruno, the original author of this test. And somebody with merge rights.

**Comment by Madouura** [comment]
I am Chiiruno, I lost my phone, and with it, authy since I was dumb enough to not make a backup, and apparently was stupid enough to not update my phone number in github.

**Comment by Madouura** [comment]
Screenshot from 2022-01-03 06-08-43

**Comment by Madouura** [comment]
@marijanp All good for merge?

**Review by marijanp — APPROVED** [review]

**Pull request merged**
