### PR TITLE
vimPlugins.vim-zettel: init at 2022-09-05

### PR DESCRIPTION
**Pull request by heitorPB**
###### Description of changes

My first contribution here :)

Added new vim Plugin: https://github.com/michal-h21/vim-zettel/

I run the script provided, that also updated the other plugins.

Should I drop the commit that updates the tree-sitter grammars?

Should I also tag this PR with a backport tag to include this plugin in the next nixos release?

Should I also add myself to the contributors list?

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by heitorPB** [comment]
Oh, damn conflicts... Will look into that tomorrow.

**Comment by figsoda** [comment]
The merge conflict should be gone if sync the branch and run the update script again

> Should I drop the commit that updates the tree-sitter grammars?

Yes

> Should I also tag this PR with a backport tag to include this plugin in the next nixos release?

The backport bot wouldn't work in this case since the release branch is out of sync with master. If you are want to use it on a stable branch, it would have to be manually backported by cherry-picking the `vimPlugins.vim-zettel: init at 2022-09-05` commit

> Should I also add myself to the contributors list?

You don't have to, but if you want to do so, feel free to add yourself to the maintainers in a separate commit. You would need to explicitly add yourself as a maintainer of the package you want to maintain as well

**Review by figsoda — APPROVED** [review]
thanks

**Comment by heitorPB** [comment]
Awesome!

> The backport bot wouldn't work in this case since the release branch is out of sync with master. If you are want to use it on a stable branch, it would have to be manually backported by cherry-picking the `vimPlugins.vim-zettel: init at 2022-09-05` commit

@figsoda could you guide to the steps to backport this plugin to a stable and unstable branches?

**Comment by figsoda** [comment]
It should be automatically in unstable in a day or two, I opened https://github.com/NixOS/nixpkgs/pull/205333 to backport it to 22.11

**Pull request merged**
