### PR TITLE
palemoon: 28.6.0.1 -> 28.7.0, drop hardeningDisable

### PR DESCRIPTION
**Pull request by OPNA2608**
Tested without the disabled `format` hardening, it built fine.
Opening `about:buildconfig` on the Ubuntu build lists `-Wformat` under the used
compiler flags, so it should be okay anyway.

###### Motivation for this change

Package update & abit more cleanup work.
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mmahut** [comment]
@GrahamcOfBorg build palemoon

**Comment by mmahut** [comment]
I'm getting the following build error.

```
builder for '/nix/store/zwbi8p1ixd8xw653m8dr6zq2zmyw8wi0-palemoon-28.6.1.drv' failed with exit code 2; last 10 log lines:
   7:42.97              ^
   7:47.44 libgfx_layers.a.desc
   7:53.01 make[4]: *** [/build/source/config/recurse.mk:71: layout/base/target] Error 2
   7:59.98 make[4]: *** [/build/source/config/recurse.mk:71: dom/bindings/target] Error 2
   7:59.99 make[3]: *** [/build/source/config/recurse.mk:33: compile] Error 2
   8:00.01 make[2]: *** [/build/source/config/rules.mk:494: default] Error 2
   8:00.01 make[1]: *** [/build/source/client.mk:414: realbuild] Error 2
   8:00.01 make: *** [client.mk:170: build] Error 2
   8:00.08 63 compiler warnings present.
   8:00.22 Notification center failed: Install the python dbus module to get a notification when the build finishes.
cannot build derivation '/nix/store/m4klrfw44kblz9ikjcjfm16v4y0ci6zy-env.drv': 1 dependencies couldn't be built
```

**Comment by OPNA2608** [comment]
I can't reproduce your error, nix-build succeeds in my VM. :slightly_frowning_face: 
Screenshot_NixOS_19 03_2019-08-23_13:41:33

Can you give more details or the full build log? [Here's mine](https://github.com/NixOS/nixpkgs/files/3534291/palemoon-f096e5a46d89d3b4834732fd017fb27d85cc64b6.log), with the changes of this PR applied onto f096e5a46d89d3b4834732fd017fb27d85cc64b6. Should hopefully not have an effect on the result of `nix-build` on a local git clone, but here's the VM's system information as well.

- system: `"x86_64-linux"`
- host os: `Linux 5.1.16, NixOS, 19.03.173068.9ec7625cee5 (Koi)`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.2.2`
- channels(root): `"nixos-19.03.173068.9ec7625cee5"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Review by aanderse — APPROVED** [review]
This package also built (eventually...) and ran for me. Would be nice to have one more person confirm this builds for them, or someone to look at what went wrong with the build @mmahut :thinking:

**Comment by OPNA2608** [comment]
Upstream tagged a new release 28.7.0 afew days ago, I'll update this PR to the new version as needed and test it once they put up the release notes on Github.

https://github.com/MoonchildProductions/UXP/releases/tag/PM28.7.0_Release

**Comment by OPNA2608** [comment]
Updated to 28.7.0. [(Releae notes)](http://www.palemoon.org/releasenotes.shtml)

Tested compiling it, which succeeded after ~30min on 3 threads, and starting it, which appeared to work fine. I can do more thorough testing later today.

**Comment by aanderse** [comment]
New version compiled (eventually) and ran as expected.

@OPNA2608 please squash commits.

**Comment by rnhmjoj** [comment]
@OPNA2608 Could you please remove my name from the maintainers of this package? I haven't been using pale moon or updating the package for a while.

**Comment by rnhmjoj** [comment]
Thank you.

**Pull request merged**
