### PR TITLE
Added Inconsolata-dz For Powerline

### PR DESCRIPTION
**Pull request by cassandracomar**
Added the powerline version of the Inconsolata-dz font. I got the font from https://github.com/powerline/fonts but had to load it into a gist because of the spaces in the original file name.

### CODE REVIEW

**Comment by devhell** [comment]
Just as question/suggestion: Wouldn't it be more beneficial to include the entire suite of powerline fonts instead of one specific font?

**Comment by arjuncomar** [comment]
Sure, I can do that. Won't that make it more difficult to find a particular font though? If you don't know what the (theoretical) powerline-fonts package contains, how would you discover that your favorite font had a powerline variant?

If that's an acceptable tradeoff, I'll go ahead and install the entire suite of powerline fonts instead of just the one.

**Comment by devhell** [comment]
@arjuncomar Sorry for the late reply. I'd personally say that if someone is aware that powerline fonts exist they'll know what to look for. Maybe mentioning their existence in the wiki would also be a good idea once we have them in NixOS. ;-)

**Comment by devhell** [comment]
@arjuncomar ping? ;-)

**Comment by arjuncomar** [comment]
Sorry @devhell, hadn't logged into github in some time. I'll make this change this weekend so we can close out this PR.

**Comment by devhell** [comment]
@arjuncomar No problem, thanks for doing this!

**Comment by vcunat** [comment]
Ping again?

**Comment by zimbatm** [comment]
Closing as the powerline fonts have been added since April 2015. 76dcf48b13c27b7a2fc2373e2bf2e2e1e95ab120

**Pull request closed without merging**
