### PR TITLE
polar-bookshelf: 1.0.11 -> 1.0.13

### PR DESCRIPTION
**Pull request by fx-chun**
###### Motivation for this change

https://github.com/burtonator/polar-bookshelf/releases/tag/v1.0.13

Changelog: 
```
# 1.0.13

 - point release to fix auto-updates in release process and upgrade 
   electron-builder and electron-updater

 - migration from typescript 3.0.3 to 3.1.6 due to incompatibility to with new 
   electron-builder

# 1.0.12

- Reduced the minimum mouse click duration required for bringing up the annotation 
  bar. 

- Fixed bug with Electron generating an error window on exit due to a conversion 
  of the wrong type to an integer.  This was/is an Electron bug.  This may not
  be fixed in all situations but it's much better than it was before.

- Feature: drag and drop for bulk PDF import works. 

- Upgrade to Electron 3.0.8

- Fixed analytics around number of documents in the repository

- Feature: The "Delete" text is now danger red.

- Feature: Implemented a confirm prompt when deleteing flashcards, comments, and
  annotations.
 
- Feature: Implemented Cancel when creating flashcards and comments 

- Feature: Reworked anki sync to run from the doc repository.

- Feature: Renamed "Copy URL" to "Copy Original URL"
```

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by worldofpeace — CHANGES_REQUESTED** [review]
Your pr title is an acceptable commit msg according to the [Contribution Guidelines](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes).

While `Bump version from 1.0.11 to 1.0.13` is not.

**Comment by worldofpeace** [comment]
@GrahamcOfBorg build polar-bookshelf

**Comment by worldofpeace** [comment]
Currently the desktop files `Exec` is
```
 Exec="/opt/Polar Bookshelf/polar-bookshelf" %U
```

Which is a non-existent path.

This can be patched easily within the `installPhase` thusly:
```diff
diff --git a/pkgs/applications/misc/polar-bookshelf/default.nix b/pkgs/applications/misc/polar-bookshelf/default.nix
index 445dd84c707..cf5dd679f68 100644
--- a/pkgs/applications/misc/polar-bookshelf/default.nix
+++ b/pkgs/applications/misc/polar-bookshelf/default.nix
@@ -70,6 +70,10 @@ stdenv.mkDerivation rec {
     mv usr/share/* $out/share/
 
     ln -s $out/share/polar-bookshelf/polar-bookshelf $out/bin/polar-bookshelf
+
+    # Correct desktop file `Exec`
+    substituteInPlace $out/share/applications/polar-bookshelf.desktop \
+      --replace "/opt/Polar Bookshelf/polar-bookshelf" "$out/bin/polar-bookshelf"
   '';
 
   preFixup = ''
```

Other than that the binary executes properly.

**Comment by c0bw3b** [comment]
@GrahamcOfBorg build polar-bookshelf

**Comment by Mic92** [comment]
Does the desktop file require a backport?

**Comment by c0bw3b** [comment]
@Mic92 no `polar-bookshelf` has been added in master [only recently](https://github.com/NixOS/nixpkgs/pull/48610) and is not part of the 18.09 release

**Pull request merged**
