### PR TITLE
[Backport release-23.05] slack: 4.29.149 -> 4.34.120 (linux), 4.29.149 -> 4.34.119 (darwin)

### PR DESCRIPTION
**Pull request by SebTM**
## Description of changes

Backport #257135 // cc @delroth

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by delroth — APPROVED** [review]

**Comment by amaxine** [comment]
Can you rebase this against release-23.05 please? I don't think this technically meets the backporting guidelines but :woman_shrugging:

**Comment by delroth** [comment]
Ah, you're correct, this is the wrong branch (luckily the automated checks caught it :) )

> I don't think this technically meets the backporting guidelines

It absolutely does. What in the guidelines do you think this goes against? (for reference: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#changes-acceptable-for-releases)

**Comment by amaxine** [comment]
@delroth Each commit should be individually cherry picked with a reference to the original commit (`-x`), I don't think there's generally any exceptions to doing that when backporting changes as in this PR, rather than e.g. pulling in a singular patch to address security issues.

**Comment by delroth** [comment]
> @delroth Each commit should be individually cherry picked with a reference to the original commit (`-x`), I don't think there's generally any exceptions to doing that when backporting changes as in this PR, rather than e.g. pulling in a singular patch to address security issues.

Ah, I see what you mean - thanks for bringing this up. I don't think the guidelines explicitly *require* this per se, but it's indeed heavily recommended when the cherry picks do apply cleanly. In a case like this I don't think I have a strong preference between cherry-picking the missing series of bumps vs. just squashing it into one big commit, and I don't think this has ever come up as "something one shouldn't do" in any previous backport PR I've dealt with.

I'll bring that up on Matrix to see if others have opinions.

**Comment by delroth** [comment]
(Actually, I can fix that myself, heh.)

**Review by delroth — APPROVED** [review]

**Comment by delroth** [comment]
The opinions I got on Matrix didn't suggest that the way this backport was done should be blocking anything, so merging this to try and move the vuln remediation forward.

**Pull request merged**
