### PR TITLE
rakudo: 2021.02.1 -> 2021.05

### PR DESCRIPTION
**Pull request by stigtsp**
https://github.com/rakudo/rakudo/blob/2021.05/docs/ChangeLog

dependencies:
moarvm: 2021.02 -> 2021.05
nqp: 2021.02 -> 2021.05

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by stigtsp** [comment]
@GrahamcOfBorg build rakudo

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 126973` at 5c17943b run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built successfully:</summary>
  <ul>
    <li>moarvm</li>
    <li>nqp</li>
    <li>rakudo</li>
    <li>zef</li>
  </ul>
</details>

**Review by SuperSandro2000 — APPROVED** [review]
diff LGTM

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 126973 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>4 packages built:</summary>  <ul>    <li>moarvm</li>    <li>nqp</li>    <li>rakudo</li>    <li>zef</li>  </ul></details>

**Pull request merged**
