### PR TITLE
wine: Fix missing X11 libraries for Wayland build

### PR DESCRIPTION
**Pull request by YellowOnion**
The Wayland build provides both Wayland and X11 support

Wine still prioritizes X11 over Wayland by default, without these support libraries some things don't work, including missing cursor theme, causing some games maximize across multiple monitors, or worse to crash due to resolution support probe missing:

image

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by fufexan — APPROVED** [review]

**Comment by YellowOnion** [comment]
I'm also unsure why `isLinux` checked, line 130 has shows X11 also working on darwin, But I'm not sure on how X11 works on there to comment further.

**Comment by YellowOnion** [comment]
I've added libXfixes as per: https://wiki.winehq.org/Building_Wine

**Comment by reckenrode** [comment]
> I'm also unsure why `isLinux` checked, line 130 has shows X11 also working on darwin, But I'm not sure on how X11 works on there to comment further.

There’s a fully functional Mac driver that uses Cocoa. It would increase the closure size unnecessarily to include X11 support when it’s almost never something Darwin users should want. Perhaps instead it should be gated on a feature flag (such as `x11Support`, defaulted to `isLinux`), so if you *really* want X11 support, you can enable it on your build.

**Comment by YellowOnion** [comment]
@reckenrode that's a good idea, a simple toggle is better than broken heuristics, I don't have a mac so I can't test any new logic, I did consider that the darwin builds provided their own x11 libraries which would maybe explain it, I'll try rewrite the logic later if including xorg based x11 libraries isn't going to break x11 support on darwin.

**Comment by reckenrode** [comment]
> @reckenrode that's a good idea, a simple toggle is better than broken heuristics, I don't have a mac so I can't test any new logic, I did consider that the darwin builds provided their own x11 libraries which would maybe explain it, I'll try rewrite the logic later if including xorg based x11 libraries isn't going to break x11 support on darwin.

The Darwin builds use Cocoa and other native APIs in the Mac driver. Vulkan is implemented using MoltenVK.

If someone did enable `x11Support`, it would be fine to use the X.org libs from nixpkgs. The user would have to provide an X server since one isn’t provided by default. The normally recommended one is XQuarts. It would work but not as well as the native Mac driver (e.g., XQuartz doesn’t support Vulkan).

**Pull request merged**
