### PR TITLE
beeper: 3.109.1 -> 3.110.1

### PR DESCRIPTION
**Pull request by jiriks74**
I used an `web.archive.org` as the source for the AppImage file as the download link is currently [https://download.beeper.com/linux/appImage/x64](https://download.beeper.com/linux/appImage/x64) so I cannot fetch a specific version of the program.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by jiriks74** [comment]
Cool! I'll be looking into it tomorrow or on the weekend. 

---

I didn't know you had something like this. I'm having issues finding things that nipkgs/nix/NixOS has/does as (imho) there are multiple docs and it's hard to find some stuff because of that.

(For example I was struggling to make a Gtk package work as I had to se t some env variable to all the typelib paths, then I found `wrapGAppsHook` and the only place I could find it was some person's github page).

I tried to figure out whether I could get a direct link from the download page but I was unsuccessful so that's why I used this. I also checked if `web.archive. org` existed in the repo just to be sure it could be OK.

**Comment by jiriks74** [comment]
I'll have to look into `update-source-version` as it seems like it set a wrong hash for the source.

**Comment by jiriks74** [comment]
Ok, it looks fine now. Probably some issue with the bad internet on the train.

**Review by jshcmpbll — APPROVED** [review]
LGTM! Thanks for the update and improving the source URL 🥳

**Comment by RossComputerGuy** [comment]
Will take a look at this tonight, I might merge this later.

**Comment by RossComputerGuy** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 361944`

**Review by getchoo — APPROVED** [review]
Thanks, and welcome to Nixpkgs!

**Pull request merged**
