### PR TITLE
ocamlPackages.base64: 3.2.0 → 3.4.0

### PR DESCRIPTION
**Pull request by vbgl**
###### Motivation for this change

Use Dune 2.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 101995` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>dune-release</li>
    <li>jackline</li>
    <li>libbap</li>
    <li>python27Packages.bap</li>
    <li>python37Packages.bap</li>
    <li>python38Packages.bap</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 101995` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>dune-release</li>
    <li>jackline</li>
    <li>libbap</li>
    <li>python27Packages.bap</li>
    <li>python37Packages.bap</li>
    <li>python38Packages.bap</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 101995` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>dune-release</li>
    <li>jackline</li>
    <li>libbap</li>
    <li>python27Packages.bap</li>
    <li>python37Packages.bap</li>
    <li>python38Packages.bap</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 101995` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>dune-release</li>
  </ul>
</details>
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>jackline</li>
    <li>libbap</li>
    <li>python27Packages.bap</li>
    <li>python37Packages.bap</li>
    <li>python38Packages.bap</li>
  </ul>
</details>

**Comment by vbgl** [comment]
Thanks for your careful testing!

The failure on macOS seems unrelated to this PR.

Nonetheless, should tests of curly be disabled on that platform?

**Comment by SuperSandro2000** [comment]
> The failure on macOS seems unrelated to this PR.
> 
> Nonetheless, should tests of curly be disabled on that platform?

I don't know if it is curly directly or the test before it. I think it fails because of the sandbox. I think those tests should be disabled on darwin to make this package sandbox friendly.

**Comment by vbgl** [comment]
> I think those tests should be disabled on darwin

OK, let me do this in a different PR

**Review by sternenseemann — APPROVED** [review]
LGTM, `nixpkgs-review` on x86_64 is good

**Pull request merged**
