### PR TITLE
haskell-ci: f7ab8c -> v0.1.0.0

### PR DESCRIPTION
**Pull request by langston-barrett**
###### Motivation for this change
Update to first numbered version, released 16 days ago

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by mpickering** [comment]
I think this is now a normal hackage package so that the automatically generated version should be used rather than this manually maintained script. 

https://hackage.haskell.org/package/haskell-ci

**Comment by siddharthist** [comment]
Is there anything that needs to be done, or can we just wait for the next update of the Hackage package set?

**Comment by mpickering** [comment]
It is already in the package set. `haskellPackages.haskell-ci`.

**Comment by siddharthist** [comment]
I'll change this PR to remove this expression. Thanks for the pointer!

**Comment by mpickering** [comment]
Any updates with this?

**Comment by siddharthist** [comment]
Not yet...

**Pull request closed without merging**
