### PR TITLE
rocksdb: 6.10.2 -> 6.12.7

### PR DESCRIPTION
**Pull request by basvandijk**
###### Motivation for this change

https://github.com/facebook/rocksdb/blob/v6.12.7/HISTORY.md#6127-2020-10-14

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by basvandijk** [comment]
@GrahamcOfBorg build rocksdb

**Comment by basvandijk** [comment]
@GrahamcOfBorg build rocksdb sortmerna

**Comment by basvandijk** [comment]
@GrahamcOfBorg build rocksdb

**Comment by basvandijk** [comment]
@GrahamcOfBorg build sortmerna

**Comment by basvandijk** [comment]
Result of `nixpkgs-review pr 101559` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>bareos</li>
  </ul>
</details>
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>ceph</li>
    <li>ceph-client</li>
    <li>libceph</li>
    <li>samba4Full</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>blockbook</li>
    <li>rocksdb</li>
    <li>rocksdb_lite</li>
    <li>sortmerna</li>
  </ul>
</details>

**Comment by basvandijk** [comment]
The failures reported by `nixpkgs-review` above are all due to `ceph` failing to build. This is not due to this PR since `ceph` is already [failing on master](https://hydra.nixos.org/job/nixpkgs/trunk/ceph.x86_64-linux).

**Review by SuperSandro2000 — COMMENTED** [review]
Builds on darwin and NixOS.

**Pull request merged**
