### PR TITLE
Kernels 2021-11-02

### PR DESCRIPTION
**Pull request by TredwellGit**
###### Things done
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by fabianhjr — APPROVED** [review]
Been using 5.14.15 hardened for a day or so.

**Comment by fabianhjr** [comment]
@TredwellGit, https://www.kernel.org/ 5.15 was released yesterday. :3

(Didn't notice until today)

**Comment by fabianhjr** [comment]
Already merged: https://github.com/NixOS/nixpkgs/pull/144079

**Review by lovesegfault — APPROVED** [review]

**Comment by TredwellGit** [comment]
Can someone with permission please merge this?

**Comment by TredwellGit** [comment]
Thanks!

**Pull request merged**
