### PR TITLE
[18.09] set min version back to 1.11

### LINKED ISSUE #46387: Impossible to easily upgrade NixOS from <=17.09 to 18.09
## Issue description
Since 18.09 now forces people to update their Nix version to 2.0 (see https://github.com/NixOS/nixpkgs/pull/45779), only people running a 18.03 system will actually be able to smoothly upgrade with the default update procedure (upgrade channel, nixos-rebuild). Reason being that in versions <=17.09 the default Nix daemon version is <2.0, which means that even if you install a Nix 2.0 client, it won't succeed due to the daemon/client mismatch (see https://github.com/NixOS/nixpkgs/issues/42319).

## Potential solutions
- Improve upgrade instructions to mention that people need to do a 2-step upgrade process through 18.03
- (partial solution) Don't force people on Nix 2.0 until a later release, such that this will only be a problem when upgrading from <=17.09 to 19.03

Preferably both of those

## Workarounds
- Upgrade via 18.03
- Boot into the installer and call nixos-install
- Set nix.package = <nix 2> before upgrading

In my opinion we should revert the 2.0 forcing anyways, there's just too many problems with 2.0 yet to be addressed. There's been already 2 people in IRC with super annoying Nix upgrade process bugs since the bump 2 weeks ago.

Ping @samueldr @vcunat @grahamc @lheckemann @symphorien @ElvishJerricco

### PR DESCRIPTION
**Pull request by matthewbauer**
###### Motivation for this change

This reverts the minver.nix change as well as commits that introduced 2.0 language features. Need more feedback on whether this is okay. My impression was that this was the original intention, to make things easier on users. As a rule, we should make sure it is always be possible to upgrade yearly, so 17.03 -> 18.03 should work and 17.09 -> 18.09 should also work. Eventually we may want to make one of the biyearly releases a LTS.

Fixes #46387

*Note*: this just effects the release-18.09 branch. The minver is still 2.0 in master.

For reference, if you ever need to check for nix 1.0 support, just do ```nix-shell -p nix1 --run 'nix-env -qaP	-f.'```.

### CODE REVIEW

**Comment by Infinisil** [comment]
For reference: The 2 IRC users that had trouble updating to Nix 2.0:
- floop, 2018-09-06, [logs](https://logs.nix.samueldr.com/nixos/2018-09-06#1536265160-1536266815;), https://github.com/NixOS/nixpkgs/pull/46207
- gudea, 2018-09-08, [logs](https://logs.nix.samueldr.com/nixos/2018-09-08#1536428585-1536431006;), https://github.com/NixOS/nixpkgs/issues/46387

Also: A Nix 2.0 nix.conf apparently isn't backwards compatible with one for Nix 1.x. The second user received an additional error because of that when they tried to use the Nix 2.0 client on their NixOS 17.09 system. Inlined pastebin of their error:
```
√ nix upgrade-nix
[0.0 MiB DL] downloading 'https://github.com/NixOS/nixpkgs/raw/master/nixos/modules/installer/tools/nix-fallback-paths.nix'warning: unknown setting 'signed-binary-caches'
[0.0 MiB DL]
warning: unknown setting 'signed-binary-caches'
replacing old 'nix-2.1.1'
installing 'nix-2.1.1'
building path(s) ‘/nix/store/q37gn45a3ylpjghkfcvnla7hs5yg1jym-user-environment’
error: unsupported builtin function ‘buildenv’
builder for ‘/nix/store/ddq105fnqkda93kdl4p436h96c4fan5c-user-environment.drv’ failed with exit code 1
error: build of ‘/nix/store/ddq105fnqkda93kdl4p436h96c4fan5c-user-environment.drv’ failed
error: program '/nix/store/h180y3n5k1ypxgm1pcvj243qix5j45zz-nix-2.1.1/bin/nix-env' failed with exit code 100
```

Yes, I think that's the error you get when you try to use `nix upgrade-nix` with an older daemon running.

The whole daemon/client mismatch confusion should really be dealt with better in general if we're forcing people to upgrade.

**Comment by xeji** [comment]
> As a rule, we should make sure it is always be possible to upgrade yearly, 

I don't think we should do this.

How many users do we think this is relevant for? I would assume a big majority do not skip a version, and #46387 lists 3 viable (not even complicated) workarounds that just need to be well documented. 

Forcing ourselves to generally support upgrades from two versions back will result in a 1.5 year delay in fully using major nix updates (with beneficial new language features like placeholders) and phasing out old stuff, like deprecated options etc. It also increases the complexity of  maintenance ("this cannot be cherry-picked to stable, it uses a placeholder, not allowed in 18.09...") and is likely to generate more bugs.

**Comment by srhb** [comment]
> My impression was that this was the original intention, to make things easier on users.
From where did you get this impression?

**Comment by ElvishJerricco** [comment]
> How many users do we think this is relevant for?

One of the teams at my company has a fairly large Nix codebase, and they generally do not try to keep up with the 6 month release cycle of NixOS. I try to push them to stay within a year, e.g. the most recent upgrade was from 17.03 to 18.03. But generally I think NixOS's lack of support for things beyond 6 months is pretty bad for large companies. I would advocate for either year long support windows or occasional LTS releases.

**Comment by matthewbauer** [comment]
> From where did you get this impression?


Maybe it was a misunderstanding, but part of the idea to wait so long to up minver.nix was so that the change happened immediately _after_ the 18.09 branch off, not immediately _before_ it. It's not a huge deal either way - I think everyone agrees that we should be switching to 2.0 soon, I just thought we could provide compat in 18.09.

**Comment by srhb** [comment]
@matthewbauer I see, thanks for explaining. :)

**Comment by globin** [comment]
@ElvishJerricco we don't really have the manpower to support releases longer than we currently do. And you should be aware that there generally are no security months after 7 months.

I guess to have an extended support cycle companies would have to start being willing to pay for that at least in some form, otherwise I think it won't be sustainable.

**Comment by grahamc** [comment]
Bummer, but okay.

**Comment by ElvishJerricco** [comment]
@Ericson2314 I've noted elsewhere that at least going to 18.03 with nixos-rebuild works fine from pretty old NixOSes, because nixos-rebuild takes the Nix from the channel being installed and builds the rest of the system with that.

**Pull request merged**
