### PR TITLE
Revert the sudo-rs change: #256294, #253876

### PR DESCRIPTION
**Pull request by RaitoBezarius**
## Description of changes

As you can see on the PR discussion, this change sparked some
controversy, where the original maintainer asked for a full separation
of the `sudo` module and `sudo-rs` module, to which, the original PR
author refused to comply with.

Separations of NixOS modules in contexts of almost drop-in replacements
are not new in NixOS, prior art can be found in Forgejo/Gitea, see
248310 for an example.

Furthermore, they make sense when an "drop-in replacement" is not
totally a drop-in replacement, which is the case as this can be seen in
the issue tracker of `sudo-rs`.

In the meantime, until we obtain reasonable confidence that `sudo-rs` is
100% a drop-in replacement of `sudo`, it is not reasonable to push the
burden of a fused module maintenance on the original maintainer, even if
they did not commit anything to that module yet, which is not an
argument.

Moreover, as this can be seen in the discussion, the original maintainer
dropped the ball as they cannot reached a compromise with the original
PR author which said they would take care of this.

Nevertheless, it does not change that the PR was merged too fast (2
weeks) and caused cross compilation regressions because of ignored comments on
`buildPackages` handling which were raised early by the original
maintainer. Also, changes to the test driver were done without any look
or approval from the code owner of the test driver and without any idea
if the change can have bigger consequences.

The NixOS 23.11 release process will start in one month and two weeks,
this is too close to stabilize such a complicated change, no matter what
the original PR author believes it to be.

If such change has to pass while keeping the fused NixOS module, it will
have to wait after the 23.11 release so we have plenty of time of
testing it.

Otherwise, this change is free to be sent as another NixOS module as
recommended by the original maintainer and other NixOS developers in the
discussion.

---

This reverts commit 63ae6fa, reversing
changes made to 922926c.

This is a self-merge hotfix for the sudo-rs tests by mkg2001.
It is actually part of the PR 253876 change and the complete
revert rationale can be found there

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
cc @nbraud as you are not part of the NixOS organization so I cannot add you as a reviewer.

**Comment by delroth** [comment]
Honest question: do we have any precedent in NixOS right now for `.package` options used to swap between two separate implementations of a given binary/set of binaries? The closest that comes to mind is MySQL/MariaDB, and those are forks with a close lineage, not independent reimplementations.

I'll quote `sudo-rs`'s own documentation: "sudo-rs supports less functionality than sudo. Some of this is by design." or "Some parts of the original sudo are explicitly not in scope.", or "work may evolve beyond that target. We are also looking into alternative ways to configure sudo without the sudoers config file syntax". Rephrasing: `sudo-rs` is not attempting to be a full drop-in replacement for `sudo`, only one that works in basic/common use cases. This is further proven by several instances of `config.security.sudo.package.pname != "sudo-rs"` in this PR and the fact that the current `sudo` NixOS test suite does not pass without alteration for `sudo-rs`, which IMO are a very strong smell.

FWIW, a grep for `package.pname` in `nixos/` confirms what I thought: this is basically an unprecedented pattern, with the exception of two assertions for `searx` vs. `searxng` (which are direct forks of each other), and one assertion for `nginxQuic`. Nothing that does conditional configuration logic based on `pname` really currently exists other than what was implemented in this PR.

(Note that I'm unlikely to go into any deep technical debate here, since TBH my first round of review on the original PR was basically dismissed by the author, and it has now been proven that I actually reported a valid bug… no energy for this.)

**Comment by Ma27** [comment]
> do we have any precedent in NixOS right now for .package options used to swap between two separate implementations of a given binary/set of binaries

A precedent where it didn't work out and the maintainers of both packages agreed on a split was gitea and forgejo, see https://github.com/NixOS/nixpkgs/pull/248310 and https://github.com/NixOS/nixpkgs/issues/244866 (the discussion back then was unfortunately cluttered over a few more PRs/issues, but all of them should be linked in the two I pasted here).

**Review by bendlas — APPROVED** [review]
Let me just go ahead and approve this, because even though I wasn't invited for a review, reading through the other thread, reverting this is clearly the right move:

For 1) in https://github.com/NixOS/nixpkgs/pull/253876#issuecomment-1724232661
> the actual diff needed to support sudo-rs in the module is really tiny (everything else is refactorings and a couple new options to control behavior that was previously hardcoded)

Not familiar with the details, but this may already be the problem right there: Mixing a feature and a refactoring within a single PR is a recipe for disaster.

@nbraud, if you intend to pursue this further, I'd ask two things of you:

- please try to be more receptive towards feedback and more accommodating in your responses. laying off a PR for a few days when things get too heated, is always an option. finding new maintainers after we burned out existing ones, is not.
- separate new functionality from improving existing code's "poor condition". I know it can be tempting to "just do it", when the code is right there and you're already working on it. However, many people's systems depend on `sudo` and so improving that carries vastly greater risks than just adding a mode and it's not fair to expect somebody interested in maintaining usability of the absolute foundation of NixOS to care about the latest rust thing du jour.

for 2) ad separating modules vs growing options: I think https://github.com/NixOS/nixpkgs/issues/244866 was a lot closer call than this: forgejo is still drop-in compatible and the main reason we separated was small differences in release schedule. Also gitea is hardly what you'd call a "central component for many people's systems".

---

One thing that I think the Nix community has to continually learn and re-learn is that since our configuration language is a fully functional programming language, there is simply much less need to cram every functionality into the same modules: We have lots of freedom to experiment with almost-compatible-but-not-quite modules, and we can even share the "compatible subset" in a common dependency. All without ever getting into the weeds about whether sudo-rs is or will be fully compatible.

Various factors over the decades (mainly memory being scarce in the first few decades) have contributed to [place-oriented-programming](https://www.youtube.com/watch?v=-6BsiVyC1kM&t=243s) becoming the norm and the whole industry is hurting for it. FP does give us the chance to break free from this, but only if we decide to use that freedom. Mindlessly applying patterns that we know from other Distros can only lead us down the same path of brittle rigidity, drama and heartbreak, and if we can avoid that, we'll all be better off.

/rant

**Review by mkg20001 — CHANGES_REQUESTED** [review]
Alongside my response in the other PR (https://github.com/NixOS/nixpkgs/pull/253876#issuecomment-1729495061) I vouch for

- Not reverting the whole thing without a good reason
- Fixing cross-compile
- Maybe splitting the module (that is a revert of sudo module changes, and addition of sudo-rs)
- Reverting the test-driver change as you see fit, as it doesn't really affect anything other than stderr being visible

**Comment by mkg20001** [comment]
I've opened a competing PR https://github.com/NixOS/nixpkgs/pull/256491, which aims to move this forward instead of backward.

My resolution is to maintain sudo-rs as the module that does both sudo-rs and sudo and merge those changes into sudo itself PR after PR.

And also revert the test driver change.

**Comment by Nyabinary** [comment]
Yeah, I vouch for just fixing this instead of reverting the whole change as well. Make no sense on reverting it and delaying it more.

**Comment by delroth** [comment]
As maintainer of `sudo` I'm perfectly fine with (1) as a solution to the shared maintainership problem (and only to that problem - please don't interpret that as an LGTM from me of the approach of that PR as a whole, this is not a review of the design or the implementation of that integration of `sudo-rs` in NixOS).

From my reading of @RaitoBezarius I suspect this is not the only issue that he feels needs to be resolved though.

**Comment by bendlas** [comment]
Look, @nbraud, I fully understand the frustration that comes with having worked on a thing and then running into unexpected roadblocks. I also understand the irony of having waited for reviews only for everybody to come out of the woodwork once it's merged (even though that didn't seem to be the case here). But please understand that this whole issue is not about you personally and any criticism that you may have perceived coming your way is 100% directed just towards what I've seen in the discussions, for the limited time I'm giving myself to look into this.

All I can hope for is to help keep up some of the standards that I believe made NixOS what it is today.

I have great respect for time invested, but that can never be a substitute for due diligence and correctness, especially in NixOS where nothing stops you from scratching your own itch and publishing on NUR or wherever.

And regarding due diligence: 2 weeks may seem like a lot while waiting for reviews and responses, but it's really not, when it comes to something as central to NixOS' functionality, as `sudo` is.

> you are framing this as concern for delroth

Not only. I think @delroth can speak for himself. I have this concern for all of open source. And it's not about who can feasibly replace who. It's more about: Why do we seem to be willing to make people leave over some technical argument? Are we treating each other the same way as the faceless corpo would, that we're trying to build an alternative to? For more thoughts: https://gist.github.com/richhickey/1563cddea1002958f96e7ba9519972d9

> made me reconsider contributing to nixpkgs at all
> accepting responsibility for the sudo drv

With respect, these two approaches seem somewhat contradictory, especially if "accepting responsibility" means "replacing the existing maintainer" in this case.

I'd be as happy to welcome you, as the next person. Though please consider first if you're ready to accept that responsibility in full, before doing so. With added responsibilty, the discussions usually become more difficult (and numerous), with even more of those wibbly wobbly hard-to-decide social issues than before. We wouldn't want to burn you out either.

> I do not know why I am being told I think that, but please just stop telling people what their own thoughts are.

Nobody is telling you what you think. You've been given feedback on what you chose to write out and how it was perceived by readers.

@RaitoBezarius  said
> Also, I don't think (1) should be regarded as a solution, if anything this is a maintainer throwing the gauntlet and I don't like this and this is not something we want to encourage in the future.

:100: that. To me it didn't sound like "wow, you're doing good work, would you be willing to accept maintainership", but more like the friendliest possible version of "I give up, just take it from me".

And that's really not how I want the conversation to go when the question is: "Will sudo continue to work in the next release?". Or any conversion, for that matter.

Again, I respect your hustle, @nbraud, and your willingness to put in work.

> I am neither a native English speaker, nor neurotypical enough to express dismissal this way

IMO the perception of "dismissiveness" comes from the combination of apparently expressing strong opinions about how something ought to be done, in conjunction with not being aware of some of the surrounding issues, be they technical or social.

I honestly don't blame you for it (nor would I blame autism). It just takes time to learn the constraints of NixOS, which are different than on other distros. And until then, a certain degree of extra humility can go a long way towards bringing out the good faith in everybody.

Btw, I wouldn't call myself neurotypical either, and as it happens, I'm also an Austrian native speaker. Maybe we can meet at an Austrian Nix meetup at some point?

---

> Again, moving on.

My preferrence: Merge this, then continue with https://github.com/NixOS/nixpkgs/pull/256491

**Comment by SuperSandro2000** [comment]
> FWIW, a grep for `package.pname` in `nixos/` confirms what I thought: this is basically an unprecedented pattern, with the exception of two assertions for `searx` vs. `searxng` (which are direct forks of each other), and one assertion for `nginxQuic`. Nothing that does conditional configuration logic based on `pname` really currently exists other than what was implemented in this PR.

There is another one: locate, plocate and mlocate.

**Comment by delroth** [comment]
> > FWIW, a grep for `package.pname` in `nixos/` confirms what I thought: this is basically an unprecedented pattern, with the exception of two assertions for `searx` vs. `searxng` (which are direct forks of each other), and one assertion for `nginxQuic`. Nothing that does conditional configuration logic based on `pname` really currently exists other than what was implemented in this PR.
> 
> There is another one: locate, plocate and mlocate.

Indeed, thanks! I think this might be the only other one: looking for `hasPrefix.*\.name` also finds `mxisd` but the diff there is just finding a different executable name in the bin dir (which could be replaced by `mainProgram`, presumably) and some cosmetic filenames.

Unless people found a creative 3rd way to select based on package name 👀

**Comment by RaitoBezarius** [comment]
Also, I realize @nbraud this may come up as us pinning the blame on you, but to be clear, your PR has no problem per se as long as it is a draft or a work in progress, the big problem which caused this whole mess is the merge decision by @mkg20001 which forces us to examine the whole process.

And I think @mkg20001 took the wrong merge decision here. Of course, we don't have the perfect guidelines to let folks decide when to merge or not, but merging is very much a "I take responsibility for merging this", especially when there is controversy. It is by no mean a light decision, and that's why mergers don't go around on a merging spree in general.

Once we experience or cause catastrophic issues on master that we run to fix, we learn from that, and we keep in check that everyone tries their best at not reproducing our past mistakes, otherwise, nixpkgs cannot be sustainable.

In either case, I think we talked enough about the matter at hand, I remain available on any channel to discuss this further, but I hope this clears out the whole situation and I hope we can restart collaboration on better grounds and let the past be.

**Comment by RaitoBezarius** [comment]
Closed as superseded by many other things.

**Pull request closed without merging**
