### PR TITLE
mupdf: 1.13.0 -> 1.14.0

### PR DESCRIPTION
**Pull request by danieldk**
###### Motivation for this change

Changelog: https://mupdf.com/release_history.html

Tested on Linux and macOS. On Linux mupdf works as expected. On macOS, mupdf-gl results in the following bug:

https://bugs.ghostscript.com/show_bug.cgi?id=699726#c3

But I am not sure whether it is worth holding up the updates on Linux. mupdf-x11 probably works fine (can test this, but I have to install XQuartz).

I have redone the patches, since they did not apply cleanly.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by 7c6f434c** [comment]
I am inclined to merge, but maybe maintainers will comment either way.

@vrthra @fpletz

**Review by peti — APPROVED** [review]
:+1:

**Review by veprbl — APPROVED** [review]
Both mupdf-gl and mupdf-x11 do work on darwin

**Comment by 7c6f434c** [comment]
@veprbl Which macOS version, just out of curiousity?

@danieldk you tested on 10.13, right?

**Comment by veprbl** [comment]
@7c6f434c 
10.13.6

**Comment by danieldk** [comment]
@7c6f434c I tested on 10.14.

**Comment by 7c6f434c** [comment]
@danieldk and does the pre-update `mupdf-gl` work?

**Comment by danieldk** [comment]
@7c6f434c indeed, mupdf 1.13 works with Mojave.

**Comment by 7c6f434c** [comment]
So apparently the change itself isn't making any platform worse-off than just a rebuild of `mupdf` would.

What to do on macOS is an interesting question but not a blocker, in my opinion.

**Comment by Profpatsch** [comment]
This broke zathura with the mupdf backend.

**Comment by danieldk** [comment]
Sorry! It seems that version 0.3.4 of the PDF plugin adds mupdf 1.14 support:

https://github.com/pwmt/zathura-pdf-mupdf/commit/327c90003a05d181bba573997c11d9b1e5e596fe

I am now on a Mac, so I can't test. Maybe later today...

**Comment by Profpatsch** [comment]
Oh, there is a plugin. I looked at the drv of zathura proper and there was no update, so I thought we might be out of luck here.

**Pull request merged**
