### PR TITLE
Go: 1.9.1 -> 1.9.2 && Go: 1.8.4 -> 1.8.5

### PR DESCRIPTION
**Pull request by adisbladis**
###### Motivation for this change
Golang bugfix releases

Needs backport to 17.09

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by NeQuissimus** [comment]
@GrahamcOfBorg go

**Comment by NeQuissimus** [comment]
@grahamc I guess I am not allowed to use your Borg alter ego? :D

**Review by LnL7 — APPROVED** [review]

**Comment by NeQuissimus** [comment]
Both built for me, porting

**Comment by NeQuissimus** [comment]
217832131f and cd9ce6dd60

**Comment by adisbladis** [comment]
@NeQuissimus Thanks :)

**Comment by grahamc** [comment]
Not yet, but soon. Also borg is turned off for most of today.

Graham

**Comment by NeQuissimus** [comment]
@grahamc You should change your profile pic to the Borg Queen.

**Pull request merged**
