### PR TITLE
kde_applications: 19.08.1 -> 19.08.2

### PR DESCRIPTION
**Pull request by edolstra**
(cherry picked from commit a83d96fad50a97b0e64f84b2b9314396c889f5a1)

### CODE REVIEW

**Comment by nyanloutre** [comment]
19.08.3 is out if you want to update this

**Comment by edolstra** [comment]
@nyanloutre Thanks for the heads up, if you want to update to 19.0.3 on master, I'll add it to this PR.

**Comment by nyanloutre** [comment]
#73304 but I didn't test everything yet

**Review by ttuegel — APPROVED** [review]
Thanks! :smiley:

**Comment by ajs124** [comment]
spectacle fails to build. It's fixed on master with fda32e99e0d20e2d68ed47b15be31412982cac1c, so that should probably be backported as well.

**Pull request merged**
