### PR TITLE
lmstudio: 0.2.27 -> 0.2.31

### PR DESCRIPTION
**Pull request by crertel**
## Description of changes

**v0.2.31**

    🌋🔥 Vulkan llama.cpp engine!

    This is the official replacement for the now-removed OpenCL engine
    Expected to enable GPU acceleration for AMD, Intel (and NVIDIA) discrete GPUs!

    🤖 Support for Google's new Gemma 2 2B model

    Get it from the lmstudio-community page

    🛠️ Advanced: configure KV Cache data quantization when Flash Attention is on

    Turn on Flash Attention to see available options
    Helps reduce memory requirement for large models (Experimental)
    Note: not all models support Flash Attention.

**0.2.29**

<h3 class="anchor anchorWithStickyNavbar_LWe7" id="whats-new-with-llama-31">What's new with Llama 3.1?</h3><ul>
<li>New longer context window supporting up to 128k tokens.</li>
<li>Now available in 3 different sizes, including a new 405B parameter flagship model, and upgraded 70B &amp; 8B versions.</li>
<li>Available across 8 different languages, including English, German, French, Italian, Portuguese, Hindi, Spanish, and Thai.</li>
<li>Competitive with other leading, closed-source foundational models, including GPT-4, GPT-4o, and Claude 3.5 Sonnet.</li>
</ul>
<p><code>Llama 3.1</code> comes in three sizes: <strong>8B</strong>, <strong>70B</strong>, and <strong>405B</strong>.</p>

|Name | Description| 
|-- | --|
|8B | Relatively small, fast model, and supremely capable LLM you can run on your laptop.|
|70B | Medium-large variant that enables diverse use cases that may require more complex reasoning.|
|405B | The most extensively trained open LLM to date. Requires an extremely capable setup to run|

<hr>
<p>To use MetaAI's Llama 3.1 in LM Studio, download or update to LM Studio <strong>0.2.28</strong> or later.</p>

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by numinit** [comment]
Result of `nixpkgs-review pr 330770` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>lmstudio</li>
  </ul>
</details>

**Review by numinit — APPROVED** [review]
Runs for me.

**Review by eeedean — APPROVED** [review]
Result of `nixpkgs-review pr 330770` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>lmstudio</li>
  </ul>
</details>


looks good to me

**Review by cig0 — APPROVED** [review]
LGTM

**Comment by luochen1990** [comment]
LGTM,   and this will fix https://github.com/lmstudio-ai/lmstudio-bug-tracker/issues/57

**Comment by crertel** [comment]
Ah....it looks like we're stuck with 2 days in the Mac queue... :(

**Comment by eeedean** [comment]
> Ah....it looks like we're stuck with 2 days in the Mac queue... :(

That's always the case unfortunately. 

If you want to get that change into your own config ASAP, you can always add your fork as an additional channel (using import) -- or as an input, if you're using flakes.

**Comment by crertel** [comment]
They snuck in a release on us while we were waiting, figured I'd pull that in.

**Review by drupol — CHANGES_REQUESTED** [review]
Can you please merge the 2 bump commits into one?

**Comment by crertel** [comment]
@drupol done!

**Review by drupol — APPROVED** [review]

**Pull request merged**
