### PR TITLE
nodePackages: fix builds on x86_64-darwin

### PR DESCRIPTION
**Pull request by lilyinstarlight**
###### Description of changes

Follow-up to #193337 to fix several x86_64-darwin build failures due to missing `xcrun`/`xcodebuild` (see https://hydra.nixos.org/eval/1782541#tabs-now-fail)

I'm waiting on OfBorg to build these because I do not personally have access to any darwin systems. It probably also fixes aarch64-darwin errors, but those are additionally failing because the nodejs build had a [transient failure](https://hydra.nixos.org/build/192112047) (and the failure has been since cached - see #193331)

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lilyinstarlight** [comment]
@ofborg build bitwarden-cli epgstation joplin mastodon-bot theLoungePlugins.plugins.giphy

**Comment by lilyinstarlight** [comment]
@ofborg build bitwarden-cli epgstation joplin mastodon-bot theLoungePlugins.plugins.giphy

**Comment by veprbl** [comment]
Result of `nixpkgs-review pr 193533` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>epgstation</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>bitwarden-cli</li>
    <li>joplin</li>
    <li>mastodon-bot</li>
    <li>theLoungePlugins.plugins.giphy</li>
  </ul>
</details>

**Comment by winterqt** [comment]
FYI, we have a [patch for Node 14](https://github.com/NixOS/nixpkgs/blob/5cac465ec618cdc6e9077b447b4a5b138e482ddb/pkgs/development/web/nodejs/bypass-xcodebuild.diff) to disable the use of xcbuild (no clue why it wasn't applied to any future versions).

As part of my work on buildNpmPackage, I was going to port it to newer versions, which would (hopefully) mean that it's not required for these packages. If you'd like to do it instead, let me know -- no need to duplicate work :)

**Comment by lilyinstarlight** [comment]
> Result of `nixpkgs-review pr 193533` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
> 
> 1 package failed to build:
> * epgstation
> 
> 4 packages built:
> * bitwarden-cli
> * joplin
> * mastodon-bot
> * theLoungePlugins.plugins.giphy

@veprbl, do you have logs for that epgstation failure? It works in OfBorg



> FYI, we have a [patch for Node 14](https://github.com/NixOS/nixpkgs/blob/5cac465ec618cdc6e9077b447b4a5b138e482ddb/pkgs/development/web/nodejs/bypass-xcodebuild.diff) to disable the use of xcbuild (no clue why it wasn't applied to any future versions).
> 
> As part of my work on buildNpmPackage, I was going to port it to newer versions, which would (hopefully) mean that it's not required for these packages. If you'd like to do it instead, let me know -- no need to duplicate work :)

Ah, that would explain why it suddenly became required then! I was wondering but didn't really dive into it because I'm not too familiar with the Node.js ecosystem and just kinda wanted node2nix/nodePackages working again. I'll see if I can forward-port that patch real quick and test whether it fixes these builds as an alternative to adding `xcbuild` to stuff

(Also the buildNpmPackage stuff looks lovely and I can't wait for it to be available)

**Comment by veprbl** [comment]
Result of `nixpkgs-review pr 193533` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>bitwarden-cli</li>
    <li>epgstation</li>
    <li>joplin</li>
    <li>mastodon-bot</li>
    <li>theLoungePlugins.plugins.giphy</li>
  </ul>
</details>

**Comment by veprbl** [comment]
The failure was due to a known nix bug with sandboxing.

**Review by veprbl — APPROVED** [review]

**Comment by winterqt** [comment]
> The failure was due to a known nix bug with sandboxing.

Just for posterity, logs/what bug? (I'd build myself but I can't at the moment and figure you have them on hand :)

**Comment by lilyinstarlight** [comment]
Could either of you run `nix build github:lilyinstarlight/nixpkgs/fix/nodepackages-darwin-v2#bitwarden-cli` on darwin to see if nodejs and bitwarden-cli build with just the xcodebuild patch?

That branch is effectively @winterqt's suggestion above, but I don't have a Mac to test it on

**Comment by veprbl** [comment]
> > The failure was due to a known nix bug with sandboxing.
> 
> Just for posterity, logs/what bug? (I'd build myself but I can't at the moment and figure you have them on hand :)

This one https://github.com/NixOS/nix/issues/2311

**Comment by lilyinstarlight** [comment]
@winterqt, I tested out my branch in the macOS runner in GitHub Actions and it does look like just forward-porting that patch will work to remove the need for xcbuild in these packages

It also looks like the `buildNodejs` function patches xcode_emulation.py in `postPatch` and `postInstall` to deal with lack of Xcode, but not in a way that seems to work with any recent Node.js versions. So I could instead update that to patch it in a somewhat interpreter agnostic way -- it could just be somewhat fragile and version-specific patches like the one for v14 may be better long-term

Also, I'm assuming a PR to patch Node.js to avoid the need for xcbuild would have to go to staging, since touching `nodejs` makes quite a few rebuilds (~1k on x86_64-linux alone) even if it is a low-risk change?

**Comment by winterqt** [comment]
> It also looks like the `buildNodejs` function patches xcode_emulation.py in `postPatch` and `postInstall` to deal with lack of Xcode, but not in a way that seems to work with any recent Node.js versions.

It looks like the patches you talk about are *ancient* (introduced in 822abc49adc7b130e3bdc99bdfaf2503a6cf699d), so that doesn't surprise me. We can definitely drop them in favor of version-specific patches, IMO.

> Also, I'm assuming a PR to patch Node.js to avoid the need for xcbuild would have to go to staging, since touching `nodejs` makes quite a few rebuilds (~1k on x86_64-linux alone) even if it is a low-risk change?

The high amount of rebuilds was caused by your nodePackages change, I presume. I think that's a candidate for staging then, yes. (@vcunat can confirm, though.)

> Edit: I also did not see any reason that patch was dropped for the v16 update in #120008

Yeah, I assume it was just forgotten about. 😔

**Comment by vcunat** [comment]
> Also, I'm assuming a PR to patch Node.js to avoid the need for xcbuild would have to go to staging, since touching `nodejs` makes quite a few rebuilds (~1k on x86_64-linux alone) even if it is a low-risk change?

Yes, sounds like `staging` to me.  (Doesn't sound urgent, like security fixes.)

**Comment by winterqt** [comment]
@lilyinstarlight Your nodePackages PR added, at most, 500 packages to this rebuild count -- any clue what the other 500+ packages that would be affected by the Node change would be? I'd really only think it would be nodePackages at the most (at least now, since it's not using Node 14), though we also have assorted web apps and such.

**Comment by vcunat** [comment]
OfBorg lists all rebuilt packages if you click on details.

**Comment by winterqt** [comment]
> OfBorg lists all rebuilt packages if you click on "Details" on the "ofborg-eval" line.

Somehow I forgot this... thanks.

**Comment by lilyinstarlight** [comment]
I've opened #193759 targeting staging with the change to patch nodejs as before and reverted some of the changes from this PR that added `xcbuild` in overrides

**Pull request merged**
