### PR TITLE
erlang: 20.1.7 -> 20.2.2

### PR DESCRIPTION
**Pull request by ankhers**
###### Motivation for this change

Update ErlangR20

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by LnL7** [comment]
@GrahamcOfBorg build erlangR20

**Comment by grahamc** [comment]
I increased the timeouts on my linux builder and the aarch64 builder to 3600s. Let's try this again.

**Comment by grahamc** [comment]
@GrahamcOfBorg build erlangR20

**Comment by ankhers** [comment]
@grahamc Another timeout :(

**Comment by ankhers** [comment]
Another version of Erlang was just released. Should I close this PR and open a new one, should I squash the commits, or something else entirely?

**Comment by orivej** [comment]
I have amended the PR as necessary and merged. Thank you!

**Pull request merged**
