### PR TITLE
zeek: add zeek module and fix zeekctl to deploy it.

### PR DESCRIPTION
**Pull request by GTrunSec**
###### Motivation for this change
Re-open PR by https://github.com/NixOS/nixpkgs/pull/86435.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by GTrunSec** [comment]
-  sudo systemctl status zeek.service

**Comment by GTrunSec** [comment]
-  sudo systemctl status zeek.service

**Comment by GTrunSec** [comment]
@tobim @marsam @pSub. I can not pass the Zeekctl on NixOS. I still got an error output like this 
`Error: cannot create working directory for zeek` (https://github.com/zeek/zeekctl/blob/7e65a34905ec9684c442da5f737fe75beb94aae6/ZeekControl/control.py#L175

  if you have time do a PR test or debug this issue. I really confuse what happed about this error outpout. I can deploy it and work well on other Linux which installed nix.

**Comment by tobim** [comment]
@GTrunSec I appreciate you put in so much work into that. I hope to be able to free up some time to help debug this during the next couple of days.

I suspect the error you get is a result of zeekctl trying to create a folder in the `PREFIX` where zeek is installed, which in case of nixos is in the store, which is mounted read-only by default.

**Comment by GTrunSec** [comment]
@tobim first of all, Thank you so much help to debug it.

I think this issue from Spool/zeek could not be created.

image
invalid `Spool/zeek` hardlink to `logs/current`

**No Zeek directory under Spool dir**
- let we look at the zeekctl testing what it did.
>  Create Zeek's working directory, chdir to that dir, and create rotated logs
mkdir $ZEEKCTL_INSTALL_PREFIX/spool/zeek
cd $ZEEKCTL_INSTALL_PREFIX/spool/zeek
cat > ${origtestlog} << _EOF_
 This is a test zeekctltest.log
_EOF_
- Start process.
>  verify that these files don't already exist before the start command runs
test ! -e $ZEEKCTL_INSTALL_PREFIX/spool/zeek
test ! -e $ZEEKCTL_INSTALL_PREFIX/spool/stats.log
zeekctl start > start.out
 the start command creates some files (these are NOT created by zeek itself)
while read line; do
    test -e $ZEEKCTL_INSTALL_PREFIX/$line
done << EOF
spool/zeek/.cmdline
spool/zeek/.env_vars
spool/zeek/.pid
spool/zeek/.startup
spool/zeek/stderr.log
spool/zeek/stdout.log

- On Debian OS I got all of the outputs in here.
**Valid Zeek directory and hard link.**
image
image

**Comment by GTrunSec** [comment]
I even can not deploy the localhost mode of Zeek which installed without the nix-store on NixOS.
- test nix-shell
https://github.com/hardenedlinux/debian-nix-manager/blob/master/pkgs/zeek/zeek-shell/zeek-shell.nix
`nix-shell zeek-shell.nix --command "make -j8 all && sudo make install"`

**Comment by tobim** [comment]
It looks like zeekctl is trying to run `['mkdir', '-p', '/var/lib/zeek/spool/zeek']` through ssh, as if the host IP belongs to a worker node, even when using `type=standalone` in node.cfg.

**Comment by GTrunSec** [comment]
@tobim 
- I have no idea how to fix the issue for Zeekctl. 

> if we did not solve the Zeekctl problem which running on NixOS(sandbox mode). I'm going to write a Systemd of Zeek for NixOS that can be running with some arguments of the interface instead of zeekctl to deploy it.

**Without Zeekctl deploy**
- systemd workindDirecotry /var/lib/zeek/logs
```.
./run-zeek -1 -i eno1 -U .status -p zeekctl -p zeekctl-live -p standalone -p local -p zeek local.zeek zeekctl zeekctl/standalone z
```
image

**Comment by GTrunSec** [comment]
@tobim @marsam @pSub. ready to take a test for the maintainer. everything goes well.
Zeek's module  test setting:
```
services.zeek = {
  enable = true;
  standalone = true;
  interface = "eno1";
  listenAddress = "localhost";
  privateScript = ''                                                            
  @load /home/gtrun/project/hardenedlinux-zeek-script/scripts/zeek-query.zeek   
  '';
};                                                                              
```
- check privateScript loading Status:
```
more /var/lib/zeek/logs/current/loaded_scripts.log      
  /home/gtrun/project/hardenedlinux-zeek-script/scripts/zeek-query.zeek
/nix/store/g4al63qrpx8ckf6bkimam6w3wps1imav-zeek-3.0.5/share/zeek/zeekctl/standalone.zeek
  /var/lib/zeek/spool/installed-scripts-do-not-touch/auto/standalone-layout.zeek
  /nix/store/g4al63qrpx8ckf6bkimam6w3wps1imav-zeek-3.0.5/share/zeek/policy/misc/trim-trace-file.zeek
/nix/store/g4al63qrpx8ckf6bkimam6w3wps1imav-zeek-3.0.5/share/zeek/zeekctl/auto.zeek
  /var/lib/zeek/spool/installed-scripts-do-not-touch/auto/local-networks.zeek
```
- sudo systemctl status zeek.service
```
zeek.service - Zeek Daemon
     Loaded: loaded (/nix/store/nal9g7ih8idk27pajvdxbbid4y18mgsc-unit-zeek.service/zeek.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2020-05-07 20:07:36 PDT; 1min 6s ago
    Process: 7985 ExecStartPre=/nix/store/xcs2xvn398hgsp0gz3slhlv02qljnhm0-unit-script-zeek-pre-start (code=exited, status=0/SUCCESS)
   Main PID: 8034 (bash)
         IP: 0B in, 0B out
      Tasks: 18 (limit: 4915)
     Memory: 82.4M
        CPU: 18.158s
     CGroup: /system.slice/zeek.service
             ├─8034 /nix/store/kgp3vq8l9yb8mzghbw83kyr3f26yqvsz-bash-4.4-p23/bin/bash /nix/store/zkrr30qd8acjdnwk89gp3fa6jjss4rdg-zeek-o>
             ├─8148 /nix/store/kgp3vq8l9yb8mzghbw83kyr3f26yqvsz-bash-4.4-p23/bin/bash /var/lib/zeek/scripts/run-zeek -1 -i eno1 -U .stat>
             └─8158 /nix/store/g4al63qrpx8ckf6bkimam6w3wps1imav-zeek-3.0.5/bin/zeek -i eno1 -U .status -p zeekctl -p zeekctl-live -p sta>

May 07 20:07:36 nixos bash[8042]: generating standalone-layout.zeek ...
May 07 20:07:36 nixos bash[8042]: generating local-networks.zeek ...
May 07 20:07:36 nixos bash[8042]: generating zeekctl-config.zeek ...
May 07 20:07:36 nixos bash[8042]: generating zeekctl-config.sh ...
May 07 20:07:36 nixos bash[8148]: max memory size         (kbytes, -m) unlimited
May 07 20:07:36 nixos bash[8148]: data seg size           (kbytes, -d) unlimited
May 07 20:07:36 nixos bash[8148]: virtual memory          (kbytes, -v) unlimited
May 07 20:07:36 nixos bash[8148]: core file size          (blocks, -c) unlimited
May 07 20:07:36 nixos bash[8158]: listening on eno1
May 07 20:07:46 nixos bash[8158]: 1588907266.826376 warning in /nix/store/g4al63qrpx8ckf6bkimam6w3wps1imav-zeek-3.0.5/share/zeek/base/mi
```

**Comment by GTrunSec** [comment]
- fixed archive logs  (paths)
```
/var/lib/zeek/logs
├── 2020-05-07
│   └── conn-summary.22:05:32-22:57:10.log.gz
└── current
    ├── conn.log
    ├── dns.log
    ├── known_services.log
```

**Comment by GTrunSec** [comment]
add Option: to override some arguments that alternative installs Zeek's plugin or not.

**Comment by GTrunSec** [comment]
Does anyone give me some feedback about this PR?  let me know that to keep going deep work for this module on NixOS or not. Make sure I am doing the right direction on the way.  @marsam @pSub  @tobim Thanks. Sorry to bother you.

**Comment by GTrunSec** [comment]
@ryantm  resolved the merge conflict. Thanks for reviewing.

**Comment by koalaeagle** [comment]
Seems like this is exactly what I was looking for on NixOS. Still learning NixOS, but appreciate the effort trying to sort out a somewhat complicated package/module.

**Pull request closed without merging**
