### PR TITLE
Plasma 5.17.5

### PR DESCRIPTION
**Pull request by ttuegel**
###### Motivation for this change

Update Plasma from 5.16.5 to 5.17.5. Status: I can start a Plasma session in a QEMU virtual machine. There is one issue with the SDDM theme which I consider blocking, and one non-blocking annoyance with `plasma-desktop`.

**TODO:**

- [x] Fix the SDDM theme's background. At present, the background is blank (white).
- [ ] Fix the default desktop cursor. The cursor is correctly themed in other applications, but the desktop displays the default X11 cursor.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by worldofpeace** [comment]
Hi @ttuegel, freeze is soon https://discourse.nixos.org/t/nixos-20-03-feature-freeze/5655.
I don't see too many blockers here, do you need this in 20.03?

**Comment by peterhoeg** [comment]
How about giving the 5.18 beta a try to see if that solves your problem? We could then skip straight to that when it's released in a weeks time.

**Comment by ttuegel** [comment]
> How about giving the 5.18 beta a try to see if that solves your problem?

The problem is almost certainly a missing runtime dependency. Going up a version is likely to introduce _more_ missing dependencies. :slightly_frowning_face:

**Comment by ttuegel** [comment]
> I don't see too many blockers here, do you need this in 20.03?

Yes, I plan to get this merged before the feature freeze for NixOS 20.03.

**Comment by ttuegel** [comment]
Well, the `plasma-workspace` build system appears to assume it's running in a Wayland or X session, so I hope that's not critical for the build... :man_facepalming:

**Comment by ttuegel** [comment]
The blocker is fixed. The non-blocking issue, I realized, is due to some changes not being ported from the start-up script to the new C++ executable. I think it is appropriate to move those to the NixOS Plasma 5 start-up script, instead of the `plasma-workspace` package, because they are NixOS-specific. Although these are non-blocking cosmetic issues, I would still like to deal with them before merging.

**Comment by worldofpeace** [comment]
> The blocker is fixed. The non-blocking issue, I realized, is due to some changes not being ported from the start-up script to the new C++ executable. I think it is appropriate to move those to the NixOS Plasma 5 start-up script, instead of the `plasma-workspace` package, because they are NixOS-specific. Although these are non-blocking cosmetic issues, I would still like to deal with them before merging.

I believe such a change would qualify as a bugfix so you have during beta to produce such a change.

**Comment by ttuegel** [comment]
> I believe such a change would qualify as a bugfix so you have during beta to produce such a change.

Yeah, you're right. I don't like merging something that I know is buggy, but at least merging this part reduces the bus factor.

**Comment by worldofpeace** [comment]
> > I believe such a change would qualify as a bugfix so you have during beta to produce such a change.
> 
> Yeah, you're right. I don't like merging something that I know is buggy, but at least merging this part reduces the bus factor.

I opened an issue in the tracker so it doesn't get lost.

**Pull request merged**
