### PR TITLE
brave: add update script

### PR DESCRIPTION
**Pull request by danieldk**
###### Motivation for this change

The Brave package often seems to get very outdated. This is bad for a
browser, where vulnerabilities are high impact.
    
This change adds an update script, so that r-ryantm will suggest
updates. We find the latest version using their Debian package
database (since we are using the Debian package anyway).

While at it, use the update script to update Brave ;):

brave: 1.18.75 -> 1.18.77
    
Changelog:
https://community.brave.com/t/release-channel-1-18-77/191009

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lourkeur** [comment]
Great idea, I knew we needed such a script but I didn't know how to do it. I ran the script, my results are consistent with yours

A quick suggestion from my experience looking at a few brave PRs: the list of shared objects has to be maintained by hand. An easy way to know if it's good is to just run `brave --version`: if there's something missing it will crash, otherwise it just exits. I believe ofborg runs installCheck; we could put it in there so that we know immediately if it's good or not.

Capture d’écran de 2020-12-31 12-39-21

**Comment by lourkeur** [comment]
fleshed out my suggestion:
```nix
  doInstallCheck = true;
  installCheckPhase = ''
    # call directly because upstream wrapper suppresses errors
    $out/opt/brave.com/brave/brave --version
  '';
```
If you intentionally mess up the rpath:
```
/nix/store/z378c0l156zyvj91fq3d79rr30xsb91n-brave-1.18.77/opt/brave.com/brave/brave: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory
```
Otherwise, it passes

**Comment by danieldk** [comment]
> fleshed out my suggestion:
> 
> ```nix
>   doInstallCheck = true;
>   installCheckPhase = ''
>     # call directly because upstream wrapper suppresses errors
>     $out/opt/brave.com/brave/brave --version
>   '';
> ```
> 
> If you intentionally mess up the rpath:
> 
> ```
> /nix/store/z378c0l156zyvj91fq3d79rr30xsb91n-brave-1.18.77/opt/brave.com/brave/brave: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory
> ```
> 
> Otherwise, it passes

Sounds good! Could you open a PR for this?

**Review by nasirhm — APPROVED** [review]
LGTM, Thank you for working on it @danieldk .

**Review by otavio — APPROVED** [review]

**Review by bbjubjub2494 — APPROVED** [review]

**Comment by danieldk** [comment]
Thanks for the reviews! 👍

**Pull request merged**
