### PR TITLE
postgresql: Move socket dir to /run/postgresql

### PR DESCRIPTION
**Pull request by aszlig**
The default, which is `/tmp`, has a few issues associated with it:

One being that it makes it easy for users on the system to spoof a PostgreSQL server if it's not running, causing applications to connect to their provided sockets instead of just failing to connect.

Another one is that it makes sandboxing of PostgreSQL and other services unnecessarily difficult. This is already the case if only `PrivateTmp` is used in a systemd service, so in order for such a service to be able to connect to PostgreSQL, a bind mount needs to be done from `/tmp` to some other path, so the service can access it. This pretty much defeats the whole purpose of `PrivateTmp`.

We regularly run into issues with this in the past already (one example would be https://github.com/NixOS/nixpkgs/pull/24317) and with the new systemd-confinement mode upcoming in https://github.com/NixOS/nixpkgs/pull/57519, it makes it even more tedious to sandbox services.

I've tested this change against all the postgresql NixOS VM tests and they still succeed and I also grepped through the source tree to replace other occasions where we might have /tmp hardcoded. Luckily there were very few occasions.

### CODE REVIEW

**Comment by danbst** [comment]
:+1: would be awesome if it was changed to `/var/run/postgresql`, as Debian/Ubuntu use that path by default. See https://sources.debian.org/src/postgresql-11/11.2-2/debian/patches/51-default-sockets-in-var.patch/ , but I guess `/run` and `/var/run` are mounted to each other in every distribution, so not a big deal.

Also, add release notes, because it can make old `psql` not to connect to new postgresql via UNIX socket.

**Comment by aszlig** [comment]
> Also, add release notes, because it can make old `psql` not to connect to new postgresql via UNIX socket.

Yep, that's why I added that label, just wanted to see first whether there is any opposition.

**Review by thoughtpolice — APPROVED** [review]
LGTM, pending a release note addition as @danbst asked.

**Comment by aszlig** [comment]
@thoughtpolice, @danbst: Done.

**Comment by danbst** [comment]
BTW, this should be only for Linux system, right? Does darwin platform have `/run`? cc @basvandijk

**Comment by aszlig** [comment]
@danbst: Hm, good catch, but even if OSX would have `/run`, it probably won't have `/run/postgresql`. So I'm going to make this Linux-only.

**Comment by flokli** [comment]
@aszlig what's the socket path that PHP defaults to when connecting to a local postgresql?

Is there a way to tweak this one, similar to how I did for mysql in 5bb85cd45ce96a8c48e089711eead4129c36baf8?

**Comment by aszlig** [comment]
@flokli: I haven't checked PHP in particular but I'd assume that it's using the default one in libpq like most other software.

**Comment by flokli** [comment]
@aszlig if that's the case, shouldn't overriding `DEFAULT_PGSOCKET_DIR` in this PR also make PHP find the proper socket path automatically?

**Comment by aszlig** [comment]
@flokli: Exactly that is the idea. Just checked the PHP source and they rely fully on `libpq` and there is no NIH implementation. So this also covers PHP unless of course someone uses `/tmp` as the hostname in `PDO`/`pg_connect`, but see the changelog entry.

**Comment by puckipedia** [comment]
This PR seems to have broken the build of hydra, since it doesn't use the systemd service to launch postgresql and as such, it doesn't have a `/run/postgresql` to put the socket into...

**Comment by flokli** [comment]
can we tweak the hydra module to simply enable the postgresql module through `services.postgresql`?

**Comment by flokli** [comment]
wait, I don't get it - the hydra module already uses the postgresql module, and this one should set up `/run/postgresql` through `RuntimeDirectory = "postgresql"`…

**Comment by puckipedia** [comment]
no, that part's fine. It's during doCheck that it fails: https://hydra.nixos.org/build/91221682

**Comment by flokli** [comment]
@puckipedia we also can't just mkdir -p /run/postgresql in hydra's `preCheck`, as the sandbox doesn't allow to write to `/run`.

We however might be able to tweak hydra's `tests/` to pass `-k /tmp` when instructing postgresql commands, didn't check.

**Comment by danbst** [comment]
Very unfortunate situation. I tend to revert this, and reapply when Nix does allow creating `/run/postgresql`. It can even be a build setup hook for `postgresql`, but Nix doesn't allow `/run` directory....

@aszlig what do you think?

**Comment by aszlig** [comment]
@danbst: Nix doesn't need to allow this, because you can simply set PGHOST during `preCheck` to use a different socket path.

**Comment by aszlig** [comment]
eg, similar to: https://github.com/nixcloud/nixcloud-webservices/blob/d8b966f8d25c08e9445fa9a28ba850afc2ffcc2d/modules/web/database/postgresql-hook.sh#L1

**Comment by danbst** [comment]
I just see it as regression - previously it was possible to do `pg_ctl -D ... start` and `psql`, but now you have specify socket directory both for server and client. It was useful...

Probably the best approach would be to patch postgres server to create socket in `unix_socket_dir`, and if it is not set, then create in `/run/user/$(id -u)`, and if it doesn't exist, then use `/run/postgresql`. And implement same search logic for `psql` - first search in host argument/PGHOST, and if not specified, then in `/run/user/$(id -u)`, if not found then search in `/run/postgresql`. This would still require Nix to allow `/run` directory and require setup hook for postgresql, to make things flawless.

**Comment by danbst** [comment]
Added a discussion topic here https://www.postgresql.org/message-id/CANZg%2Byd2OdqxM%3DHwnrkT-QecNMqLKNp%2BbGO_2SirJGznGK6h_w%40mail.gmail.com

Meanwhile, we just have to mention in release notes that `pg_ctl` should use custom socket dir (XDG_RUNTIME_DIR for users, /tmp for nix build environment) both for client and server.

**Comment by flokli** [comment]
@danbst can we either revert this PR, or add a fetchpatch `https://github.com/NixOS/hydra/pull/648/commits/4171ab4c4fd576c516dc03ba64d1c7945f769af0.patch` to get Hydra to build again?

**Comment by tilpner** [comment]
I believe this might also fix a race condition between `systemd-tmpfiles` (caused by `boot.cleanTmpDir`) and postgres, that causes the socket to be deleted on boot.

**Comment by flokli** [comment]
@tilpner another reason to run systemd-tmpfiles as part of sysinit.target, before every other "regular" service ;-)

see https://github.com/NixOS/nixpkgs/pull/56265#issuecomment-487936452 and following.

cc @aanderse @erikarvstedt

**Comment by LnL7** [comment]
This breaks postgres outside of NixOS, this shouldn't be patched but handled in the nixos modules instead IMHO.

**Comment by danbst** [comment]
@LnL7 true, but outside NixOS it is easy fixable with `-h /tmp` in client CLI arg, and `-k /tmp` server CLI arg. I agree this is less convenient, but sharing sockets through /tmp isn't generally safe in multiuser setup.

**Comment by LnL7** [comment]
That doesn't matter, the default usage is broken because of non-standard behaviour. If this was a change in postgresql it would be another story.

**Comment by edolstra** [comment]
While I think getting rid of sockets in `/tmp` is great (including `/tmp/.X11-unix` and `/tmp/.ICE-unix` while we're at it), it would be better if this were done upstream rather than in NixOS-specific patches.

**Comment by tilpner** [comment]
So revert this PR and pass `-k /run/...` from the module?

**Comment by aanderse** [comment]
Is anyone in favor of a `socket` option (potentially `readOnly`) so we can stop using so many magic strings all over NixOS modules every time we want to refer to a socket? Other modules like `mysql` would benefit from this as well. If so, let me know and I can whip something up.

**Comment by danbst** [comment]
@LnL7 unfortunately, it was already "non-standard", depending on what is "standard". Ubuntu (and Debian afaik) uses `/var/run/postgresql` as a de-factor standard socket path (same as we do now).

@edolstra Upstream doesn't work to improve this. https://www.postgresql.org/message-id/25758.1553906401%40sss.pgh.pa.us

@tilpner no, because PG consists of "server" and "client". And PG wants both to have same config parameter. So either both use same location, or they don't communicate each other.

**Comment by edolstra** [comment]
@danbst Well, Tom Lane isn't wrong about "a Babel of servers and clients that can't talk to each other", as this issue shows...

Having said that, the fact that Ubuntu/Debian already use `/run/postgresql` is probably more relevant to us than what upstream does.

**Comment by LnL7** [comment]
Unlike the apt packages, nix won't ensure these defaults are functional however.

**Pull request merged**
