### PR TITLE
 nixpkgs-check-by-name test that fails multiple validity checks 

### LINKED ISSUE #274345: `nixpkgs-check-by-name` should have a test for multiple simultaneous failures
The `nixpkgs-check-by-name` tool that checks the [`pkgs/by-name`](https://github.com/NixOS/nixpkgs/tree/master/pkgs/by-name) directory uses [various checks](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test/nixpkgs-check-by-name/README.md#validity-checks).

A notable feature is that it can report multiple failures at once:
```
$ cd ~/src/nixpkgs
$ mkdir -p pkgs/by-name/fo/bar
$ $(nix-build -A tests.nixpkgs-check-by-name)/bin/nixpkgs-check-by-name .
pkgs/by-name/fo/bar: Incorrect directory location, should be pkgs/by-name/ba/bar instead.
pkgs/by-name/fo/bar: Missing required "package.nix" file.
Validation failed, see above errors
```

The tool currently only has tests for single errors. There should be a test to test multiple failures together, ideally as many of them as possible.

See [here](https://github.com/NixOS/nixpkgs/tree/master/pkgs/test/nixpkgs-check-by-name#tests) for how tests can be declared.

### PR DESCRIPTION
**Pull request by keanuk**
## Description of changes
Added a test to nixpkgs-check-by-name that fails multiple validity checks, the list of tests failed are in the `expected` file.
Attempt to address #274345

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by infinisil — APPROVED** [review]
That's great, thanks a lot!

**Comment by infinisil** [comment]
Ah one thing, check out the [commit conventions](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions), in particular:
- Only use a single commit for this change
- Use `tests.nixpkgs-check-by-name: ...` as the prefix of the commit, this will also automatically trigger CI to build it

**Comment by infinisil** [comment]
@keanuk Gentle ping, can you follow up on this? :)

**Comment by keanuk** [comment]
> @keanuk Gentle ping, can you follow up on this? :)

I'm so sorry for the delay, I think it's correct now but let me know if there's still any problems

**Comment by infinisil** [comment]
I pushed a change myself in order to align with the changes from https://github.com/NixOS/nixpkgs/commit/aa7dd0b5964f4b8b8f3bd542d2883296b249d68b.

However, now CI is failing due to the new check that makes sure all Nix files can be parsed, merged just yesterday in https://github.com/NixOS/nixpkgs/pull/279892 :sweat_smile:

We could just ignore that, because the check only checks for files _changed_ in a PR, so it wouldn't break master. Notably there's already another test case that has [an invalid Nix file](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test/nixpkgs-check-by-name/tests/ref-parse-failure/pkgs/by-name/aa/aa/invalid.nix).

I guess we could consider removing the check for invalid Nix files entirely, since that's already covered by the new CI check. I'll follow up on this myself!

**Pull request merged**
