### PR TITLE
x42-plugins: add xz so it can unpack itself

### PR DESCRIPTION
**Pull request by magnetophon**

### CODE REVIEW

**Comment by vcunat** [comment]
- You only added `xz` to parameters, but the derivation itself is unaffected.
- Our stdenv does contain `xz` by default (at least on Linux).

**Comment by vcunat** [comment]
Oh, I see a Hydra error `don't know how to unpack`. Let me have a look.

**Comment by magnetophon** [comment]
@vcunat odd, huh? obviously this expression worked just fine without the xz before...

**Comment by vcunat** [comment]
It certainly should work without including `xz`, but I want to inspect http://hydra.nixos.org/build/26145249 more closely. It could be that it's transient and e.g. it just got killed in precisely bad moment for some reason.

**Comment by magnetophon** [comment]
@vcunat, well, the whole reason for this PR is that it stopped compiling for me locally (latest 15.09), so that rules out a transient, doesn't it?

**Comment by vcunat** [comment]
Oh, really? I can't reproduce it on the exact commit that Hydra fails.

**Comment by magnetophon** [comment]
hmm, I'll try again locally then. one sec...

**Comment by magnetophon** [comment]
guess what:  it's building.
what could cause something like this???

**Comment by vcunat** [comment]
There are loads of improbable things that could cause it: tar or xz failing for a random reason, or insufficient memory or drive space, or some oneshot HW failure...

The only suspicious thing left about this is that *both* you and Hydra had the same problem.

**Comment by magnetophon** [comment]
exactly, that's what makes it odd

**Comment by magnetophon** [comment]
@vcunat Anyway, I'll close this for now.
Let me know if you find out what's causing this.
I wouldn't know where to start looking...   (but would love to learn!)

**Comment by vcunat** [comment]
OK. I will no longer actively look into this, so it's likely we will never find out if it disappears by itself now.

**Comment by vcunat** [comment]
No, it re-appears on a different branch and both platforms on Hydra. This isn't just a random error.

**Comment by magnetophon** [comment]
@vcunat hmmm...  How can I help fixing this?

**Comment by vcunat** [comment]
The problem seems to have gone away on Hydra: http://hydra.nixos.org/job/nixos/release-15.09/nixpkgs.x42-plugins.x86_64-linux

**Comment by vcunat** [comment]
Hmm, no, it seems to behave completely randomly http://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.x42-plugins.x86_64-linux. No ideas.

**Pull request closed without merging**
