### PR TITLE
apptainer: 1.2.4 -> 1.2.5

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Changelog: https://github.com/apptainer/apptainer/releases/tag/v1.2.5

cc @ShamrockLee 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 269324` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>apptainer</li>
    <li>apptainer-overriden-nixos</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
`apptainer-image-hello-cowsay.img` builds fine as well.

**Review by ShamrockLee — APPROVED** [review]
Verified the vendorHash with nix-prefetch and tested the image-running functionality. LGTM.

**Comment by mirkolenz** [comment]
Is it possible to backport this to `23.11`? We use the latest NVIDIA driver and need the upstream fix included in this release. We currently target the unstable channel, but that is not ideal for our GPU server. Would greatly appreciate that!

**Comment by infinisil** [comment]
@mirkolenz Sounds good! If you test the backport PR I'll merge it :)

**Comment by mirkolenz** [comment]
Thanks for the fast response! I will try it tomorrow and let you know if it works. 😊

**Comment by ShamrockLee** [comment]
> If you test the backport PR I'll merge it :)

For both `apptainer` and `singularity`, `passthru.tests.image-hello-cowsay` is the test case which is itself an image package built with the package to test and `singularity-tools.buildImale`. This means
1. If the CI builds the `passthru.tests` successfully, we are sure that basic image building functionality of the binary works alright.
2. It can be used to test basic image running functionality

```bash
set -eu -o pipefail

FLAKE_URL=github:NixOS/nixpkgs/backport-269324-to-23.11
IMAGE="$(nix build -L "$FLAKE_URL"#singularity.passthru.tests.image-hello-cowsay --print-out-paths)"
nix run "$FLAKE_URL"#singularity exec "$IMAGE" hello \
  | nix run "$FLAKE_URL"#singularity exec "$IMAGE" cowsay
```

As for the Nvidia GPU, I don't have a way to actually test it, since I haven't found a way to get the Nvidia card work on my laptop.

**Comment by mirkolenz** [comment]
Thanks for providing me with this excellent snippet! I executed the following version without issues:

```shell
#!/usr/bin/env bash
set -eu -o pipefail

FLAKE_URL=github:NixOS/nixpkgs/backport-269324-to-release-23.11
IMAGE="$(nix build -L "$FLAKE_URL"#singularity.passthru.tests.image-hello-cowsay --print-out-paths)"
nix run "$FLAKE_URL"#singularity exec "$IMAGE" hello \
  | nix run "$FLAKE_URL"#singularity exec "$IMAGE" **cowsay**
```

Here is the output:

```txt
INFO:    Converting SIF file to temporary sandbox...
INFO:    Converting SIF file to temporary sandbox...
WARNING: passwd file doesn't exist in container, not updating
WARNING: group file doesn't exist in container, not updating
WARNING: passwd file doesn't exist in container, not updating
WARNING: group file doesn't exist in container, not updating
INFO:    Cleaning up image...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_TERMINAL = "iTerm2",
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
 _______________
< Hello, world! >
 ---------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
INFO:    Cleaning up image...
```

I also rebuilt my system configuration using `nixpkgs.url = "github:nixos/nixpkgs/backport-269324-to-release-23.11";` in my flake. It worked without any issues as well and the GPU is working as expected:

```console
$ apptainer run --nv docker://pytorch/pytorch python -c "import torch; print(torch.cuda.is_available())"
INFO:    Using cached SIF image
INFO:    gocryptfs not found, will not be able to use gocryptfs
True
```

**Comment by infinisil** [comment]
Awesome thanks! Merged the backport :)

**Pull request merged**
