### PR TITLE
Beets: fix keyfinder plugin (did not work) and add copyartifacts plugin

### PR DESCRIPTION
**Pull request by michalrus**
###### Motivation for this change
1. `keyfinder` did not work.
2. `copyartifacts` is a useful plugin to copy some album extras (scans, logs, cues etc.) along with the audio files
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend — none do.
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Profpatsch** [comment]
Huh, we should really add tests for beets. It’s work to test it without modifying my local database/music collection. :(

**Comment by michalrus** [comment]
@Profpatsch, what do you mean exactly?

Please, notice that in this PR:

* I fixed keyfinder, that you have to explicitly enable. And if you had it enabled and didn’t notice it didn’t work, you’re still covered.
* I added a new, external plugin, which you would have to explicitly enable in your configuration.

Thank you!

**Comment by Profpatsch** [comment]
> All in all, this PR has no impact on existing users. Arguably, if you want to add tests, they should be added in a separate PR.

Yeah, but how should I merge it if I didn’t test it. And testing is manual work without tests.

**Comment by michalrus** [comment]
@Profpatsch, to be clear, are you proposing that I add tests to the **whole** of beets in a PR that does not impact existing users?

Because if not, this slightly off-topic discussion should really be happening elsewhere (e.g. in a PR implementing the tests).

**Comment by Profpatsch** [comment]
> proposing that I add tests to the whole of beets

err, no. But maybe you might want to add tests for your changes. :P

**Comment by michalrus** [comment]
@Profpatsch, I’d really like to see some tests, too, but I guess I’m not competent enough to decide on how they should look like for an app like beats. :-)

I suggest we check this one manually (I’ve been successfully using this setup for a few days now and it works flawlessly) and then, having well-thought-out tests for the whole app as an example, I’d be more than happy to provide tests for keyfinder and copyartifacts in the same manner.

@aszlig, @joachifm, what do you think? Is it an acceptable strategy for a newbie contributor?

**Comment by fpletz** [comment]
AFAIK we don't have a test framework for packages in nixpkgs. It seems the keyfinder plugin wasn't tested before either, so I see no reason in doubting that @michalrus are not correct. The diff also looks like it never worked before. That's why this should and can be merged.

Suggesting that @michalrus should add tests is not the right way to fix this. The beets package maintainers should.

**Comment by Profpatsch** [comment]
> Suggesting that @michalrus should add tests is not the right way to fix this. The beets package maintainers should.

Yes, of course.

> I suggest we check this one manually (I’ve been successfully using this setup for a few days now and it works flawlessly) and then, having well-thought-out tests for the whole app as an example, I’d be more than happy to provide tests for keyfinder and copyartifacts in the same manner.

I’m sorry if I sounded like we need you to provide tests (and a framework for them). I have to admit I’m not even sure how a test suite for a derivation should look.

**Comment by michalrus** [comment]
OK. :smile_cat: Thank you to both of you!

**Pull request merged**
