### PR TITLE
Backport steam chrootenv improvements

### PR DESCRIPTION
**Pull request by bjornfor**
The goal for me was actually just to backport ef5c05234569d984d24244a2d885a2744be59e26 ("fhs-env: symlink /usr/lib to libs for the main architecture"), but due to dependencies on several steam commits in master, I ended up with this PR.

I have build tested with nox-review, but not run-tested. I have no idea if these steam changes are stable enough for the release-15.09 branch. Hopefully some steam users can give some feedback.

### CODE REVIEW

**Comment by bjornfor** [comment]
CC @abbradar.

**Comment by abbradar** [comment]
Hmm, I'm afraid this would be too serious a change for 15.09 -- Steam is essentially redone anew, with its own bugs (see for example https://github.com/NixOS/nixpkgs/issues/10950).

I can backport the patch without all the Steam changes (it should be simple) but now I see another hypothetical problem of some user relying on current behavior of `lib -> lib32`. What do you think?

**Comment by bjornfor** [comment]
I'm biased of course (since I created the issue), but I think the "lib -> lib32 symlink on 64-bit arch" thing is a bug that needs to be fixed (backported).

**Comment by bjornfor** [comment]
Steam changes seen as too unstable for release-15.09 -> closing.

**Comment by abbradar** [comment]
Well, I think so too -- let's backport and see if problems come up. I'll do the job later and let you know.

**Comment by bjornfor** [comment]
@abbradar: Thanks.

**Pull request closed without merging**
