### PR TITLE
python scipy: fix tests

### LINKED ISSUE #11720: python scipy: wrong tests are run
As noted by @adnelson scipy uses the wrong tests. Instead of running its own test-suite, it runs that of numpy. This is because accidentally pkgName was set to `numpy` in 6c238d1d5f4da8b20ecaeb0cec32cbbbec5be5e5

### PR DESCRIPTION
**Pull request by FRidh**
This should fix #11720
Haven't tested yet. Will check tomorrow.

### CODE REVIEW

**Comment by FRidh** [comment]
cc @adnelson

**Comment by adnelson** [comment]
I'll take a look at this in a bit

**Comment by FRidh** [comment]
After applying the patch there are still two failing tests. One is minor, disabling that one.
The other is due to a syntax error after patching references to the python interpreter.

**Comment by FRidh** [comment]
scipy 2.7 fails with `DeprecationWarning: unorderable dtypes; returning scalar but in the future this will be an error`.
This is likely solved with numpy 1.10.2
https://github.com/scipy/scipy/issues/5575

**Comment by FRidh** [comment]
With numpy 1.10.2 and scipy 0.16.1 the following test fails with Python 2.7:
======================================================================
ERROR: test_user (test_catalog.TestCatalogPath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/dsx814jghjypygwl6vvmcz1kqvkrkzyi-python2.7-numpy-1.10.2/lib/python2.7/site-packages/numpy/testing/decorators.py", line 146, in skipper_func
    return f(*args, **kwargs)
  File "/nix/store/mx74p08j9r47gdvia0qp03aync9r4y5q-python2.7-scipy-0.16.1/lib/python2.7/site-packages/scipy/weave/tests/test_catalog.py", line 235, in test_user
    d,f = os.path.split(path)
  File "/nix/store/3q0y8dzdr5a09n4rzwxhc8y0mb29n49l-python-2.7.11/lib/python2.7/posixpath.py", line 85, in split
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'

**Comment by FRidh** [comment]
Both scipy and numpy build with the current commits.
I now need to check how it affects other packages; that might take a while.

**Comment by FRidh** [comment]
6ea543e accidentally came in, will fix that.

**Comment by FRidh** [comment]
I've checked most of the dependents, and everything builds fine. I say we merge it
@domenkozar

**Pull request merged**
