### PR TITLE
parity: 2.4.6 -> 2.4.8, parity-beta: 2.5.1 -> 2.5.3

### PR DESCRIPTION
**Pull request by xrelkd**
###### Motivation for this change
Update `parity` and `parity-beta` to the latest release.
https://github.com/paritytech/parity-ethereum/releases/tag/v2.4.8
https://github.com/paritytech/parity-ethereum/releases/tag/v2.5.3

cc @akru to review. Thank you!
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by mmahut — APPROVED** [review]
- [X] reviewed the diff and commit messages
- [X] made sure ofBorg evals
- [X] run nix-review without any failures
- [X] run and tested the binaries

**Comment by xrelkd** [comment]
Hi @marsam
I think that this PR gets stuck. 
Could you review this PR and call @GrahamcOfBorg to build `parity` and `parity-beta` ?
Thank you!!

**Comment by akru** [comment]
@GrahamcOfBorg build parity parity-beta

**Comment by marsam** [comment]
it fails, when I try to build it
parity https://gist.github.com/marsam/f978e47eb9900600daadd02b22f5b80d 
parity-beta https://gist.github.com/marsam/6f797950de52d1f1291ccc574f9eed59
@xrelkd can you build them? 
@GrahamcOfBorg build parity parity-beta

**Comment by xrelkd** [comment]
@marsam Thanks for the review.
I could build `partiy` and `parity-beta` with `nix-build -A parity` and `nix-build -A parity-beta`.
```
user@local:~ ➔ ./result/bin/parity --version
Parity Ethereum
  version Parity-Ethereum/v2.4.8-stable/x86_64-linux-gnu/rustc1.34.2
Copyright 2015-2019 Parity Technologies (UK) Ltd.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf
   Habermeier/Czaban/Greeff/Gotchac/Redmann
```

**Comment by marsam** [comment]
I trust you :), it must be something on my side

**Comment by xrelkd** [comment]
@akru @marsam @mmahut Thank you!

**Pull request merged**
