### PR TITLE
openblas: 0.2.15 -> 0.2.17

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done:
- [x] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @ttuegel

### CODE REVIEW

**Comment by adnelson** [comment]
Have we test-built some of the downstream packages? In particular (due to my experience) it's important that numpy/scipy/pandas build with this.

**Comment by grahamc** [comment]
Rebuilding downstream packages has failed for me locally, I'm investigating.

**Comment by grahamc** [comment]
Failure when building cudatoolkit, due to gcc:

```
gcc    -O3 -fexceptions -fPIC -DNPARTITION -DLONGBLAS=int64_t -DNPARTITION -DDLONG -c -I../../AMD/Include -I../../AMD/Source -I../../COLAMD/Include -I../../CCOLAMD/Include -I../../CAMD/Include -I../Include -I../../SuiteSparse_config ../Modify/cholmod_rowdel.c -o cholmod_l_rowdel.o
NVCC src/caffe/util/im2col.cu
In file included from /nix/store/5cvqgnhnj2mpw9jq2cyk5vj1jrcwmly8-cudatoolkit-7.0.28/include/cuda_runtime.h:62:0,
                 from <command-line>:0:
/nix/store/5cvqgnhnj2mpw9jq2cyk5vj1jrcwmly8-cudatoolkit-7.0.28/include/host_config.h:105:2: error: #error -- unsupported GNU version! gcc 4.10 and up are not supported!
 #error -- unsupported GNU version! gcc 4.10 and up are not supported!
```

**Comment by FRidh** [comment]
Successfully built numpy, scipy and scikitlearn against this version.

**Comment by FRidh** [comment]
@ttuegel @domenkozar @bjornfor I might want to get this into 16.03. In 16.03 2.15 is the default version but 2.14 is used for numpy because of segmentation faults with 2.15. Unfortunately, 2.14 doesn't build as easily on newer CPU's (see #https://github.com/NixOS/nixpkgs/issues/13163). (And I've considered reverting to ATLAS but that takes ages to build so isn't an option in my opinion.)

**Comment by domenkozar** [comment]
We have to also test: R, julia and octave.

**Comment by FRidh** [comment]
Successfully built the above 3.

**Comment by FRidh** [comment]
i686 `julia-git` does seem to fail now

**Pull request merged**
