### PR TITLE
patchelf: 0.10-pre-20180108 -> 0.10-pre-20180509, minor touchup

### PR DESCRIPTION
**Pull request by dtzWill**
Useful update-- adds support for accepting multiple files as arguments
and fixes handling of large executables (>2Gb).

While touching this, modify version to include more info.

Preserving version format previously used, although not usual style.

Important updates/fixes for patchelf!

Might fix errors seen w/chrome (chromium?) but haven't checked.

Been using this more or less since the day these commits were merged
(FWIW).

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
Let's build the real thing :smile:
@GrahamcOfBorg build patchelfUnstable

**Comment by xeji** [comment]
Looks like `patchelfUnstable` never built on darwin, restrict to linux perhaps?

https://hydra.nixos.org/job/nixpkgs/trunk/patchelfUnstable.x86_64-darwin/all

**Comment by dtzWill** [comment]
If "stable" patchelf supports it, that seems like a regression worth flagging as a failure but I suppose it depends on the goals/interests of the patchelf developers (teehee whoever they are :P).  Good point though, I suppose without input that's probably the best we can do.

**Comment by dezgeg** [comment]
Presumably `doCheck = false;` on Darwin will fix it, it's just compiling the test code which can't work given Darwin doesn't use ELF.

**Comment by Ekleog** [comment]
(triage) This… looks ready?

**Comment by dtzWill** [comment]
> `virtualbox` uses `patchelfUnstable`. When I build it locally with this update, the build succeeds but there's a weird error message:

It **looks** like it uses patchelfUnstable but it doesn't, haha.  Things look better after #47444 either with or without updating patchelfUnstable.  LMK if you try it and if that's your findings as well.

**Comment by xeji** [comment]
Good catch! Indeed `virtualbox` uses regular `patchelf` because stdenv puts it in PATH before `patchelfUnstable`  :smile:  (so the `patchelfUnstable` dependency is quite useless)

So let's merge this now.

**Pull request merged**
