### PR TITLE
scs: Fix darwin build

### PR DESCRIPTION
**Pull request by knedlsepp**
###### Motivation for this change
This fixes the darwin build of scs.
/cc ZHF #45961

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by LnL7** [comment]
I don't see any dylibs/so's in the output, while the linux build does include dynamic libraries.

**Comment by knedlsepp** [comment]
Hm. That's odd. I'll look into it.

**Comment by knedlsepp** [comment]
@LnL7 Should be fixed now.

**Comment by LnL7** [comment]
Looks like we'll also have to fixup the install_name.

**Comment by knedlsepp** [comment]
Oh, I've never dealt with that before. Could you hint me to what it should look like and how you can tell that it's not correct currently?

**Comment by knedlsepp** [comment]
@LnL7: Thanks for the pointer. Had a look at the options:
- `LDFLAGS=-Wl,-install_name...` during `buildPhase`
- `install_name_tool -id` during `fixupPhase`
- `fixDarwinDylibNames` in `nativeBuildInputs`

It went for the most convenient, namely `fixDarwinDylibNames`.

**Review by LnL7 — APPROVED** [review]
Thanks!

**Comment by LnL7** [comment]
backported in 84361ab3e19cf23b9d1b13324ff2c1f9f79017ef

**Pull request merged**
