### PR TITLE
lib: Add composeExtensions for composing extension functions

### PR DESCRIPTION
**Pull request by shlevy**

### CODE REVIEW

**Comment by shlevy** [comment]
I'm pretty sure this is right and my tests pass, but just wanted a second opinion.

**Comment by shlevy** [comment]
Nope, it's wrong, fix incoming

**Comment by shlevy** [comment]
OK, should be working now

**Comment by Profpatsch** [comment]
I think something like that should be reviewed before being merged. cc @peti @nbp

**Review by nbp — COMMENTED** [review]
These modification sounds correct.

I also agree with @Profpatsch that we should be adding tests to our lib functions now (see `lib/tests` directory).

**Comment by shlevy** [comment]
OK, I'll add some tests

**Comment by Profpatsch** [comment]
> I also agree with @Profpatsch that we should be adding tests to our lib functions now (see lib/tests directory).

For function tests, `lib/tests.nix` is the correct file. The `lib/tests/` folder is only set up for module tests.

**Comment by Ericson2314** [comment]
Hah I just recently wrote this not knowing it was added. It took me a couple attempts, but then I fixed it by proving the monoid https://gist.github.com/Ericson2314/ab120ccce04ac41b2ec2bec11fda3879 . I'm not sure which of machine-checked tests or hand-written proof is better for inclusion in Nixpkgs, but rest assured this PR is correct :).

**Comment by shlevy** [comment]
@Ericson2314 There are tests already, but if you want to formalize nix in coq and check in a machine-checked proof I'm :100:  :tongue:

**Comment by vcunat** [comment]
Maybe it would be more practical to compose lists of extensions directly.  We already use
```nix
let # ...
    toFix = lib.foldl' (lib.flip lib.extends) (self: {}) someListOfExtensions;
in lib.fix toFix
```

**Comment by shlevy** [comment]
@vcunat More practical in what sense? We've been using this as-is for a while now.

**Comment by vcunat** [comment]
Just a random thought.  It surely depends on particular use case (and the number of extensions you usually combine).

**Comment by Ericson2314** [comment]
@vcunat on the contrary I rather do a fold1 with `composeExtensions` and fix with a `fixExtension = f: fix (f {})`.

**Comment by vcunat** [comment]
Yes, using folds explicitly would be a more idiomatic way, at least if we had a `forldr1` or `foldl1`, but it's easy enough to write those.

**Comment by Ericson2314** [comment]
Well, while it's extra needless work, the monoid identity can always provide the base case for a normal fold.

**Pull request merged**
