### PR TITLE
nix-prefetch-github: 2.3 -> 2.3.1

### PR DESCRIPTION
**Pull request by seppeljordan**
###### Motivation for this change
There was new version released of this program upstream.  All the changes upstream are backwards compatible.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by FRidh** [comment]
Opened it twice. Closing this in favor of https://github.com/NixOS/nixpkgs/pull/67943.

**Comment by FRidh** [comment]
Ah, nevermind, this is the release branch.

**Comment by FRidh** [comment]
I think it's better to `cherry-pick -xe` after the other one is submitted.

**Comment by seppeljordan** [comment]
Hi, will do.  Forgot about the cherry-picking rule.

**Comment by seppeljordan** [comment]
Hi, I backported the changes from master with `git cherry-pick -xe ...`.  Also tested everything again as described in the OP

**Comment by seppeljordan** [comment]
Okay, I don't want to see this anymore in my PR overview, closing this.

**Pull request closed without merging**
