### PR TITLE
gvisor: 2019-11-14 -> 2020-03-27

### PR DESCRIPTION
**Pull request by andrew-d**
###### Motivation for this change
Keep up-to-date with upstream.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by andrew-d** [comment]
Looks like `rules_python` generates non-reproducible output; I submitted a PR upstream, and after that's been fixed, will bump the dependency in `gvisor` as well.

**Comment by FRidh** [comment]
Merge conflict

**Comment by andrew-d** [comment]
@GrahamcOfBorg test gvisor

**Comment by andrew-d** [comment]
Ugh, wheels are `.zip` files and dependent on filesystem traversal :expressionless:  Hopefully this fixes it:

@GrahamcOfBorg test gvisor

**Comment by andrew-d** [comment]
@FRidh - Okay, tests passing and merge conflict solved! :tada:

**Pull request closed without merging**
