### PR TITLE
terraform_0_11: 0.11.14 -> 0.11.15

### PR DESCRIPTION
**Pull request by polynomial**
###### Motivation for this change
https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512

HashiCorp was impacted by a security incident with a third party (Codecov) that led to potential disclosure of sensitive information. As a result, the GPG key used for release signing and verification has been rotated. Customers who verify HashiCorp release signatures may need to update their process to use the new key.

###### Things done
This is a minor version increment, but very improtant for security!

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by polynomial** [comment]
I'm unsure of the security practice here. We use 21.09 now, so wanted to update it for others using that channel. Should I also open a PR against main? The problem there is I don't have the facilities to test the other TF versions, they all need to be bumped a minor version # due to the key leak above...

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 126909` at a4bfb6ab run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>terraform_0_11</li>
  </ul>
</details>
<details>
  <summary>4 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Consider adding a comment explaining the purpose of this patch on the line preceeding.
Near pkgs/applications/networking/cluster/terraform/default.nix:126:9:
```
    |
126 |         (fetchpatch {
    |         ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Consider adding a comment explaining the purpose of this patch on the line preceeding.
Near pkgs/applications/networking/cluster/terraform/default.nix:125:9:
```
    |
125 |         ./provider-path.patch
    |         ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Consider adding a comment explaining the purpose of this patch on the line preceeding.
Near pkgs/applications/networking/cluster/terraform/default.nix:137:17:
```
    |
137 |     patches = [ ./provider-path.patch ];
    |                 ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Consider adding a comment explaining the purpose of this patch on the line preceeding.
Near pkgs/applications/networking/cluster/terraform/default.nix:115:17:
```
    |
115 |     patches = [ ./provider-path.patch ];
    |                 ^
```
</li>
  </ul>
</details>

**Comment by zimbatm** [comment]
thanks, that's fine. Usually, we target master and then backport it to the release channel.

**Comment by zimbatm** [comment]
Did a bit of cleanup, https://github.com/NixOS/nixpkgs/pull/126919 will drop that version.

**Pull request merged**
