### PR TITLE
thunderbird-bin: 45.1.1 -> 45.2.0

### PR DESCRIPTION
**Pull request by taku0**
###### Motivation for this change

Bug fixes.

https://www.mozilla.org/en-US/thunderbird/45.2.0/releasenotes/
###### Things done
- [X] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [X] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bjornfor** [comment]
May I suggest using sha256 until the next NixOS release comes out? The thing is that no commit that uses sha512 can be backported to stable...

**Comment by taku0** [comment]
@bjornfor Doesn't 16.03 support SHA-512? `firefox-bin-47.0` is backported to 16.03 and I can install it.
https://github.com/NixOS/nixpkgs/tree/release-16.03/pkgs/applications/networking/browsers/firefox-bin

**Comment by bjornfor** [comment]
@taku0: Hm, you're right. But what causes this eval error then? https://github.com/NixOS/nixpkgs/commit/094c6ceff0a9a0ac2bdf2c4e16a14fc58ac7ec3f#commitcomment-18174818

**Comment by bjornfor** [comment]
@taku0: Ah, it's not sha256 vs sha512 error, but just a wrong attribute reference in thunderbird-bin/default. I guess someone skipped an important commit when backporting thunderbird to stable...

**Comment by bjornfor** [comment]
@taku0: Will you backport the missing commit(s)?

**Comment by fpletz** [comment]
Sorry, my fault. I will fix this.

**Comment by fpletz** [comment]
Fixed in 89d1d487b5bbb457e5a21a506801cd095257d0d7.

**Comment by taku0** [comment]
I installed `firefox-bin` from 16.03 but It seems that I didn't installed `thunderbird-bin`.

**Comment by bjornfor** [comment]
@fpletz, @taku0: Thanks, now release-16.03 works again.

**Pull request merged**
