### PR TITLE
chromium: speed up build and enable system ffmpeg, libjpeg, and zlib

### PR DESCRIPTION
**Pull request by TredwellGit**
Only tested and built `chromium` not `chromiumBeta` and `chromiumDev`.
- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TredwellGit** [comment]
My plan in coming pull requests is to get Chromium to:
- Use only system libraries.
- [Build with LLD](https://lld.llvm.org/#performance). (Note the Chromium performance comparison)
- [Enable control flow integrity](https://www.chromium.org/developers/testing/control-flow-integrity).

**Comment by TredwellGit** [comment]
Getting https://github.com/NixOS/nixpkgs/pull/99647 merged would help with my first goal.

**Comment by TredwellGit** [comment]
@primeos requesting review since ofborg did not.

**Comment by primeos** [comment]
Sorry for the delay, I lost track of this. Let's give this a try :)

- https://github.com/NixOS/nixpkgs/pull/100110/commits/a7cbf67a24e7079bb889f0c58314ff00e1da8397
  - That's nice, thanks :) I guess this means that Chromium won't print a stack trace anymore when it crashes, but I don't think we needed those so far.
  - One request for the next time: Could you try wrapping the body of your commit messages at 72 characters? See https://chris.beams.io/posts/git-commit/#seven-rules. The commit message is nice though :)
- https://github.com/NixOS/nixpkgs/pull/100110/commits/eb74717477bd782d202495e05afcbeefc4c26bb3
  - Reusing system libraries is obviously nice but I'm not sure yet if we can keep that commit. If this starts causing compatibility issues we might have to revert it in the future. It might also be problematic when testing the builds of the beta and dev channels.

**Comment by TredwellGit** [comment]
@primeos
Is wrapping lines a rule for Nixpkgs? I dislike wrapping lines since every terminal, visual text editor, and web browser that I am aware of will automatically wrap the line at the end of the window. See: https://lkml.org/lkml/2020/5/29/1038

I was planning to submit another pull request that additionally makes Chromium build with the system fontconfig, freetype, harfbuzz, icu, libdrm, libevent, libvpx, libxml, openh264, and re2. I don't expect there to be any issue right now since nixos-unstable has the latest version of all of those but [harfbuzz](https://github.com/NixOS/nixpkgs/pull/100198), [libvpx](https://github.com/NixOS/nixpkgs/pull/100210), and  which someone just needs to merge. Other distros are able to handle using the system libraries using the latest versions; my main concern is with backporting the libraries, but if that is not possible they can just be selectively commented out.

**Comment by primeos** [comment]
> Is wrapping lines a rule for Nixpkgs?

No, not that I know of, but most/(almost all?) people usually do it anyway (for code and especially for commit messages). And if you look at the commit messages in Nixpkgs or the Linux kernel most people wrap their lines at 72 or 80 characters (with exceptions of course, e.g. for readability).

> Other distros are able to handle using the system libraries using the latest versions;

Yeah, though I'd assume that they also have more or dedicated maintainers (see #78450).

> my main concern is with backporting the libraries, but if that is not possible they can just be selectively commented out.

Oh, I forgot to consider our stable channel. I guess selectively commenting them out is either up to you or I have to do it more aggressively to avoid long iteration cycles.

**Pull request merged**
