### PR TITLE
youtube-music: 3.6.2 -> 3.7.1

### PR DESCRIPTION
**Pull request by SuperSandro2000**
Changelog: https://github.com/th-ch/youtube-music/releases/tag/v3.7.0
Changelog: https://github.com/th-ch/youtube-music/releases/tag/v3.7.1

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by h-banii** [comment]
version 3.7.0 changed the WM_CLASS (app ID on wayland)  to `com.github.th_ch.youtube_music`
PR: https://github.com/th-ch/youtube-music/pull/2758
Issue: https://github.com/th-ch/youtube-music/issues/2687

We should update the `StartupWMClass` in the desktop entry to match that
```diff
- startupWMClass = "YouTube Music"; 
+ startupWMClass = "com.github.th_ch.youtube_music"; 
```

Just like the package in the AUR: https://aur.archlinux.org/packages/youtube-music

<hr>

I don't know if other changes are needed to make it work on Plasma/GNOME, like changing the .desktop and/or icon names. See this: https://github.com/th-ch/youtube-music/issues/2806

**Comment by SuperSandro2000** [comment]
@h-banii could you create a PR for that, please?

**Comment by h-banii** [comment]
@SuperSandro2000 , sure I'll open a PR as soon as I get back home

**Comment by h-banii** [comment]
follow up PR to update the startupWMClass: #371682

**Pull request merged**
