### PR TITLE
cvc5: init at 1.0.0 & symfpu: init at 8fbe139b

### PR DESCRIPTION
**Pull request by shadaj**
###### Description of changes

Adds the CVC5 package (an SMT solver), along with its dependency symfpu (which provides symbolic floating point APIs).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dtzWill** [comment]
Please specify gpl3Only or gpl3Plus, if you would :).

symfpu:
Also, convention for packages built from an unofficial or untagged revision (aka no version number), is to set version to "unstable-2022-01-22" or so, where that's the commit date in year-month-day form.

The first "mkdir -p" can be dropped, the second one makes it redundant (that's what the -p flag is for).

Installing everything to a subdir of $out ($out/symfpu) is unusual but without inspection I trust that makes sense for some reason? Not a big deal I don't think, but don't think I've seen that before.

Cvc5:
Please drop the  "with pkgs;", I am on my phone so haven't checked but not sure where "pkgs" even comes from.  Does this evaluate as-is?

Oh, no, probably not.  In all-packages  cvc5 is defined as a callPackage to the cvc4 path (the first line this PR adds to that file).  Change that to cvc5 and let's see where things stand :).

Thanks for packaging this!

Btw sorry for not doing this as a proper review attached to changes, my client is erroring when I try.  If you have questions or if anything's unclear please let me know!

**Comment by risicle** [comment]
Ideally these should be two separate commits, `symfpu` first and `cvc5` after.

**Comment by risicle** [comment]
Oh :(

```
builder for '/nix/store/8c4nzpga5xz8aik9av3rhdaiwp0l24g4-source.drv' failed with exit code 1; last 8 log lines:
  
  trying https://github.com/martin-cs/symfpu/archive/unstable-2019-05-17.tar.gz
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
  100   137  100   137    0     0   1797      0 --:--:-- --:--:-- --:--:--  1802
    0    14    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  curl: (22) The requested URL returned error: 404
  error: cannot download source from any mirror
```

**Comment by shadaj** [comment]
Ah oops, fixed. Somehow `nixpkgs-review rev HEAD` seemed to build things just fine, not sure what's going on there.

**Comment by risicle** [comment]
On nixos x86_64:

```
builder for '/nix/store/vvwb79x55a4vpn8ri40wpr8fv22bhssq-cvc5-0.0.7.drv' failed with exit code 2; last 10 log lines:
  make[2]: *** [src/parser/CMakeFiles/cvc5parser-objs.dir/build.make:108: src/parser/CMakeFiles/cvc5parser-objs.dir/antlr_input.cpp.o] Error 1
  make[2]: *** Waiting for unfinished jobs....
  In file included from /build/source/src/parser/antlr_input_imports.cpp:59:
  /build/source/src/./parser/parser.h:28:10: fatal error: expr/kind.h: No such file or directory
     28 | #include "expr/kind.h"
        |          ^~~~~~~~~~~~~
  compilation terminated.
  make[2]: *** [src/parser/CMakeFiles/cvc5parser-objs.dir/build.make:122: src/parser/CMakeFiles/cvc5parser-objs.dir/antlr_input_imports.cpp.o] Error 1
  make[1]: *** [CMakeFiles/Makefile2:683: src/parser/CMakeFiles/cvc5parser-objs.dir/all] Error 2
  make: *** [Makefile:146: all] Error 2
```

Both build happily for me on macos 10.15 though.

**Comment by risicle** [comment]
p.s. did you have a go at enabling the tests for `cvc5`? A quick try suggests a small amount of `LD_LIBRARY_PATH`/`DYLD_LIBRARY_PATH` manipulation may be needed, but might not be too difficult.

**Comment by shadaj** [comment]
@risicle interesting... I've actually been using this derivation on nixos x86_64 for a while; will investigate in addition to trying to set up tests

**Comment by risicle** [comment]
@ofborg build cvc5

I'm consistently getting the error I mentioned yesterday

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 166740` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>cvc5</li>
    <li>symfpu</li>
  </ul>
</details>

**Comment by shadaj** [comment]
Updated CVC5 to the 1.0.0 release!

**Review by risicle — APPROVED** [review]
WFM now

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 166740` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>cvc5</li>
    <li>symfpu</li>
  </ul>
</details>

**Review by thiagokokada — APPROVED** [review]

**Pull request merged**
