### PR TITLE
nixos: zsh: add more helpful documentation into generated files

### PR DESCRIPTION
**Pull request by oxij**
# What? Why?

See discussion in #38535 after https://github.com/NixOS/nixpkgs/pull/38535#issuecomment-521046953.

# `git log`

- nixos: zsh: move NixOS-specific variables from /etc/zshrc to /etc/zshenv

  We want these to be set even when /etc/zshrc loading is disabled.

- nixos: zsh: reorder /etc/zshrc a little bit, add more helpful documentation

# `nix-instantiate` environment

- Host OS: Linux 4.9, SLNOS 19.09
- Nix: nix-env (Nix) 2.2.2
- Multi-user: yes
- Sandbox: yes
- NIXPKGS_CONFIG:

```nix
{
  checkMeta = true;
  doCheckByDefault = true;
}
```

# `nix-env -qaP` diffs

- On x86_64-linux: noop
- On aarch64-linux: noop
- On x86_64-darwin: noop

### CODE REVIEW

**Review by ck3d — APPROVED** [review]
Thanks for your PR!

**Comment by oxij** [comment]
@GrahamcOfBorg eval

**Comment by oxij** [comment]
@7c6f434c could you get this in, please?

**Comment by oxij** [comment]
Thanks!

**Pull request merged**
