### PR TITLE
Use more Vulnix dependencies from pythonPackages

### PR DESCRIPTION
**Pull request by adisbladis**
###### Motivation for this change
Moving a lot of Vulnix dependencies to depend on pythonPackages instead of it's own pinned ones.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
What is the reason for this? You do realize that `pythonPackages` may update to newer, and again incompatible, versions?

**Comment by Mic92** [comment]
The reason that was not done in the first place, was just laziness. The package duplication also have problems. For instance if we apply fixes to `pythonPackages`, we also need to copy them to vulnix's packages too.

**Comment by adisbladis** [comment]
@FRidh Something changed and some build-time only deps (manuel, transaction) for BTrees and zconfig were suddenly not pulled in.

I figured it was better to fix these issues in pythonPackages and then use these in the vulnix package so any future fixes only require changes in one spot.

**Comment by FRidh** [comment]
This is in staging now.

**Pull request closed without merging**
