### PR TITLE
udisks2: 2.1.6 → 2.7.6

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
Closes: https://github.com/NixOS/nixpkgs/issues/34999

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jtojnar** [comment]
@flokli Your commit worked great, except that you forgot to add `dosfstools` to the `PATH`. I added it and was able to successfully format a flash drive. You should be able to cherry-pick `jtojnar/udisks2-2.7.6` onto `flokli/udisks^`.

**Comment by flokli** [comment]
Oh wow, the missing `dosfstools` totally explains why I was still having problems with `mkfs.vfat`, thanks for finding this :-)

I quickly skimmed over `libblockdev`, filesystem-specific tools are configured in `src/plugins/fs/` (we should have all those covered, and all `g_spawn_*` calls have `G_SPAWN_SEARCH_PATH` set, so calling udisks with the currect assembled `PATH` should be enough).

Whats still missing is other parts in which `libblockdev` related to the block devices itself:

 - `mdadm`
 - `lvm2` (`dmsetup`, `vgcreate` and friends) 
 - `bcache-tools` (`make-bcache`)
 - `multipath-tools`

Those could simply added to the path. I'm still not sure on whether to prefer patching via `@path@` or the use of `wrapProgram`, but thats personal preference ;-)

There's also src/plugins/s390.c with hardcoded paths (filed upstream PR at https://github.com/storaged-project/libblockdev/pull/326). 
We currently lack the userspace tools `dasdfmt`,`chccwdev` (https://github.com/ibm-s390-tools/s390-tools), `dasd_cio_free`, `zfcp_cio_free` (might be symlinks to [device_cio_free](https://github.com/gooselinux/s390utils/blob/139d53d33f6b48be236be7ecd52062d5725e9445/device_cio_free), so I'm unsure about packaging those. Any z Systems NixOS users around? :-D

**Comment by jtojnar** [comment]
> I'm still not sure on whether to prefer patching via `@path@` or the use of `wrapProgram`, but thats personal preference ;-)

I have had my own share of problems with wrappers so my perspective is little skewed. I agree that it is cleaner than the `force-path.patch` hack.

The optimal solution would be changing each individual executable in the source code to absolute path but of course that is laborious, and unless udisk calls the executables repeatedly, getting rid of `PATH` look-up overhead is not worth the trouble. However, for the `libblockdev`, which does not have a daemon, we will have to do that anyway, if we want to allow usage outside of `udisks`.

Maybe we could make the paths `./configure`able and try to upstream it?

**Comment by jfrankenau** [comment]
@jtojnar, while you are at it, could you include storaged-project/udisks@f639f67aa3f44a4e7e182cff7e6fc7ba5872c94a and storaged-project/udisks@293aa9b2228a09af0ee92b99401bd92682f5f2b3 in the systemd service specification of the matching udisks2 module? Thank you.

**Comment by jtojnar** [comment]
I will not have time to finish this anytime soon. Anyone want to take this over?

**Comment by dtzWill** [comment]
This works (on top of recent staging changes) w/musl, with the following change:

https://github.com/dtzWill/nixpkgs/commit/3fd44d9caa635cf80e872a810653cebf7fcac096

Which can probably be reduced to just building `libblockdev` with `--without-dm` (and drop `dmraid` dep) which upstream says is okay/reasonable if we're only using libblockdev as a dependency of udisks2.
(See commit message for links to this)

**Comment by flokli** [comment]
> @jtojnar, while you are at it, could you include storaged-project/udisks@f639f67 and storaged-project/udisks@293aa9b in the systemd service specification of the matching udisks2 module? Thank you.

That's included in `udisks-2.7.6`, which is in #41723.

**Pull request closed without merging**
