### PR TITLE
ocamlPackages.ocamlify: fix build with OCaml 4.06

### PR DESCRIPTION
**Pull request by vbgl**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build ocamlPackages.ocamlify

**Comment by Mic92** [comment]
is a backport required here?

**Comment by vbgl** [comment]
What are the rule for back-porting? There is no security issue there…

**Comment by Mic92** [comment]
@vbgl we backport patch releases, bug fixes and security updates.
Optionally also new packages, that don't break anything.
If the change here also fixes the build on stable, it should be back ported.

**Comment by Mic92** [comment]
Preferable this should be decided by the maintainer making the change, as they have the best idea, what the consequences of the change are.

**Comment by vbgl** [comment]
Thanks for the clarification. Then it might be back-ported since 1. it does not break anything (AFAICT); and 2. it may benefit users using OCaml 4.06 on released channels (are there any such users? I don’t know).

**Pull request merged**
