### PR TITLE
gmic-qt: 2.7.1 → 3.0.0

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
- https://gmic.eu/gmic300/
- https://discuss.pixls.us/t/release-of-gmic-3-0/17226#from-299-to-300-3

Also add an update script.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
The mismatch only seems to happen on Darwin. `nix-build -A gmic-qt.gmic-community --check` passes on NixOS. Maybe case-insensitivity issue? cc @NixOS/darwin-maintainers

**Comment by prusnak** [comment]
> Maybe case-insensitivity issue?

It's weird it only fails on x86_64-darwin, but works fine on aarch64-darwin. Are aarch64-darwin hosts running on a case-sensitive filesystem?

**Comment by bobby285271** [comment]
> It's weird it only fails on x86_64-darwin, but works fine on aarch64-darwin.

Actually gmic-qt does not build on aarch64-darwin because qtbase 5.12 is marked as broken on that platform.

**Comment by prusnak** [comment]
> Actually gmic-qt does not build on aarch64-darwin because qtbase 5.12 is marked as broken on that platform.

Ah, right. I misread the CI report.

**Comment by uri-canva** [comment]
Yeah it's probably because there's both an `Images` and an `images` directories in https://github.com/dtschump/gmic-community/tree/9a3694a9a23d4986ed2be20e998d62faf48bb70f/tutorial. Assuming the tutorial files aren't needed, you can remove them with an `extraPostFetch`.

**Comment by prusnak** [comment]
> Yeah it's probably because there's both an `Images` and an `images` directories

Reported upstream: https://github.com/dtschump/gmic-community/issues/255

**Comment by uri-canva** [comment]
Fixed upstream, not part of a release yet: https://github.com/dtschump/gmic-community/commit/df23b08bc52767762f0e38d040cd8ffeea4b865e

**Pull request merged**
