### PR TITLE
libcap_progs: fix bash path

### PR DESCRIPTION
**Pull request by j-keck**
- in progs/capsh.c is the bash path hardcoded to '/bin/bash'
- this fix set's the path to '/var/run/current-system/sw/bin/bash'

### CODE REVIEW

**Comment by lethalman** [comment]
`/var/run/current-system` should never appear in packages. The correct patch is to search bash in PATH.

**Comment by j-keck** [comment]
sorry,
i have a new version which uses 'type -tp bash).

should i delete' the wrong commit by rebase? or open a new pull request? - what is the preferred way?

**Comment by lethalman** [comment]
I think it suffices to use `bash` instead of `/bin/bash` and use `execvpe` instead of `execve`.

**Comment by peti** [comment]
The full path to `bash` is also available in the `$SHELL` variable.

**Comment by j-keck** [comment]
the file content after the patchPhase:
```
  * raise and lower both the bset and pI capabilities before invoking
- * /bin/bash (hardcoded right now).
+ * bash (hardcoded right now).
  *
@@ -558,6 +558,6 @@ int main(int argc, char *argv[], char *envp[])
        } else if ((!strcmp("--", argv[i])) || (!strcmp("==", argv[i]))) {
-           argv[i] = strdup(argv[i][0] == '-' ? "/bin/bash" : argv[0]);
+           argv[i] = strdup(argv[i][0] == '-' ? "bash" : argv[0]);
            argv[argc] = NULL;
-           execve(argv[i], argv+i, envp);
-           fprintf(stderr, "execve /bin/bash failed!\n");
+           execvpe(argv[i], argv+i, envp);
+           fprintf(stderr, "execvpe bash failed!\n");
            exit(1);
@@ -583,3 +583,3 @@ int main(int argc, char *argv[], char *envp[])
                   "  ==             re-exec(capsh) with args as for --\n"
-                  "  --             remaing arguments are for /bin/bash\n"
+                  "  --             remaing arguments are for bash\n"
```

**Comment by lethalman** [comment]
@peti not that $SHELL is always bash.

**Comment by peti** [comment]
@lethalman,it is in `stdenv.mkDerivation`.

**Comment by peti** [comment]
Personally, I thought the second version of this patch -- the one that replaced `/bin/bash` with the proper full path to the `bash` binary -- was nicer than this one, which relies on `$PATH`, for the following reasons:

1. The full `/nix/store/.../bin/bash` path would be recognized as a dependency, i.e. Nix would know that this package depends on `bash`. Now it doesn't know that.
2. It's not clear that users will have `bash` in `$PATH`. On NixOS, they almost certainly have, but uses running Nix on some other host system may not have a `bash` binary. The original patch would have worked nonetheless, but this patch won't.

It's no big issue, though. Just my 2 cents.

**Comment by lethalman** [comment]
@peti sorry thought you wanted to use $SHELL at runtime not during substitution at compile time. I agree that it could have been a runtime dep, not sure what were the exact implications. In particular, maybe capsh needs bash with readline support.

**Pull request merged**
