### PR TITLE
[20.09] virtualbox: 6.1.14 -> 6.1.16

### PR DESCRIPTION
**Pull request by greizgh**
###### Motivation for this change

Backport #101493

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by thiagokokada — APPROVED** [review]
Didn't test but code-wise LGTM.

**Review by robertodr — APPROVED** [review]

**Review by blitz — APPROVED** [review]

**Review by unode — APPROVED** [review]

**Comment by jecaro** [comment]
I'm really in need of this to be merged. In the meantime a workaround would be greatly appreciated.

**Comment by blitz** [comment]
@svanderburg @cdepillabout Can you take a look at this?

**Comment by cdepillabout** [comment]
In general we don't do version bumps on the release branches, but it sounds like this might be necessary for people running 5.9 kernels.

Let's ping the release managers and see if they have any opinion on this (@worldofpeace and @jonringer).

**Review by jonringer — APPROVED** [review]
LGTM

According to https://www.virtualbox.org/wiki/Changelog it's a maintenance release, so there shouldn't be any regressions.

**Comment by jonringer** [comment]
> In general we don't do version bumps on the release branches,

We try to avoid breaking version bumps, but bug fixes and security updates are still welcome.

**Comment by jonringer** [comment]
@GrahamcOfBorg test virtualbox

**Comment by jonringer** [comment]
```
https://github.com/NixOS/nixpkgs/pull/107421

16 packages marked as broken and skipped:
linuxPackages_5_9.virtualbox linuxPackages_5_9.virtualboxGuestAdditions linuxPackages_hardkernel_4_14.virtualbox linuxPackages_hardkernel_4_14.virtualboxGuestAdditions linuxPackages_hardkernel_latest.virtualbox linuxPackages_hardkernel_latest.virtualboxGuestAdditions linuxPackages_latest-libre.virtualbox linuxPackages_latest-libre.virtualboxGuestAdditions linuxPackages_latest.virtualbox linuxPackages_latest.virtualboxGuestAdditions linuxPackages_latest_hardened.virtualbox linuxPackages_latest_hardened.virtualboxGuestAdditions linuxPackages_latest_xen_dom0.virtualbox linuxPackages_latest_xen_dom0.virtualboxGuestAdditions linuxPackages_latest_xen_dom0_hardened.virtualbox linuxPackages_latest_xen_dom0_hardened.virtualboxGuestAdditions

29 packages built:
linuxPackages-libre.virtualbox linuxPackages-libre.virtualboxGuestAdditions linuxPackages.virtualbox linuxPackages.virtualboxGuestAdditions linuxPackages_4_14.virtualbox linuxPackages_4_14.virtualboxGuestAdditions linuxPackages_4_19.virtualbox linuxPackages_4_19.virtualboxGuestAdditions linuxPackages_4_4.virtualbox linuxPackages_4_4.virtualboxGuestAdditions linuxPackages_4_9.virtualbox linuxPackages_4_9.virtualboxGuestAdditions linuxPackages_5_8.virtualbox linuxPackages_5_8.virtualboxGuestAdditions linuxPackages_hardened.virtualbox linuxPackages_hardened.virtualboxGuestAdditions linuxPackages_testing_bcachefs.virtualbox linuxPackages_testing_bcachefs.virtualboxGuestAdditions linuxPackages_xen_dom0.virtualbox linuxPackages_xen_dom0.virtualboxGuestAdditions linuxPackages_xen_dom0_hardened.virtualbox linuxPackages_xen_dom0_hardened.virtualboxGuestAdditions linuxPackages_zen.virtualbox linuxPackages_zen.virtualboxGuestAdditions virtualbox virtualboxExtpack virtualboxHardened virtualboxHeadless virtualboxWithExtpack
```

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 107421 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>16 packages marked as broken and skipped:</summary>  <ul>    <li>linuxPackages_5_9.virtualbox</li>    <li>linuxPackages_5_9.virtualboxGuestAdditions</li>    <li>linuxPackages_hardkernel_4_14.virtualbox</li>    <li>linuxPackages_hardkernel_4_14.virtualboxGuestAdditions</li>    <li>linuxPackages_hardkernel_latest.virtualbox</li>    <li>linuxPackages_hardkernel_latest.virtualboxGuestAdditions</li>    <li>linuxPackages_latest-libre.virtualbox</li>    <li>linuxPackages_latest-libre.virtualboxGuestAdditions</li>    <li>linuxPackages_latest.virtualbox</li>    <li>linuxPackages_latest.virtualboxGuestAdditions</li>    <li>linuxPackages_latest_hardened.virtualbox</li>    <li>linuxPackages_latest_hardened.virtualboxGuestAdditions</li>    <li>linuxPackages_latest_xen_dom0.virtualbox</li>    <li>linuxPackages_latest_xen_dom0.virtualboxGuestAdditions</li>    <li>linuxPackages_latest_xen_dom0_hardened.virtualbox</li>    <li>linuxPackages_latest_xen_dom0_hardened.virtualboxGuestAdditions</li>  </ul></details><details>  <summary>29 packages built:</summary>  <ul>    <li>linuxPackages-libre.virtualbox</li>    <li>linuxPackages-libre.virtualboxGuestAdditions</li>    <li>linuxPackages.virtualbox (linuxPackages_5_4.virtualbox)</li>    <li>linuxPackages.virtualboxGuestAdditions (linuxPackages_5_4.virtualboxGuestAdditions)</li>    <li>linuxPackages_4_14.virtualbox</li>    <li>linuxPackages_4_14.virtualboxGuestAdditions</li>    <li>linuxPackages_4_19.virtualbox</li>    <li>linuxPackages_4_19.virtualboxGuestAdditions</li>    <li>linuxPackages_4_4.virtualbox</li>    <li>linuxPackages_4_4.virtualboxGuestAdditions</li>    <li>linuxPackages_4_9.virtualbox</li>    <li>linuxPackages_4_9.virtualboxGuestAdditions</li>    <li>linuxPackages_5_8.virtualbox</li>    <li>linuxPackages_5_8.virtualboxGuestAdditions</li>    <li>linuxPackages_hardened.virtualbox</li>    <li>linuxPackages_hardened.virtualboxGuestAdditions</li>    <li>linuxPackages_testing_bcachefs.virtualbox</li>    <li>linuxPackages_testing_bcachefs.virtualboxGuestAdditions</li>    <li>linuxPackages_xen_dom0.virtualbox</li>    <li>linuxPackages_xen_dom0.virtualboxGuestAdditions</li>    <li>linuxPackages_xen_dom0_hardened.virtualbox</li>    <li>linuxPackages_xen_dom0_hardened.virtualboxGuestAdditions</li>    <li>linuxPackages_zen.virtualbox</li>    <li>linuxPackages_zen.virtualboxGuestAdditions</li>    <li>virtualbox</li>    <li>virtualboxExtpack</li>    <li>virtualboxHardened</li>    <li>virtualboxHeadless</li>    <li>virtualboxWithExtpack</li>  </ul></details>

**Pull request merged**
