### PR TITLE
obsidian: 1.5.3 -> 1.5.8

### PR DESCRIPTION
**Pull request by MichelleGranat**
## Description of changes
- Updated hashes of binaries
- Updated version on electron

## Things done
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by sdht0** [comment]
Nice.

You should rename the commit message and PR title to follow the conventions [like so](https://github.com/NixOS/nixpkgs/pull/277002/commits).

**Comment by MichelleGranat** [comment]
Thanks for the feedback.
I have changed the name of the PR as requested.
Is it critical to change the commit message? 
GitHub [strongly discourages it](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message#amending-older-or-multiple-commit-messages). I will take note of that next time I commit.

**Comment by sdht0** [comment]
I'd recommend following the nixpkgs [commit conventions](https://github.com/NixOS/nixpkgs/blob/6643d56edbd698c451bee96f0df2dcc2ddb1f52e/pkgs/README.md#commit-conventions) and do the rebase. Force pushing to PR branches is a standard practice here. You don't even need 2 commits and can merge them into a single one.

**Review by solson — APPROVED** [review]

**Review by sdht0 — APPROVED** [review]
Thanks for the changes.

I tested the new version locally (using overlay) and all seems to be working.

**Comment by MichelleGranat** [comment]
Thanks for being nice and patient

**Review by kashw2 — APPROVED** [review]

**Review by Defelo — APPROVED** [review]

**Review by drupol — APPROVED** [review]

**Pull request merged**
