### PR TITLE
pythonPackages.spacy: loosen dependency version bounds

### PR DESCRIPTION
**Pull request by mattmelling**
###### Motivation for this change
`python37Packages.spacy` depends on `0.32.0,<0.33.0`, but `wheel` has recently been updated to `0.33.4`. This change removes the `<0.33.0` restriction to allow compatibility with future versions.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by mattmelling** [comment]
I force pushed an update after somehow accidentally deleting a char between testing and committing - only noticed this evening during a rebuild while looking at another package. i hope this is OK.

**Review by jonringer — COMMENTED** [review]
Title of PR and commit should be `pythonPackages.spacy: ...`. I would do "loosen dependency version bounds" or something similar

this is what is mean by pkg-name in [CONTRIBUTING](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes)

**Comment by mattmelling** [comment]
@jonringer Thanks for the feedback. Should I amend the commit message and simply edit the PR title? Or would it be more appropriate to close and create a new PR to correct this?

**Comment by FRidh** [comment]
Amend.

**Comment by jonringer** [comment]
Sorry, i thought i replied to this. Yes, you should just amend an existing PR. 

Plenty of people force push changes, so that the commit history looks nice on master. :)

**Comment by mattmelling** [comment]
Thanks for the feedback guys! :)

**Pull request merged**
