### PR TITLE
freeplane: 1.9.14 -> 1.11.4

### PR DESCRIPTION
**Pull request by charles-dyfis-net**
Thanks to @yuuyins for the desktop items and JVM configuration tweaks. Thanks to Arthur Kaufmann for nudging me to come back to this and get it finished. :)

###### Description of changes

Update Freeplane to 1.11.4.

Desktop items added and JVM configuration tweaks added, courtesy of @yuuyins (who submitted them previously as part of draft PR #202372).

This no longer requires a separate Emoji download step, and is compatible with Gradle 7 (but not Gradle 8). Tested to work on aarch64-darwin, so dropped the Linux-only flag.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [X] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kashw2** [comment]
closes https://github.com/NixOS/nixpkgs/issues/177199

**Review by maxhbr — APPROVED** [review]
I tested it with multiple mindmaps and it worked like a charm.

I think this should be merged!

**Comment by maxhbr** [comment]
hey @charles-dyfis-net, I took this PR and added another jump to 1.11.8 on top in https://github.com/NixOS/nixpkgs/pull/275479

**Comment by pbsds** [comment]
included in #275479

**Pull request merged**
