### PR TITLE
handbrake: 0.9.9 -> 0.10.2

### PR DESCRIPTION
**Pull request by devhell**
The changelog is quite extensive, for more information please find the
changes documented here:
https://github.com/HandBrake/HandBrake/blob/master/NEWS

Built and run successfully on local.

### CODE REVIEW

**Comment by wmertens** [comment]
Eh, shouldn't the checksum be updated at least?

**Comment by devhell** [comment]
Duh.

**Comment by devhell** [comment]
@wmertens I'll leave this one alone, there have been obvious changes in regards to the patch, and I have no idea what the policy here is.

**Comment by wmertens** [comment]
Well the problem is that handbrake basically ships with its own build system and in order to fix statefulness, reduce duplication and build time I split out their patches and made it build with the relevant Nix packages.

This is a bit of work but the other packages in NixPkgs benefit from it.

Alternative is to make a wrapper build that requires all the sources Handbrake wants, puts them together in a build directory and then runs the Handbrake builder. Less admin work, more resource wastage.

**Pull request closed without merging**
