### PR TITLE
gnupg: 2.2.27 -> 2.3.3

### PR DESCRIPTION
**Pull request by colemickens**
###### Motivation for this change

This PR replaces #121083.

This upgrades gnupg to latest stable, which is 2.3.3.

Here is the release announce mail: https://lists.gnupg.org/pipermail/gnupg-announce/2021q4/000466.html

Pre-emptively, I do not plan to change the style in these files regarding optional deps/features that were expressed in #121083, though I did make the other requested style changes.

cc: @stigtsp

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by colemickens** [comment]
(The force pushes were minor cleanups - removing some accidental patch cruft and re-removing peti as maintainer.)

**Comment by colemickens** [comment]
cc: @stigtsp can you please see if this patching in this PR https://github.com/NixOS/nixpkgs/pull/121085/files and enabling the option it adds.... does it allow you to NOT "disable-ccid" in your gpg config?

**Review by SuperSandro2000 — COMMENTED** [review]
If we follow the contributing guide the second commit should contain something like ``fix eval by replacing alias`` and the third one shouldn't only be a regex.

**Comment by colemickens** [comment]
@SuperSandro2000 I updated the commit messages. Thanks for the fast reviews.

**Comment by colemickens** [comment]
For folks at home. you can:
1. Use home-manager
2. Override the programs.gnupg.package to be this one.
3. PROPERLY KILL AND RESTART GPG (<= if you get pinentry issues, you likely didn't do this correctly and gpg-agent got started automatically, incorrectly).

Then you'll see that gpg-agent is 2.3.3 and gpg --version the same. Then you can test whatever scenarios.

I think many folks will find their Yubikeys don't work unless they either disable ccid, or enable gpgSmartcard rules per my other PR. A bunch of Nix stupidly proving out these scenarios is available here for review: https://github.com/cole-mickens/nixcfg/blob/80e7391cfc434d0642a1c47edc736ff831887a04/mixins/gpg-agent.nix

(In there you'll see how I'm testing this PR fairly directly, and the steps I've gone through to validate how/why gpg 2.3 affects yubikeys)

**Comment by colemickens** [comment]
I've been using this on a couple of machines, forwarding my gpg-agent/yubikey socket around and things are working like normal (except it maybe seems to have the horrendous bug requiring  constantly reset/reseats).

**Comment by ajs124** [comment]
Why do we want to go to 2.3.x? 2.2.x is the LTS version supported until 2024.
Although we are behind on that, with version 2.2.32 being the current one.

**Comment by SuperSandro2000** [comment]
> Why do we want to go to 2.3.x? 2.2.x is the LTS version supported until 2024.

Is there any reason to not upgrade? We often use the latest and greatest.

> Although we are behind on that, with version 2.2.32 being the current one.

If this PR does not hit 21.11 we should at least update 2.2 which is more important in my opinion.

**Comment by colemickens** [comment]
Unless there's an established policy for preferring LTS over stable for gnupg, I also am not sure why we'd limit ourselves to LTS. I did ensure that 2.3.3 was considered a normal, stable release when doing this upgrade.

**Comment by ajs124** [comment]
Right. AFAICT not much attention has been paid to gnupg in nixpkgs in recent years. Sticking with an LTS release generally reduces maintenance overhead, e.g. potentially makes it easier to update/apply a security fix, when everybody forgot about gnupg again for a year.

While "latest and greatest" is fine, personally I'd much rather stay with a tried and true version, when it comes to something as critical as gnupg. We probably don't have any official policies on anything like that, though.

**Comment by luizribeiro** [comment]
I'm a fairly new user of Nix / NixOS, so I'm not familiar with how we make these decisions. FWIW, nixpkgs' gnupg package is the only package on my systems that is on 2.2. As an example, both Arch and Homebrew are on 2.3 - so whenever I use gpg agent forwarding from a nix-packaged gnupg to one of my other hosts I get a warning or even incompatibility issues sometimes. If we don't want to upgrade `gnupg`, I would hope we at least provide this as `gnupg33` (or provide the LTS version as `gnupg32` for folks who don't want to upgrade).

**Comment by stigtsp** [comment]
I'm in favor of merging this now that 21.11 is out - or at least making GnuPG 2.3 available as `gnupg23`. 

Have been using a local version of this patch for a couple of months, with smart cards, tpm2 and yubikeys and it works fine for me (except requiring disable-ccid).

**Comment by nazarewk** [comment]
I'm also in favor of at least adding this one as `gnupg23` so users can still stick to the old version.

**Comment by stigtsp** [comment]
Recently merged #121085 to master

**Comment by stigtsp** [comment]
@colemickens @ajs124 Are you ok with merging this to stable? Unless there are specific concerns that I've missed, I think we should.

**Review by SuperSandro2000 — APPROVED** [review]

**Pull request merged**
