### PR TITLE
singularity: 4.1.0 -> 4.1.1

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Changelog: https://github.com/sylabs/singularity/releases/tag/v4.1.1

cc @ShamrockLee @jbedo 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 285539` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>singularity</li>
    <li>singularity-overriden-nixos</li>
    <li>udocker</li>
    <li>udocker.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 285539` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>singularity</li>
    <li>singularity-overriden-nixos</li>
    <li>udocker</li>
    <li>udocker.dist</li>
  </ul>
</details>

**Review by LeSuisse — APPROVED** [review]
Looks good and upstream changes are pretty minimal.

Result of `nixpkgs-review pr 285539` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>singularity</li>
    <li>singularity-overriden-nixos</li>
    <li>udocker</li>
    <li>udocker.dist</li>
  </ul>
</details>

**Comment by LeSuisse** [comment]
How should we handle this on 23.11 which is currently using 4.0.2? [4.1.0](https://github.com/sylabs/singularity/releases/tag/v4.1.0) seems big but overall reasonable. Backporting the deps upgrades independently is probably going to require some manual work and might not be straightforward.

**Comment by ShamrockLee** [comment]
Sorry for not being responsive recently. I'll take a look tomorrow and inspect the impact of backporting.

> Backporting the deps upgrades independently is probably going to require some manual work and might not be straightforward.

I don't quite get this part. It seems that most updates change only the versions and hashes.

**Comment by LeSuisse** [comment]
> Sorry for not being responsive recently. I'll take a look tomorrow and inspect the impact of backporting.

:+1: 

> I don't quite get it. It seems that most updates change only the versions and hashes.

Those packages have also been upgraded between 4.0.2 and and 4.1.0 so cherry-picking the upstream commits is very likely to conflict and we are going to need to create and maintain an out of tree patch.

**Comment by ShamrockLee** [comment]
> Those packages have also been upgraded between 4.0.2 and and 4.1.0 so cherry-picking the upstream commits is very likely to conflict and we are going to need to create and maintain an out of tree patch.

I think it's inevitable for all projects that maintain "stable branches" or "version branches".

**Comment by ShamrockLee** [comment]
1. The vulnerabilities fixed by Sylabs Singularity CE 4.1.1 only affect the releases 4.1.0-rc.1 and 4.1.0. Version 4.0.2 on Nixpkgs release 23.11 is not affected.
2. The version bump commits from 4.0.2 to 4.1.0 doesn't contain additional expression changes. Cherry-picking those commits goes smoothly without conflicts.
3. Based on the previous point, backporting singularity from 4.0.2 to 4.1.0 are not likely to increase the likelihood of conflicts for future backports.

**Pull request merged**
