### PR TITLE
python-packages networkx: 1.9.1 -> 1.10

### PR DESCRIPTION
**Pull request by FRidh**
20 / 2079 tests failed with both py27 and py34.
networkx is compatible with other python version than py27, so I removed
the disabled flag.

### CODE REVIEW

**Comment by FRidh** [comment]
> The log length has exceeded the limit of 4 Megabytes (this usually means that test suite is raising the same exception over and over).

> The build has been terminated.

**Comment by lethalman** [comment]
I don't think we should update a package and forget about tests. Check what tests are failing, and eventually disable/fix them.

**Comment by FRidh** [comment]
@lethalman it runs now on all Python versions except PyPy without disabling tests. PyPy is disabled because its currently incompatible. 

Tested with nox-review wip

**Comment by FRidh** [comment]
@lethalman could you merge this?

**Pull request merged**
