### PR TITLE
rtorrent: 0.9.4 -> 0.9.6

### PR DESCRIPTION
**Pull request by ebzzry**

### CODE REVIEW

**Comment by rycee** [comment]
Perhaps better to use http://rtorrent.net/downloads/ as upstream source?

**Comment by codyopel** [comment]
@rycee, if anything github would be a more reliable source if there is any reason to change it.

@ebzzry Just a heads up that someone is probably going to complain about this being broken even though it isn't.  After 0.9.4+ the entire configuration syntax was overhauled so will break all existing configs.  The information is in the docs and the github wiki are both partially or completely outdated so I have an example config that I use: https://github.com/codyopel/dotfiles/blob/master/rtorrent.rc

**Comment by ebzzry** [comment]
@rycee, @codyopel what upstream source should we use?

@codyopel Yes, but this is something that we should expect, even though it is a bit unfortunate. Maybe he should have changed the version number to 0.10.0, to indicate a non-backward compatible change.

**Comment by ebzzry** [comment]
@rycee, @codyopel I used <http://rtorrent.net/downloads> as the upstream source, for now.

**Comment by codyopel** [comment]
Thats fine, I typically use github's release tarballs just because github rarely has downtime and is more reliable in that sense.

And yeah the config changes are unavoidable.

**Comment by rycee** [comment]
Both rtorrent.net or github are fine with me. Unfortunately the downloads are not identical, the tarball on rtorrent.net seems to be generated by `make dist` or something similar while the github one is the typical "raw repo" style.

Had they been the same I suppose the most prudent thing would have been to include both in the `fetchurl` call.

**Comment by jagajaga** [comment]
Please squash commits.

**Comment by ebzzry** [comment]
@jagajaga squashed.

**Pull request merged**
