### PR TITLE
ledger-autosync: fix build with Python 3.12 and don't propagate ledger and hledger

### PR DESCRIPTION
**Pull request by dotlambda**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by dotlambda** [comment]
> What do we need 3.11 for here?

for `imp`

**Comment by dotlambda** [comment]
> Upstream doesn’t actually mention nose at all

True. I dropped the nose dependency.

**Comment by emilazy** [comment]
Sorry, should have read more closely…

Seems reasonable (albeit unfortunate) to me, but since upstream uses pytest, can we at least drop the nose use here?

**Comment by dotlambda** [comment]
The alternative to using `python311Packages` would be applying https://github.com/egh/ledger-autosync/commit/b7a2a185b9c3b17764322dcc80153410d12e6a5f and https://github.com/egh/ledger-autosync/commit/453d92ad279e6c90fadf835d1c39189a1179eb17.

**Comment by emilazy** [comment]
Perhaps we should just bump to the current Git HEAD. The conversion to pytest was actually after the latest release, and upstream was [planning on cutting a release in July](https://github.com/egh/ledger-autosync/issues/143). That hasn’t yet happened, but there’s been a lot of clean‐up and fixes since, so if upstream thought it was ready for release I say we should just bump.

(I was looking at these packages a while ago but paged out most of the memories…)

**Comment by DamienCassou** [comment]
> Perhaps we should just bump to the current Git HEAD

I think this makes sense given the state of the project. I'm fine merging the PR as it is though.

What do you say @dotlambda?

**Comment by dotlambda** [comment]
Let's give upstream a little more time to cut a release before we change use the git HEAD.

**Review by DamienCassou — APPROVED** [review]
Changes are great, thank you for your work. I'm fine merging that or waiting for upstream to release or using git HEAD.

**Pull request merged**
