### PR TITLE
go: Fix the build in non-root sandboxes

### PR DESCRIPTION
**Pull request by thufschmitt**
###### Motivation for this change

Workaround for <https://github.com/golang/go/issues/42525>

(Also related to <https://github.com/NixOS/nix/issues/3245>)

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Maybe we want to throw that on staging?

**Review by Mic92 — APPROVED** [review]

**Comment by zowoq** [comment]
Is this only an issue with `go_1_16` or does it need to be applied to `go_1_17` as well?

**Comment by regnat** [comment]
> Is this only an issue with `go_1_16` or does it need to be applied to `go_1_17` as well?

I actually didn’t try it with other go versions, but I guess it would need to be ported here as well since the upstream bug is still open

**Comment by hhoeflin** [comment]
Will this be merged? One of my builds is also affected by this. Thanks

**Comment by SuperSandro2000** [comment]
The same needs to be applied to go 1.17 and we should target staging because this change is not very important and does not need to trigger so many rebuilds on master.

**Review by c00w — APPROVED** [review]

**Comment by gurgl** [comment]
Just chiming in to say im affacted by this too. Running nix on ubuntu 20.04, if that matters.

**Comment by zowoq** [comment]
@ofborg build go_1_17

**Comment by zowoq** [comment]
I added the patch to the go 1.18 PR in https://github.com/NixOS/nixpkgs/pull/157650 so it doesn't get overlooked.

I'll rebase this after the patch lands in staging and merge.

**Comment by zowoq** [comment]
@jonringer Can I squeeze this into the new `staging-next`?

**Comment by jonringer** [comment]
I just started this as you posted :(

**Comment by zowoq** [comment]
I was waiting for the merge action to push the patch from master to staging when I saw you do it manually. 😆 

This waited a couple of months until I picked it up, it can wait until the next cycle.

**Pull request merged**
