### PR TITLE
MythTV 29.1 -> 30.0

### PR DESCRIPTION
**Pull request by LouisDK1**
#### Motivation for this change

https://github.com/NixOS/nixpkgs/issues/54596

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

Jonathan Rudenberg <jonathan@titanous.com>

### CODE REVIEW

**Review by titanous — APPROVED** [review]

**Comment by mmahut** [comment]
@GrahamcOfBorg build mythtv

**Comment by mmahut** [comment]
@titanous @LouisDK1 please see the build failures.

**Comment by LouisDK1** [comment]
@mmahut will look into this tomorrow.

**Comment by LouisDK1** [comment]
As new dependencies are introduced in 30.0 the configure file is updated with some unpure hacks. I'll patch this and make a new commit before the end of the weekend.

**Comment by LouisDK1** [comment]
I a bit more complicated to fix it. Will look into this in the upcoming week and submit another commit.

**Comment by LouisDK1** [comment]
I need to somehow to detect if mythtv is being build on a system using some "nvidia*" driver and if not mythtv should be build with "--disable-xnvctrl" as an additional configureFlags.
This could be done with some .override option. Should need to figure out how to do this. 

Also line #6673 should be commented to avoid build errors. I'll patch that after the above has been solved.

**Comment by LouisDK1** [comment]
The problem is that building fails on my intel-only system due to xnvctrl not being present. Is it correct that this would too happen on a nvidia system because the building is done inside a sandbox?

If yes maybe I should just disable xnvctrl by default.

**Review by ck3d — APPROVED** [review]

**Pull request closed without merging**
