### PR TITLE
nzbget.service override nzbget.conf broken paths with current derivation

### PR DESCRIPTION
**Pull request by csingley**
###### Motivation for this change
Clean rework of [this ugly nzbget bugfix](https://github.com/NixOS/nixpkgs/pull/30144), with commits squashed & extraneous commits removed.  Sorry about that.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by c0bw3b** [comment]
@csingley for final review

( follow up to #30144 )

**Comment by csingley** [comment]
Yes, this is right.

**Comment by c0bw3b** [comment]
Phew I wanted to ping @fadenb too actually but thanks :)

**Comment by c0bw3b** [comment]
Well he already approved the changes on the previous PR so let's not stall this longer.

**Pull request merged**
