### PR TITLE
nixos-option: Support flake

### LINKED ISSUE #97855: nixos-option does not support flakes
**Describe the bug**
Running `nixos-option nix.nixPath` fails because I don't have a `nixpkgs` entry in my NIX_PATH. This requires me to use my compatibility wrapper (https://github.com/cole-h/nixos-config/tree/c02cdf4702db3e383073426396dea31c40ae6e71/compat) with `-I nixpkgs=compat`; otherwise, the program aborts.

**To Reproduce**
1. `nixos-option nix.nixPath` without `nixpkgs` in NIX_PATH
2. Observe abort due to lack of `<nixpkgs/nixos>`

**Expected behavior**
I would expect a `--flake` flag, just like `nixos-rebuild` has, to be able to e.g. `nixos-option nix.nixPath --flake .#hostname`.

**Notify maintainers**
cc @Ma27 @chkno 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.7-zen1, NixOS, 20.09.20200912.ac8a276-cosmere (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 3.0pre20200903_8a945d6`
 - channels(vin): `""`
 - channels(root): `""`
 - nixpkgs: `/home/vin/.config/nixpkgs/compat`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: installer.tools.nixos-option
```

### PR DESCRIPTION
**Pull request by azuwis**
## Description of changes

Need https://github.com/NixOS/nixpkgs/pull/313497, tested with:

```sh
$ nixos-option
$ nixos-option --flake /etc/nixos
$ nixos-option --flake /etc/nixos#machine1
$ nixos-option --flake github:user/repo#machine2
```

Fixes https://github.com/NixOS/nixpkgs/issues/97855

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by deifactor** [comment]
Drive-by thought: I definitely agree that using nix-instantiate or similar as opposed to using nix as a library is the right move here.

**Comment by Aleksanaa** [comment]
I've amended your commit to the original PR https://github.com/NixOS/nixpkgs/pull/313497/commits. Thanks!

**Comment by Aleksanaa** [comment]
Also would you mind becoming the maintainer of nixos-option?

**Comment by Aleksanaa** [comment]
Added!

**Pull request closed without merging**
