### PR TITLE
perlPackages.AppMusicChordPro: 0.977 -> 6.010

### PR DESCRIPTION
**Pull request by stig**
Added missing dependency on perlPackages.FileHomeDir.

Also bumped other required dependencies:

- perlPackages.FileLoadLines: 1.01 -> 1.021
- perlPackages.PDFAPI2: 2.042 -> 2.044
- perlPackages.StringInterpolateNamed: 1.00 -> 1.03
- perlPackages.TextLayout: 0.019 -> 0.031
  Also added missing IOString dependency.

Built and tested locally on MacOS. The program works for my 31 songs, and fixes many bugs compared to the previous version :-) 

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by stigtsp — COMMENTED** [review]
Heisann Stig!

Thanks for the updates, however a small nit: Please change the prefix in the commit messages to "perlPackages" instead of "perl-packages"

Apart from that, looks good to me.

**Comment by stig** [comment]
Result of `nixpkgs-review pr 241657` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>fntsample</li>
    <li>perl534Packages.AppMusicChordPro</li>
    <li>perl534Packages.FileLoadLines</li>
    <li>perl534Packages.PDFAPI2</li>
    <li>perl534Packages.StringInterpolateNamed</li>
    <li>perl534Packages.TextLayout</li>
    <li>perl536Packages.AppMusicChordPro</li>
    <li>perl536Packages.FileLoadLines</li>
    <li>perl536Packages.PDFAPI2</li>
    <li>perl536Packages.StringInterpolateNamed</li>
    <li>perl536Packages.TextLayout</li>
  </ul>
</details>

**Review by stigtsp — APPROVED** [review]
LGTM, thanks. Waiting for ofborg to agree.

**Comment by stig** [comment]
> Heisann Stig!

Heisann! Kjekt å krysse spor med en navnebror på denne måten i steden for å få GitHub meldingene dine 😄

**Pull request merged**
