### PR TITLE
python3Packages.scikit-image: 0.21.0 -> 0.22.0

### PR DESCRIPTION
**Pull request by yl3dy**
## Description of changes

Updated to the latest stable. Changelog (0.22.0 has only trivial changes compared to 0.22.0rc1): https://github.com/scikit-image/scikit-image/releases/tag/v0.22.0rc1.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by risicle** [comment]
`nixpkgs-review` reveals no new failures, macos 12 x86_64 & nixos x86_64.

FWIW on macos 12 x86_64 I get one failure in the test suite:

```
_______________________ test_ellipse_parameter_stability _______________________

    def test_ellipse_parameter_stability():
        """The fit should be modified so that a > b
        """

        for angle in np.arange(0, 180 + 1, 1):
            # generate rotation matrix
            theta = np.deg2rad(angle)
            c = np.cos(theta)
            s = np.sin(theta)
            R = np.array([
                [c, -s],
                [s, c]]
            )

            # generate points on ellipse
            t = np.linspace(0, 2 * np.pi, 20)
            a = 100
            b = 50
            points = np.array([a * np.cos(t), b * np.sin(t)])
            points = R @ points

            # fit model to points
            ellipse_model = EllipseModel()
            ellipse_model.estimate(points.T)
            _, _, a_prime, b_prime, theta_prime = ellipse_model.params

>           assert_almost_equal(theta_prime, theta)

/nix/store/isqh08lghpz68jzi5g56wxp8n7qaydvg-python3.11-scikit-image-0.22.0/lib/python3.11/site-packages/skimage/measure/tests/test_fit.py:247:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = (0.7853981633974483, 2.356194490192345), kwds = {}

    @wraps(func)
    def inner(*args, **kwds):
        with self._recreate_cm():
>           return func(*args, **kwds)
E           AssertionError: 
E           Arrays are not almost equal to 7 decimals
E            ACTUAL: 0.7853981633974483
E            DESIRED: 2.356194490192345

/nix/store/rfqs6lmm832yp3aqihsjdfvvs0wvr1a5-python3-3.11.6/lib/python3.11/contextlib.py:81: AssertionError
```

...but that's one fewer than I get with 0.21.0 on the same system.

**Comment by yl3dy** [comment]
@risicle Should it be marked as broken on darwin then? Unfortunately I don't have an opportunity to test there and so not sure if disabling this test could hide actual problems.

**Comment by risicle** [comment]
Well, we don't seem to be the only ones with this issue:

https://github.com/scikit-image/scikit-image/issues/7061
https://github.com/scikit-image/scikit-image/issues/7104

In fact I note we omit that file for darwin aarch64, linking to this issue. I'd just expand that to darwin on all platforms.

**Comment by yl3dy** [comment]
Thanks a lot for the suggestion, @risicle! I've expanded disabled test list, could you please verify it on macOS?

**Review by risicle — APPROVED** [review]

**Pull request merged**
