### PR TITLE
[release-22.05] gitlab: 15.4.4 -> 15.6.0

### PR DESCRIPTION
**Pull request by yayayayaka**
###### Description of changes

https://about.gitlab.com/releases/2022/11/22/gitlab-15-6-released/

Backport of #202541 that additionally updates libgit2 to v1.5.0 (see https://github.com/NixOS/nixpkgs/pull/202541#issue-1461951261).

Will mark as ready once my NixOS test passed.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by yayayayaka** [comment]
`gitlab-workhorse.service` failed in the test. I'll take a look.

**Comment by yayayayaka** [comment]
Ah, they've bumped workhorse to Go 1.18 now.

**Comment by yayayayaka** [comment]
```
Nov 23 18:34:12 gitlab gitaly[1263]: time="2022-11-23T18:34:12.780Z" level=error msg="Gitaly shutdown" error="unsupported Git version: \"2.36.2\""
```

Hm, we should keep the git version in sync with the one gitaly likes to see.

**Comment by onny** [comment]
Is backport to 22.05 required since 22.11 will be released soon?

**Comment by yayayayaka** [comment]
Given the fact that bumping gitlab to 15.6 needs some additional fixups in the module, I don't think it is worth doing so. Gitlab 15.4 will be supported until the end of the NixOS 22.05 release cycle.

**Pull request closed without merging**
