### PR TITLE
python312Packages.uproot: 5.5.0 -> 5.5.1; fix build

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Things done

Changelog: https://github.com/scikit-hep/uproot5/releases/tag/v5.5.1

cc @veprbl

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
I had to disable several tests failing with:
```
_____________________________ test_split_encoding ______________________________

    def test_split_encoding():
>       filename = skhep_testdata.data_path(
            "Run2012BC_DoubleMuParked_Muons_1000evts_rntuple_v1-0-0-0.root"
        )


tests/test_1191_rntuple_fixes.py:55:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

filename = 'Run2012BC_DoubleMuParked_Muons_1000evts_rntuple_v1-0-0-0.root'
raise_missing = True, cache_dir = None

    def data_path(
        filename: str, raise_missing: bool = True, cache_dir: str | None = None
    ) -> str:
        if remote_files.is_known_remote(filename):
            return remote_files.remote_file(filename, raise_missing=raise_missing)

        if filename not in known_files and raise_missing:
>           raise FileNotFoundError(filename)
E           FileNotFoundError: Run2012BC_DoubleMuParked_Muons_1000evts_rntuple_v1-0-0-0.root

cache_dir  = None
filename   = 'Run2012BC_DoubleMuParked_Muons_1000evts_rntuple_v1-0-0-0.root'
raise_missing = True

/nix/store/rmz9ypjg4jp6jk512jbz1hzp571xljmx-python3.12-scikit-hep-testdata-0.4.48/lib/python3.12/site-packages/skhep_testdata/local_files.py:46: FileNotFoundError

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 357938`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 24 packages built:</summary>
  <ul>
    <li>python311Packages.coffea</li>
    <li>python311Packages.coffea.dist</li>
    <li>python311Packages.dask-awkward</li>
    <li>python311Packages.dask-awkward.dist</li>
    <li>python311Packages.mplhep</li>
    <li>python311Packages.mplhep.dist</li>
    <li>python311Packages.scikit-hep-testdata</li>
    <li>python311Packages.scikit-hep-testdata.dist</li>
    <li>python311Packages.uproot</li>
    <li>python311Packages.uproot.dist</li>
    <li>python311Packages.vector</li>
    <li>python311Packages.vector.dist</li>
    <li>python312Packages.coffea</li>
    <li>python312Packages.coffea.dist</li>
    <li>python312Packages.dask-awkward</li>
    <li>python312Packages.dask-awkward.dist</li>
    <li>python312Packages.mplhep</li>
    <li>python312Packages.mplhep.dist</li>
    <li>python312Packages.scikit-hep-testdata</li>
    <li>python312Packages.scikit-hep-testdata.dist</li>
    <li>python312Packages.uproot</li>
    <li>python312Packages.uproot.dist</li>
    <li>python312Packages.vector</li>
    <li>python312Packages.vector.dist</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 24 packages built:</summary>
  <ul>
    <li>python311Packages.coffea</li>
    <li>python311Packages.coffea.dist</li>
    <li>python311Packages.dask-awkward</li>
    <li>python311Packages.dask-awkward.dist</li>
    <li>python311Packages.mplhep</li>
    <li>python311Packages.mplhep.dist</li>
    <li>python311Packages.scikit-hep-testdata</li>
    <li>python311Packages.scikit-hep-testdata.dist</li>
    <li>python311Packages.uproot</li>
    <li>python311Packages.uproot.dist</li>
    <li>python311Packages.vector</li>
    <li>python311Packages.vector.dist</li>
    <li>python312Packages.coffea</li>
    <li>python312Packages.coffea.dist</li>
    <li>python312Packages.dask-awkward</li>
    <li>python312Packages.dask-awkward.dist</li>
    <li>python312Packages.mplhep</li>
    <li>python312Packages.mplhep.dist</li>
    <li>python312Packages.scikit-hep-testdata</li>
    <li>python312Packages.scikit-hep-testdata.dist</li>
    <li>python312Packages.uproot</li>
    <li>python312Packages.uproot.dist</li>
    <li>python312Packages.vector</li>
    <li>python312Packages.vector.dist</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:x: 20 packages failed to build:</summary>
  <ul>
    <li>python311Packages.coffea</li>
    <li>python311Packages.coffea.dist</li>
    <li>python311Packages.dask-awkward</li>
    <li>python311Packages.dask-awkward.dist</li>
    <li>python311Packages.mplhep</li>
    <li>python311Packages.mplhep.dist</li>
    <li>python311Packages.uproot</li>
    <li>python311Packages.uproot.dist</li>
    <li>python311Packages.vector</li>
    <li>python311Packages.vector.dist</li>
    <li>python312Packages.coffea</li>
    <li>python312Packages.coffea.dist</li>
    <li>python312Packages.dask-awkward</li>
    <li>python312Packages.dask-awkward.dist</li>
    <li>python312Packages.mplhep</li>
    <li>python312Packages.mplhep.dist</li>
    <li>python312Packages.uproot</li>
    <li>python312Packages.uproot.dist</li>
    <li>python312Packages.vector</li>
    <li>python312Packages.vector.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>python311Packages.scikit-hep-testdata</li>
    <li>python311Packages.scikit-hep-testdata.dist</li>
    <li>python312Packages.scikit-hep-testdata</li>
    <li>python312Packages.scikit-hep-testdata.dist</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:x: 20 packages failed to build:</summary>
  <ul>
    <li>python311Packages.coffea</li>
    <li>python311Packages.coffea.dist</li>
    <li>python311Packages.dask-awkward</li>
    <li>python311Packages.dask-awkward.dist</li>
    <li>python311Packages.mplhep</li>
    <li>python311Packages.mplhep.dist</li>
    <li>python311Packages.uproot</li>
    <li>python311Packages.uproot.dist</li>
    <li>python311Packages.vector</li>
    <li>python311Packages.vector.dist</li>
    <li>python312Packages.coffea</li>
    <li>python312Packages.coffea.dist</li>
    <li>python312Packages.dask-awkward</li>
    <li>python312Packages.dask-awkward.dist</li>
    <li>python312Packages.mplhep</li>
    <li>python312Packages.mplhep.dist</li>
    <li>python312Packages.uproot</li>
    <li>python312Packages.uproot.dist</li>
    <li>python312Packages.vector</li>
    <li>python312Packages.vector.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>python311Packages.scikit-hep-testdata</li>
    <li>python311Packages.scikit-hep-testdata.dist</li>
    <li>python312Packages.scikit-hep-testdata</li>
    <li>python312Packages.scikit-hep-testdata.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 357938`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 24 packages built:</summary>
  <ul>
    <li>python311Packages.coffea</li>
    <li>python311Packages.coffea.dist</li>
    <li>python311Packages.dask-awkward</li>
    <li>python311Packages.dask-awkward.dist</li>
    <li>python311Packages.mplhep</li>
    <li>python311Packages.mplhep.dist</li>
    <li>python311Packages.scikit-hep-testdata</li>
    <li>python311Packages.scikit-hep-testdata.dist</li>
    <li>python311Packages.uproot</li>
    <li>python311Packages.uproot.dist</li>
    <li>python311Packages.vector</li>
    <li>python311Packages.vector.dist</li>
    <li>python312Packages.coffea</li>
    <li>python312Packages.coffea.dist</li>
    <li>python312Packages.dask-awkward</li>
    <li>python312Packages.dask-awkward.dist</li>
    <li>python312Packages.mplhep</li>
    <li>python312Packages.mplhep.dist</li>
    <li>python312Packages.scikit-hep-testdata</li>
    <li>python312Packages.scikit-hep-testdata.dist</li>
    <li>python312Packages.uproot</li>
    <li>python312Packages.uproot.dist</li>
    <li>python312Packages.vector</li>
    <li>python312Packages.vector.dist</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 24 packages built:</summary>
  <ul>
    <li>python311Packages.coffea</li>
    <li>python311Packages.coffea.dist</li>
    <li>python311Packages.dask-awkward</li>
    <li>python311Packages.dask-awkward.dist</li>
    <li>python311Packages.mplhep</li>
    <li>python311Packages.mplhep.dist</li>
    <li>python311Packages.scikit-hep-testdata</li>
    <li>python311Packages.scikit-hep-testdata.dist</li>
    <li>python311Packages.uproot</li>
    <li>python311Packages.uproot.dist</li>
    <li>python311Packages.vector</li>
    <li>python311Packages.vector.dist</li>
    <li>python312Packages.coffea</li>
    <li>python312Packages.coffea.dist</li>
    <li>python312Packages.dask-awkward</li>
    <li>python312Packages.dask-awkward.dist</li>
    <li>python312Packages.mplhep</li>
    <li>python312Packages.mplhep.dist</li>
    <li>python312Packages.scikit-hep-testdata</li>
    <li>python312Packages.scikit-hep-testdata.dist</li>
    <li>python312Packages.uproot</li>
    <li>python312Packages.uproot.dist</li>
    <li>python312Packages.vector</li>
    <li>python312Packages.vector.dist</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 24 packages built:</summary>
  <ul>
    <li>python311Packages.coffea</li>
    <li>python311Packages.coffea.dist</li>
    <li>python311Packages.dask-awkward</li>
    <li>python311Packages.dask-awkward.dist</li>
    <li>python311Packages.mplhep</li>
    <li>python311Packages.mplhep.dist</li>
    <li>python311Packages.scikit-hep-testdata</li>
    <li>python311Packages.scikit-hep-testdata.dist</li>
    <li>python311Packages.uproot</li>
    <li>python311Packages.uproot.dist</li>
    <li>python311Packages.vector</li>
    <li>python311Packages.vector.dist</li>
    <li>python312Packages.coffea</li>
    <li>python312Packages.coffea.dist</li>
    <li>python312Packages.dask-awkward</li>
    <li>python312Packages.dask-awkward.dist</li>
    <li>python312Packages.mplhep</li>
    <li>python312Packages.mplhep.dist</li>
    <li>python312Packages.scikit-hep-testdata</li>
    <li>python312Packages.scikit-hep-testdata.dist</li>
    <li>python312Packages.uproot</li>
    <li>python312Packages.uproot.dist</li>
    <li>python312Packages.vector</li>
    <li>python312Packages.vector.dist</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 24 packages built:</summary>
  <ul>
    <li>python311Packages.coffea</li>
    <li>python311Packages.coffea.dist</li>
    <li>python311Packages.dask-awkward</li>
    <li>python311Packages.dask-awkward.dist</li>
    <li>python311Packages.mplhep</li>
    <li>python311Packages.mplhep.dist</li>
    <li>python311Packages.scikit-hep-testdata</li>
    <li>python311Packages.scikit-hep-testdata.dist</li>
    <li>python311Packages.uproot</li>
    <li>python311Packages.uproot.dist</li>
    <li>python311Packages.vector</li>
    <li>python311Packages.vector.dist</li>
    <li>python312Packages.coffea</li>
    <li>python312Packages.coffea.dist</li>
    <li>python312Packages.dask-awkward</li>
    <li>python312Packages.dask-awkward.dist</li>
    <li>python312Packages.mplhep</li>
    <li>python312Packages.mplhep.dist</li>
    <li>python312Packages.scikit-hep-testdata</li>
    <li>python312Packages.scikit-hep-testdata.dist</li>
    <li>python312Packages.uproot</li>
    <li>python312Packages.uproot.dist</li>
    <li>python312Packages.vector</li>
    <li>python312Packages.vector.dist</li>
  </ul>
</details>

**Review by veprbl — APPROVED** [review]
Looks great.

**Pull request merged**
