### PR TITLE
kernel: disable module signing

### PR DESCRIPTION
**Pull request by Atemu**
###### Motivation for this change

https://r13y.com

Closes #107524 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Izorkin** [comment]
This PR breaks work the lockdown module:
```
boot.kernelParams = [ "lockdown=confidentiality" ];
```

**Comment by Atemu** [comment]
Intentionally so. Without enforcing signatures or otherwise preventing root from loading modules, lockdown is pretty pointless AFAICT.

**Comment by ajs124** [comment]
I thought lockdown does enforce signatures? [This](https://man7.org/linux/man-pages/man7/kernel_lockdown.7.html) says that, at least.

**Comment by raboof** [comment]
> I thought lockdown does enforce signatures?

Correct, it does. The lockdown feature depends on module signatures being enabled, because without it you could circumvent the lockdown protections (by loading a custom module that performs the protected actions).

**Review by raboof — COMMENTED** [review]
I'm in favor of this change.

The lockdown feature is a feature that restricts root from performing certain actions. On a 'regular' NixOS machine that does not make much sense, since root could just build and reboot into a kernel that does allow the desired operations.

To make effective use of the lockdown feature, you'd build a hardened image with just the things you need and make sure root cannot reboot into different kernels, using for example EFI Secure Boot (or other mechanisms for other deployment scenario's). Doing that correctly requires some reading and configuration work - if you're going that far anyway, it would be a good idea to customize the kernel build configuration and only include the features you want to be available for that particular use case (either baking them into the kernel directly and not using modules at all, or using module signatures).

I think it's reasonable to have module signatures and lockdown disabled for 'regular' NixOS installations - I think the advantage of having reproducible kernel images outweighs the disadvantage of having to explicitly enable the feature when you need it. We should probably mention it in the release notes - ideally we could point to some documentation on how to effectively use lockdown, though the latter is probably beyond the scope of this PR.

**Comment by raboof** [comment]
Another data point: while Debian and Arch I think by default do include module signatures, OpenWRT does not (https://git.openwrt.org/?p=openwrt/openwrt.git;a=blob;f=target/linux/generic/config-4.14;h=d54ede9efda0a3ffd84e9a0c49dc410a01737d82;hb=refs/tags/v19.07.5#l2736).

**Comment by Atemu** [comment]
OpenWRT doesn't disable module signatures but simply doesn't set the option. Pretty sure it defaults to yes.

**Comment by raboof** [comment]
> OpenWRT doesn't disable module signatures but simply doesn't set the option.

Good point

> Pretty sure it defaults to yes.

I don't think so: I don't see a default in https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/init/Kconfig?h=v5.4.85#n2016, and https://www.kernel.org/doc/Documentation/kbuild/kconfig-language.txt suggests in that case the default is 'n'. If you enable SECURITY_LOCKDOWN_LSM then https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/security/lockdown/Kconfig?h=v5.4.85#n4 automatically also enables MODULE_SIG, though.

**Review by flokli — APPROVED** [review]
I'd love to see some people tinkering with this feature for their own locked down systems (building their own kernels with their own keys), but it probably doesn't make much sense to default to a nonreproducible key in nixpkgs. :+1:

**Review by raboof — APPROVED** [review]

**Comment by kevincox** [comment]
I see that we have other reviewers and some of them have committer rights. As I don't have expertise in this area I'm going to leave it to them.

**Comment by 7c6f434c** [comment]
Yeah, given that most systems presumably fetch a kernel from Hydra and so use a random but same key…

**Comment by r-burns** [comment]
Does this require kernel 5.4? I think this has broken linux-config for older kernels.
https://www.phoronix.com/scan.php?page=news_item&px=Linux-5.4-Adds-Lockdown

**Comment by Atemu** [comment]
It does indeed. I don't know why you'd want to use such an ancient kernel but we shouldn't break that. Fix above.

**Pull request merged**
