### PR TITLE
pythonPackages.pykdtree: init at 1.3.0

### PR DESCRIPTION
**Pull request by PsyanticY**
###### Motivation for this change

pykdtree is a kd-tree implementation for fast nearest neighbour search in Python. The aim is to be the fastest implementation around for common use cases (low dimensions and low number of neighbours) for both tree construction and queries.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
@GrahamcOfBorg build pythonPackages.pykdtree python3Packages.pykdtree

**Comment by Assassinkin** [comment]
@xeji  Thanks for the review. According to the package documentation we can disable the use of openmp by exporting `USE_OMP=0`. I was not able to add openmp as build input as it is not under `all-packages.nix`.

**Comment by xeji** [comment]
Apparently `openmp` is in `llvmPackages.openmp`, so you can add it like this (I didn't check if it really works, just copied from another package):

```
pykdtree = callPackage ../development/python-modules/pykdtree { 
  inherit (llvmPackages) openmp;
};
```

But disabling it should also be fine, so let's try that first.

@GrahamcOfBorg build  pythonPackages.pykdtree python3Packages.pykdtree

**Comment by Assassinkin** [comment]
@xeji  Seems like no build was triggered for darwin.

**Comment by xeji** [comment]
@Assassinkin  it was queued but currently no darwin builder is available (they're run by volunteers and not always up). See https://monitoring.nix.ci/dashboard/db/ofborg?refresh=10s&orgId=1 for status.
So unfortunately we need to wait.

**Comment by Assassinkin** [comment]
@xeji  Thanks for the explanation didn't know about that. In the mean time i was able to add openmp as build input by passing it as follow

```
 pykdtree = callPackage ../development/python-modules/pykdtree {
    inherit (pkgs.llvmPackages) openmp;
  };
```

What do you recommend ? use `openmp` or not (if the current fix do work)

**Comment by xeji** [comment]
According to upstream https://github.com/storpipfugl/pykdtree#benchmarks , multithreading with `openmp` has some performance benefits, so I would enable it if it works.

**Comment by Assassinkin** [comment]
@xeji included openmp.

**Comment by xeji** [comment]
@GrahamcOfBorg build pythonPackages.pykdtree python3Packages.pykdtree

**Comment by xeji** [comment]
Thanks. Let's wait for the Darwin  build, I'll merge if it succeeds.

**Comment by xeji** [comment]
that was the old build job, we can ignore it.

**Pull request merged**
