### PR TITLE
Remove Voxelands package

### PR DESCRIPTION
**Pull request by PyroLagus**
###### Motivation for this change

The project seems to be dead  (no activity since one year in the [repository](https://gitlab.com/voxelands/voxelands)), and the voxelands domain now redirects to some spam/referral site.

### CODE REVIEW

**Comment by srhb** [comment]
It seems https://gitlab.com/voxelands/voxelands would make an acceptable homepage in lieu of the defunct one. If it still works, by the nature of it being a game, I guess it doesn't really need _active_ development to argue for inclusion. However, the version in the repo is also newer than what we have, so maybe it's fine to get rid of it. I'll leave this hanging for a few days.

**Comment by PyroLagus** [comment]
I suppose we could just replace the fetchurl with a fetchgitlab, but the package is going to break eventually anyways when its dependencies become incompatible. And most people are going to want Minetest anyways, which is in the repository.

Either way, I think that URL should be removed as soon as possible. I don't know if it serves malware as well, but it was obviously put up to trick people into visiting it.

**Review by doronbehar — APPROVED** [review]

**Comment by ajs124** [comment]
There's a merge conflict now, because of some treewide changes, but this still seems relevant, since upstream is still dead and the website still redirecting _somewhere_.

**Comment by doronbehar** [comment]
The project isn't dead, apparently. It just switched some domains / hosting: https://voxelands.net/ . It even had a few releases since the release we package: https://gitlab.com/voxelands/voxelands/-/tags . It still builds, so I don't know if it should be considered dead.

**Comment by prusnak** [comment]
It seems the project has been restarted under the new domain. This PR is superseded by https://github.com/NixOS/nixpkgs/pull/104705

**Pull request closed without merging**
