### PR TITLE
i3 man & doc

### PR DESCRIPTION
**Pull request by Profpatsch**
###### Motivation for this change

man pages and documentation have been missing. Introduces a helper to correctly copy manpages. See commits.

### CODE REVIEW

**Comment by grahamc** [comment]
It seems a bit strange to make a whole helper for  this copy task. That is the only hold-up on me merging.

**Review by Profpatsch — COMMENTED** [review]
> It seems a bit strange to make a whole helper for this copy task.

I created the helper because it’s non-trivial shell code to get right and might be useful for other packages (aka `build-support`). Plus, there’s a few tests that will be included in the upcoming test suite for build-support.

**Comment by samueldr** [comment]
A year later, what's the verdict?

Have we seen situations where the helper would be required? Should this be merged?

Though, I'm not sure the helper is right.

 * I don't think it handles compressed (`$x.1.gz`) man pages?
 * I don't think it handles non-standard (other than 0-9) manpages

```
~/.../nixos/tests $ nix-locate -r 'man/man' | cut -d'/' -f6-7 | sort -u | grep ^man/
man/man
man/man0p
man/man1p
man/man1x
man/man3p
man/manm
man/mann
man/mant
man/manx
```

While I can understand the value of the helper, I'm not sure the implementation fills the role (yet).

**Comment by Profpatsch** [comment]
Personally I have no strong incentive to get this merged (I don’t use `i3` at the moment). Please feel free to push changes to this branch if you want to use the work I already did, otherwise I’ll close.

**Pull request closed without merging**
