### PR TITLE
Telegraf

### PR DESCRIPTION
**Pull request by Mic92**
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
See also https://github.com/NixOS/nixpkgs/pull/18149

**Comment by Mic92** [comment]
mhm. Looks like I was too slow.

Maybe you could take my ruby script addition and update to telegraf 1.0.0

**Comment by groxxda** [comment]
You could cherry-pick from the other PR, rebase your changes on top, fix open concerns and force push here :wink:

**Comment by Mic92** [comment]
now includes all the changes done by @roblabla

**Comment by Mic92** [comment]
anything left to do?

**Comment by zimbatm** [comment]
Thanks!

**Pull request merged**
