### PR TITLE
nixos-containers: add option for user-specified container dependencies

### PR DESCRIPTION
**Pull request by Thesola10**
###### Motivation for this change
There is currently no way to tell a NixOS container to wait for another container or dependency before starting, which can cause a race condition.

Concrete example I encountered: My Gitea container starts _before_ my MariaDB container, causing Gitea to error out and remain in that state until it is restarted.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Thesola10** [comment]
still waiting for a review

**Comment by SuperSandro2000** [comment]
This should be solvable by https://search.nixos.org/options?channel=unstable&show=systemd.targets.%3Cname%3E.after&from=0&size=50&sort=relevance&type=packages&query=systemd.targets.

**Comment by Thesola10** [comment]
Thanks, skipped the option. Should I close the PR or turn it into an alias? (ex. `containers."A".unit` → `systemd.targets."container@A.service"`)

**Comment by peterhoeg** [comment]
If this isn't clear from the section in the documentation on containers, then an update to the docs would be much appreciated!

**Pull request closed without merging**
