### PR TITLE
clojure: 1.10.1.727 -> 1.10.1.763 

### PR DESCRIPTION
**Pull request by thiagokokada**
###### Motivation for this change

Bump Clojure (changelog): https://clojure.org/releases/tools.

Also, add myself as a maintainer.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 108187` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>clojure</li>
    <li>lumo</li>
  </ul>
</details>

**Review by jlesquembre — APPROVED** [review]
Thanks!

**Comment by thiagokokada** [comment]
@jlesquembre can you send a `/status needs_merger` please, so we can use `marvin` to get this merged fast?

**Review by timokau — APPROVED** [review]
Thanks :)

**Pull request merged**
