### PR TITLE
wine: 1.7.52 -> 1.7.53 + build fixes

### PR DESCRIPTION
**Pull request by bendlas**
Update wine and fix wine-staging

### CODE REVIEW

**Comment by bendlas** [comment]
These patches should probably also be applied to current stable, since I suppose it also has the infinite recursion regression and it also has both wine 1.6 (stable) and wine 1.7 (unstable)

**Comment by abbradar** [comment]
I've updated `winetricks` to `20151110` in https://github.com/NixOS/nixpkgs/commit/fc620ae093592def95fead25de4bd7b2c2638bfb, but you've updated it to `20150826`. I've taken the latest version blindly -- what should we leave in the end, in your opinion?

**Comment by abbradar** [comment]
Oh, I see -- this PR is just older than `20151116` ^_^. OK, I'll make a test build and merge if everything is okay. Thank you very much!

**Comment by abbradar** [comment]
Closed by https://github.com/NixOS/nixpkgs/commit/703aaa6e8965d4743d4ac44cc3b295a07fe92b77

**Pull request closed without merging**
