### PR TITLE
llvmPackages.*: Add devExtraCmakeFlags parameter

### PR DESCRIPTION
**Pull request by pwaller**
## Description of changes

cmake flags have a 'last flag wins' logic, so by appending to the end of
the flags it is possible to override any cmake flag.

It also ignores (and warns) if a flag is unused, so passing flags across
all packages should be safe if you want to ~target one package~ pass flags which aren't supported by all packages.

In combination with #320261, this PR allows consistently overriding all
packages within LLVM with additional cmake arguments. Consistency here
means for example 'if you override LLVM, then all dependencies on it 
also see the overridden LLVM in their input'. Consistency is hard to
achieve with the other obvious way of implementing this as a user: if
you use overrideAttrs then you have to write a big mess of override code
in order to override all dependents, and this can be very difficult in a
cross-compilation scenario using crossSystem and useLLVM, for example.

With this PR it is possible to write an overlay which overlays
`llvmPackages` with `super.llvmPackages.override { devExtraCmakeFlags = [ ... ]; }`,
and then the toolchain used with useLLVM in effect should respect
these flags.

This is useful in development for experimenting with the effect of
various flags, hence the chosen name `devCmakeFlags`.

This won't work out of the box without #341855 applied, which fixes
override passthrough.

See-Also: #320261, #341855

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by alyssais** [comment]
Could you share an example use case? What flags did you want to set?

**Comment by pwaller** [comment]
> Could you share an example use case? What flags did you want to set?

Setting LLVM_BUILD_INSTRUMENTED=IR, LLVM_PROFDATA, LLVM_USE_LTO in various cases in order to get a PGO/LTO build is one.

More generally, as a dev, I want to test LLVM in a variety of different configurations using options documented at https://llvm.org/docs/CMake.html.

Some options may (or may not, I don't know if nixpkgs has a policy on this) deserve being parameters in their own right (like for example the PGO/LTO build maybe), but in general it is useful to be able to access arbitrary cmake parameters consistently across the whole of LLVM for the sake of development and testing.

**Review by alyssais — APPROVED** [review]
Makes sense to be as long as other LLVM maintainers are happy.

**Review by RossComputerGuy — APPROVED** [review]
Any improvements we can make to the dev shell experience, the better.

**Comment by paparodeo** [comment]
> This is useful in development for experimenting with the effect of various flags, hence the chosen name `devCmakeFlags`.

`globalCmakeFlags`? idk. i am neutral-negative on the change. as it is a no-op my preference is to usually delete code that does nothing. though, i haven't touched then llvm stuff in some time so if this change makes life easier for further llvm work it seems positive.

**Comment by pwaller** [comment]
Thanks for the reviews!

> `globalCmakeFlags`? idk. 

The word 'global' is probably too strong since it might imply 'beyond the llvm packageset' or 'influencing the cmake flags of other projects', which this is not. My thinking of including 'dev' in the name was to discourage general use. (Although if one were found, it could be renamed).

> as it is a no-op my preference is to usually delete code that does nothing.

There are lots of things which are effectively no-op, but their existence enables additional use cases through overriding. This is such a case where lacking the passthrough it is quite difficult to achieve without patching nixpkgs, which is inconvenient and hinders experimentation and development.

**Review by paparodeo — APPROVED** [review]

**Comment by RossComputerGuy** [comment]
I assume we're good to merge?

**Pull request merged**
