### PR TITLE
WIP python37Packages.textacy: fixing broken package

### PR DESCRIPTION
**Pull request by mattmelling**
###### Motivation for this change
Added missing dependency and fixed a broken package version restriction.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by jonringer — COMMENTED** [review]
This package is in an invalid state.

I tried enabling tests, and found that it was broken by scikit-learn

issue submitted upstream here:
https://github.com/chartbeat-labs/textacy/issues/260

**Comment by risicle** [comment]
Builds for me non-nixos linux x86_64

> This package is in an invalid state.

What do you mean by this?

**Comment by jonringer** [comment]
scikit-learn 0.21 breaks how the package is used. If you enable the tests you will get this error:

<details> <summary> Really long error msg </summary>

```
>           assert isinstance(TopicModel(model).model, expected)

tests/test_topic_model.py:85:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/nix/store/kzspdnr2wnah99s59d6fkb3zfaf48sb6-python3.7-textacy-0.8.0/lib/python3.7/site-packages/textacy/tm/topic_model.py:125: in __init__
    self.init_model(model, n_topics=n_topics, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <[AttributeError("'TopicModel' object has no attribute 'model'") raised in repr()] TopicModel object at 0x7fffdd7362d0>
model = 'lda', n_topics = 10, kwargs = {}

    def init_model(self, model, n_topics=10, **kwargs):
        if model == "nmf":
            self.model = NMF(
                n_components=n_topics,
                alpha=kwargs.get("alpha", 0.1),
                l1_ratio=kwargs.get("l1_ratio", 0.5),
                max_iter=kwargs.get("max_iter", 200),
                random_state=kwargs.get("random_state", 1),
                shuffle=kwargs.get("shuffle", False),
            )
        elif model == "lda":
            self.model = LatentDirichletAllocation(
                n_topics=n_topics,
                max_iter=kwargs.get("max_iter", 10),
                random_state=kwargs.get("random_state", 1),
                learning_method=kwargs.get("learning_method", "online"),
                learning_offset=kwargs.get("learning_offset", 10.0),
                batch_size=kwargs.get("batch_size", 128),
>               n_jobs=kwargs.get("n_jobs", 1),
E               TypeError: __init__() got an unexpected keyword argument 'n_topics'
```

</details>

It builds because we dont do any tests, but if you were to use the package, usage of the TopicModel class will break without us using a pinned version of scikit-learn 0.20

**Comment by risicle** [comment]
Ahh good well caught.

**Comment by jonringer** [comment]
What this is also means is that textacy on master is also broken, you just wont know it until you use it :)

**Comment by mattmelling** [comment]
@jonringer Thanks for the feedback.

I was poking around in the awscli package recently and noticed that it overrides some python dependencies such as [pyyaml](https://github.com/NixOS/nixpkgs/blob/483d50e2cc1e4fe6c4b997c90e1c875e237a25ae/pkgs/tools/admin/awscli/default.nix#L24) which is a couple of minor versions behind. Does anyone have any comments on whether that would be an appropriate solution in this case to pin scitkit-learn to <0.21?

**Comment by FRidh** [comment]
No, we cannot have multiple versions of a library in python-packages.nix

**Comment by mattmelling** [comment]
Makes sense. I was hoping to get this package in to a working state then have a go at upgrading it to newer versions (they are up at 0.8.x now). Will leave this PR open and circle back once upstream supports scikit 0.21.

**Comment by mattmelling** [comment]
Closing as this has all been taken care of by @jonringer in https://github.com/NixOS/nixpkgs/pull/68093 :)

**Pull request closed without merging**
