### PR TITLE
chromium: 75.0.3770.90 -> 75.0.3770.142

### PR DESCRIPTION
**Pull request by ivan**
###### Motivation for this change

Fix two CVEs: https://chromereleases.googleblog.com/2019/07/stable-channel-update-for-desktop.html

Replaces #64493.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

I've been running stable 75.0.3770.142 for two days on different machines and everything works fine.

Did not test beta or dev which are often broken now, anyway. I don't like how they hold up stable updates.

### CODE REVIEW

**Comment by ivan** [comment]
Obsoleted by #65633

**Comment by primeos** [comment]
Chromium is becoming quite outdated now, wouldn't it make sense to merge this PR before #65633, assuming that it's already tested?

**Comment by ivan** [comment]
I don't think so, 75 has a lot of CVEs and 76 appears to work fine, I'm just waiting for some builds to finish to confirm

**Comment by primeos** [comment]
@ivan ok, yeah I didn't want to delay #65633 I was only concerned that Chromium would become too "outdated" in the meantime, but since the minor versions don't fix many CVEs I guess your're right and we should focus on #65633 right away :)

**Pull request closed without merging**
