### PR TITLE
squashfsTools: 4.5.1 -> 4.6

### PR DESCRIPTION
**Pull request by ruuda**
###### Description of changes

* Update squashfs-tools to 4.6. [Changelog](https://github.com/plougher/squashfs-tools/releases/tag/4.6).
* I had to rebase the 4k alignment patch for this, but the conflicts were easy to resolve, only due to context changes, nothing substantial.
* I confirmed that passing `-4k-align` can still be used and produces a valid squashfs, I did not confirm whether it is actually 4k aligned.
* As far as I can tell there are no breaking changes, so I don’t think an entry in the release notes is needed.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

This is a copy of #221836 but now targeted at `staging`.

### CODE REVIEW

**Review by raphaelr — APPROVED** [review]
Tested against master, `pureref` fails because it uses a `requireFile`. The `systemd-portabled` test works as well.

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>appimage-run-tests</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>pureref</li>
  </ul>
</details>
<details>
  <summary>107 packages built:</summary>
  <ul>
    <li>Sylk</li>
    <li>altair</li>
    <li>anytype</li>
    <li>appimage-run</li>
    <li>appimagekit</li>
    <li>apptainer</li>
    <li>apptainer-overriden-nixos</li>
    <li>authy</li>
    <li>beekeeper-studio</li>
    <li>betterdiscord-installer</li>
    <li>binwalk (python310Packages.binwalk)</li>
    <li>blockbench-electron</li>
    <li>bloomrpc</li>
    <li>bootstrap-studio</li>
    <li>buttercup-desktop</li>
    <li>caprine-bin</li>
    <li>chrysalis</li>
    <li>cider</li>
    <li>cozy-drive</li>
    <li>crypto-org-wallet</li>
    <li>devdocs-desktop</li>
    <li>diffoscope</li>
    <li>diffoscopeMinimal</li>
    <li>distrobuilder</li>
    <li>dracut</li>
    <li>electron-mail</li>
    <li>electronplayer</li>
    <li>firefly-desktop</li>
    <li>flexoptix-app</li>
    <li>fluent-reader</li>
    <li>framesh</li>
    <li>freetube</li>
    <li>fspy</li>
    <li>irccloud</li>
    <li>jetbrains-toolbox</li>
    <li>jitsi-meet-electron</li>
    <li>joplin-desktop</li>
    <li>keet</li>
    <li>lbry</li>
    <li>ldtk</li>
    <li>ledger-live-desktop</li>
    <li>lens</li>
    <li>localsend</li>
    <li>logseq</li>
    <li>losslesscut-bin</li>
    <li>lunar-client</li>
    <li>lxd</li>
    <li>marktext</li>
    <li>mathpix-snipping-tool</li>
    <li>mendeley</li>
    <li>mobilecoin-wallet</li>
    <li>molotov</li>
    <li>motrix</li>
    <li>museeks</li>
    <li>mycrypto</li>
    <li>neo4j-desktop</li>
    <li>notable</li>
    <li>notion-app-enhanced</li>
    <li>nuclear</li>
    <li>octant-desktop</li>
    <li>openlens</li>
    <li>osu-lazer-bin</li>
    <li>p3x-onenote</li>
    <li>passky-desktop</li>
    <li>pcloud</li>
    <li>plexamp</li>
    <li>polypane</li>
    <li>protonup-qt</li>
    <li>python310Packages.binwalk-full</li>
    <li>python311Packages.binwalk</li>
    <li>python311Packages.binwalk-full</li>
    <li>radicle-upstream</li>
    <li>rambox</li>
    <li>raven-reader</li>
    <li>remnote</li>
    <li>ripcord</li>
    <li>saleae-logic-2</li>
    <li>session-desktop</li>
    <li>singularity</li>
    <li>singularity-overriden-nixos</li>
    <li>sonixd</li>
    <li>soulseekqt</li>
    <li>spotify</li>
    <li>spotifywm</li>
    <li>squashfsTools</li>
    <li>ssb-patchwork</li>
    <li>standardnotes</li>
    <li>station</li>
    <li>steam-rom-manager</li>
    <li>super-productivity</li>
    <li>termius</li>
    <li>timeular</li>
    <li>todoist-electron</li>
    <li>trezor-suite</li>
    <li>tusk</li>
    <li>udocker</li>
    <li>uhk-agent</li>
    <li>uhk-udev-rules</li>
    <li>unityhub</li>
    <li>via</li>
    <li>vial</li>
    <li>wootility</li>
    <li>youtube-music</li>
    <li>ytmdesktop</li>
    <li>zecwallet-lite</li>
    <li>zettlr</li>
    <li>zulip</li>
  </ul>
</details>

**Comment by ruuda** [comment]
https://github.com/plougher/squashfs-tools/releases/tag/4.6.1 has been released already, I’ll add it to this PR shortly.

**Comment by ajs124** [comment]
does this actually need to go through staging? seems like it's <500 rebuilds, so it can probably go straight to master.

**Comment by ruuda** [comment]
Hmm, I asked @arianvp previously and he thought it would be better to target staging, but I can retarget it to master if you like. Is there a clear threshold for how many rebuilds is too much for master?

**Comment by vcunat** [comment]
The `darwin.patch` no longer applies.

**Comment by ruuda** [comment]
It was fixed in https://github.com/NixOS/nixpkgs/pull/228584.

**Pull request merged**
