### PR TITLE
vcv-rack: 0.6.2b -> 1.1.3

### PR DESCRIPTION
**Pull request by Moredread**
###### Motivation for this change

Version bump.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Moredread** [comment]
Mhh, it looks like some binary cpre plugins aren't loading/available. Marking this PR WIP for now.

Maybe we should try to build the core plugins ourselfs instead of relaying on the binary version.

**Comment by Moredread** [comment]
OK, I missed that we need to copy `Core.json` now so that that plugin is recognized. Users still need to get the Fundamental plugin from the store, but everything else works as normal.

**Comment by mmilata** [comment]
Seems to be working fine, thanks!

**Comment by Moredread** [comment]
I've added a comment for the glfw patch.

**Comment by jpotier** [comment]
Add to my overlay as-is, working fine!

**Comment by Moredread** [comment]
I've updated the PR to 1.1.3.

**Comment by Moredread** [comment]
@jpotier @mmilata Do you want to have a look again? I would be very grateful. :)

**Comment by jpotier** [comment]
I have updated this in my overlay *verbatim*, and it still runs great!

**Comment by mmilata** [comment]
Builds & runs without problems!

**Comment by Lassulus** [comment]
tested with nix-review, created an account, added some extra "instruments". everything worked finde

**Pull request merged**
