### PR TITLE
libinput: 1.9.4 -> 1.10.0

### PR DESCRIPTION
**Pull request by ryantm**
Semi-automatic update. These checks were performed:

- built on NixOS
- ran `/nix/store/zx5s9rsk3jh7n9vlx7824chzd54fw3nd-libinput-1.10.0/bin/libinput -h` got 0 exit code
- ran `/nix/store/zx5s9rsk3jh7n9vlx7824chzd54fw3nd-libinput-1.10.0/bin/libinput --help` got 0 exit code
- ran `/nix/store/zx5s9rsk3jh7n9vlx7824chzd54fw3nd-libinput-1.10.0/bin/libinput --version` and found version 1.10.0
- found 1.10.0 with grep in /nix/store/zx5s9rsk3jh7n9vlx7824chzd54fw3nd-libinput-1.10.0
- found 1.10.0 in filename of file in /nix/store/zx5s9rsk3jh7n9vlx7824chzd54fw3nd-libinput-1.10.0

cc "@codyopel @wkennington"

### CODE REVIEW

**Comment by jtojnar** [comment]
Changelog: https://lists.freedesktop.org/archives/wayland-devel/2018-February/036957.html

**Comment by obadz** [comment]
Either Github is confused, or I am confused. There seems to be 27 commits associated with this PR. I don't see an obvious link between them so I'm assuming this is a mistake. I will push the original commit by hand to staging.

**Comment by jtojnar** [comment]
@obadz This branch was based on master but is targetted to staging. The 26 commits are commits that are not on staging.

**Comment by obadz** [comment]
@jtojnar, ah thanks. I'm glad I just pushed the one to staging then. cheers.

**Pull request closed without merging**
