### PR TITLE
bring back `rubyLibs`, as people are still using it.

### PR DESCRIPTION
**Pull request by cstrahan**

### CODE REVIEW

**Comment by offlinehacker** [comment]
Do you know any solution how could we migrate this to some other better solution in a long run?

**Comment by cstrahan** [comment]
@offlinehacker I'm not sure I follow. Are you asking how to keep the `rubyLibs` approach - while cleaning up the code - in tandem with the Bundler/Bundix/Gemfile approach from #4677?

**Comment by offlinehacker** [comment]
Yes, i'm asking what could be better alternative to current generation using "gem nix" and rubyLibs? Could be bundix used for that?

**Comment by cstrahan** [comment]
I'm proposing that people use bundix for packaging applications going forward, using a Gemfile.lock to specify the specific versions of the dependencies they need. No one expressed any interest in keeping the `rubyLibs` model of packaging for Ruby back when I was wrapping up the "pleasant ruby" PR, but if someone can provide a compelling argument for keeping it around as a first class citizen, I think it would be fairly trivial to both keep that old model of packaging *and* move it forward.

I'd really like to hear from Ruby∩NixOS developers, and know how they feel about `rubyLibs` vs the `Gemfile`-centric approach that bundix takes. Do people really *want* `rubyLibs`, or is it just that people still need time to migrate over?

Personally, I think the `rubyLibs` approach just doesn't work too well in practice. For development of a Ruby project, `Gemfiles` are the de facto way to specify dependencies. The `rubyLibs` approach can't be used during development, because the `Gemfile`/`Gemfile.lock` demand specific versions (although, I suppose we *could* offer a utility analogous to our "cabal jailbreak", allowing one to at least patch up their `Gemfile.lock` to match the versions in `rubyLibs`. Any thoughts here?). Therefore the bundix approach is necessary if we want to support developers, so I figure it might as well be "the" way.

**Comment by offlinehacker** [comment]
Bundix approach is good for developers, but what about users/developers that only use ruby packages as tools and not as libraries. For example i use compass in nodejs.

**Comment by benley** [comment]
One issue I'm still running into with the bundix approach is that it seems like it is not possible to install more than one bundix-created ruby package into an environment, because the Gemfile/Gemfile.lock files from the two of them conflict.

rubyLibs made it very cumbersome to maintain ruby-based nix packages in a tree outside of nixpkgs, but it was at least possible to do so.

**Comment by offlinehacker** [comment]
I'm also using bundix now, but i also have same problem as @benley

**Comment by copumpkin** [comment]
I'm fairly confused by the whole bundix thing as someone who just wants to use existing ruby gems for other stuff. It seems quite substantially different from all the other nix package ecosystems and I don't really see compelling reason for it to be. It doesn't seem like the common case is someone developing new ruby stuff using nix, but rather wanting nix to be a package manager and thus finding a bunch of existing ruby packages floating around pre-packaged so they don't have to worry about where they come from or what they depend on.

**Comment by aflatter** [comment]
@copumpkin From my point of view, bundix is for Ruby applications (during development and for packaging). There's quite a lot of software in the Ruby ecosystem that's not necessarily available as a gem. So basically bundix is supposed to be a wrapper around Bundler (to piggyback on its dependency management), but bundix itself should reuse nixpkgs existing buildRubyGem infrastructure. If you just want to use an existing gem, you shouldn't need bundix.

**Comment by cstrahan** [comment]
> One issue I'm still running into with the bundix approach is that it seems like it is not possible to install more than one bundix-created ruby package into an environment, because the Gemfile/Gemfile.lock files from the two of them conflict.

Interesting, I thought the `out` drvPath was the only thing to be linked in user environments... I'll have to an alternative way of handling this, but I don't have a solution in mind just yet...

**Comment by cstrahan** [comment]
> I'm fairly confused by the whole bundix thing as someone who just wants to use existing ruby gems for other stuff. It seems quite substantially different from all the other nix language ecosystems and I don't really see compelling reason for it to be. It doesn't seem like the common case is someone developing new ruby stuff using nix, but rather wanting nix to be a package manager and thus finding a bunch of existing ruby packages floating around pre-packaged so they don't have to worry about where they come from or what they depend on.

The main impetus was supporting Rails web apps, which _almost always_ depend on Bundler to automatically [`require`](http://ruby-doc.org/core-2.2.2/Kernel.html#method-i-require) all necessary gems (via [`Bundler#setup`](http://bundler.io/v1.8/bundler_setup.html)). Making Rails apps work in Nix would otherwise require patching out a lot of Bundler related stuff, and manually keeping up-to-date a huge list of `require <gem-name-here>`.

The second motivator being that Ruby libs are terrible about maintaining compatibility across minor version bumps, as well as keeping up to date with the API changes of their dependencies. Coupled with the fact that, unlike the package managers for Python/Haskell/etc, Rubygems doesn't provide any way to run tests for a given gem, so you have to either

* cross your fingers and hope that all the gem versions are compatible,
* manually checkout the source for every gem, read the README, setup the gem's special-snow-flake test environment, run the tests, install the gem, and rinse-and-repeat,
* depend on the app author to have done QA with the versions given in the Gemfile they distribute.

The last bullet point is the only sane way to ensure stuff works in the Ruby/Rails world.

So, those are my reasons. I'd _like_ to have just one static set of versions, as we have with other languages. It's just that I assume Ruby libs to be broken until proven otherwise, and I _certainly_ wouldn't trust any packaged Ruby applications to work unless they used precisely the versions the author(s) tested with. Perhaps others are more trusting than me, or perhaps I'm overly bitter, in which case I'll understand if Bundix isn't accepted as default way to package Ruby applications.

**Comment by vcunat** [comment]
Ping. This is claimed to solve a blocker issue. No comments from interested people (who know something about ruby)?

**Comment by aflatter** [comment]
@vcunat Which issue are you talking about?

**Comment by vcunat** [comment]
#6340

**Comment by aflatter** [comment]
@vcunat I unfortunately don't have the time to look into this (vacation), but I can see that a curated set of rubyLibs might be useful for packages that depend on one or more gem. With some additional effort we could run tests of these gems too. For packaging full Ruby applications, Bundix would be the way to go. Both approaches should share the same mechanism to package gems though.

**Comment by domenkozar** [comment]
Would be nice to get this back in, I need for example sass compiler that is gone now.

**Comment by zimbatm** [comment]
Closing as Bundix and the whole ruby ecosystem is now in a good shape

**Pull request closed without merging**
