### PR TITLE
knot-resolver: 3.2.1 -> 4.0.0 -> 4.1.0

### PR DESCRIPTION
**Pull request by vcunat**
https://lists.nic.cz/pipermail/knot-resolver-users/2019/000136.html

Works fine for me (as of the 4.0.0 commit), including the nixos service.  Still, I'd like to improve the service to support easy passing of sockets to http module.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] N/A Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] N/A Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after):
    * no changes in runtime dependencies
    * a few KiB changes in the package itself
- [x] N/A Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vcunat** [comment]
I don't have the nixos/* changes yet and I expect they would better be merged together, with opportunity to react... so I'm just opening PR for now in case someone wants to try 4.0.0 already.

**Comment by vcunat** [comment]
@GrahamcOfBorg build knot-resolver

**Comment by vcunat** [comment]
Well, the `nixos/*` changes don't hurry and the security fixes do, so no more waiting.  (I pushed to master myself, only GitHub mis-detects as usual.)

**Comment by ajs124** [comment]
Are the security fixes also relevant to 19.03?

**Comment by vcunat** [comment]
@ajs124: yes, they are.  I had tested [this](https://github.com/NixOS/nixpkgs/compare/release-19.03...vcunat:p/knot-majors-19.03), so you can apply that immediately in case you really hurry.  I might resolve one of the less important FIXMEs in the meantime.

**Comment by vcunat** [comment]
Backported and it got into channels, too.

**Comment by ajs124** [comment]
Nice, thanks!

**Pull request merged**
