### PR TITLE
python312Packages.pgvector: 0.2.4 -> 0.3.2; postgresql16Packages.pgvector: 0.6.2 -> 0.7.4

### PR DESCRIPTION
**Pull request by natsukium**
## Description of changes

Diff: https://github.com/pgvector/pgvector-python/compare/refs/tags/v0.2.4...v0.3.2
Changelog: https://github.com/pgvector/pgvector-python/blob/refs/tags/v0.3.2/CHANGELOG.md

Diff: https://github.com/pgvector/pgvector/compare/v0.6.2...v0.7.4
Changelog: https://github.com/pgvector/pgvector/raw/v0.7.4/CHANGELOG.md

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [x] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 336456` at 05238c96 run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>khoj</li>
    <li>python311Packages.llama-index-vector-stores-postgres</li>
    <li>python311Packages.private-gpt</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/natsukium/ec23202b4ced915b20a3fe8cee471b0f">python311Packages.pgvector</a></li>
    <li><a href="https://gist.github.com/natsukium/c9a9d561ac6b4d57130b0ada32222683">python312Packages.pgvector</a></li>
  </ul>
</details>
<details>
  <summary>10 packages built successfully:</summary>
  <ul>
    <li>postgresql12JitPackages.pgvector</li>
    <li>postgresql12Packages.pgvector</li>
    <li>postgresql13JitPackages.pgvector</li>
    <li>postgresql13Packages.pgvector</li>
    <li>postgresql14JitPackages.pgvector</li>
    <li>postgresql14Packages.pgvector</li>
    <li>postgresql15JitPackages.pgvector</li>
    <li>postgresql15Packages.pgvector</li>
    <li>postgresql16JitPackages.pgvector</li>
    <li>postgresql16Packages.pgvector</li>
  </ul>
</details>

**Comment by kirillrdy** [comment]
Result of `nixpkgs-review pr 336456` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>python311Packages.private-gpt</li>
    <li>python311Packages.private-gpt.dist</li>
  </ul>
</details>
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>python311Packages.llama-index-vector-stores-postgres</li>
    <li>python311Packages.llama-index-vector-stores-postgres.dist</li>
    <li>python311Packages.pgvector</li>
    <li>python311Packages.pgvector.dist</li>
    <li>python312Packages.pgvector</li>
    <li>python312Packages.pgvector.dist</li>
  </ul>
</details>
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>postgresql12JitPackages.pgvector</li>
    <li>postgresql12Packages.pgvector</li>
    <li>postgresql13JitPackages.pgvector</li>
    <li>postgresql13Packages.pgvector</li>
    <li>postgresql14JitPackages.pgvector</li>
    <li>postgresql14Packages.pgvector</li>
    <li>postgresql15JitPackages.pgvector</li>
    <li>postgresql15Packages.pgvector</li>
    <li>postgresqlJitPackages.pgvector (postgresql16JitPackages.pgvector)</li>
    <li>postgresqlPackages.pgvector (postgresql16Packages.pgvector)</li>
  </ul>
</details>

**Comment by natsukium** [comment]
I disabled the test on darwin as it fails to start postgresql in the sandbox.
I will look into the reason for the failure of aarch64-linux and llama-index.

**Comment by kirillrdy** [comment]
@natsukium btw I got postgres running in darwin sandbox https://github.com/NixOS/nix/pull/10878

but not sure when nixpkgs infra will use newer nix

**Comment by wegank** [comment]
Done in #352153 and #356283.

**Pull request closed without merging**
