### PR TITLE
kcachegrind: init at 16.2.2

### PR DESCRIPTION
**Pull request by orivej**
###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by periklis** [comment]
fyi, i am working on a similar PR for qcachegrind to make it available for macos users too.

**Review by vcunat — APPROVED** [review]
Seems to work OK; probably the same version as old `kde4.kcachegrind` but built against newer libs.

**Comment by vcunat** [comment]
For reference, also picked to 17.03.

**Comment by orivej** [comment]
Thanks!
@periklis You may add me to the pull request and as a maintainer of qcachegrind.

**Pull request merged**
