### PR TITLE
nixUnstable: pre20220127 -> pre20220207

### LINKED ISSUE #5985: Interrupting Nix during a download causes it to hang
**Describe the bug**

If Nix gets interrupted while something is being downloaded, it will output `error (ignored): basic_string::_M_construct null not valid` and hang until SIGKILL-ed.

**Steps To Reproduce**

```console
$ nix build nixpkgs\#firefox --store $PWD&
$ sleep 2 # Just to make sure that it’s properly started
$ kill %nix
error (ignored): basic_string::_M_construct null not valid
# Nix is now stuck until
$ kill -9 %nix
```

**Expected behavior**

Should properly stop

**`nix-env --version` output**

```console
$ nix-env --version 
nix-env (Nix) 2.6.0
```

**Additional context**

Wasn’t present on `2.6.0pre20211214_18e4851` (but I didn’t bisect it any further)

### PR DESCRIPTION
**Pull request by NickCao**
###### Motivation for this change
fixes https://github.com/NixOS/nix/issues/5985

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NickCao** [comment]
this breaks `hydra-unstable` due to recent changes.

**Comment by NickCao** [comment]
I did figure out a patch: https://github.com/NickCao/nixpkgs/commit/a89e6083b2a32c2527965457e038acf5158279ff , and have being running with it on my hydra for days without problems, still need someone familiar with hydra-eval-jobs to review it. Pinning nix to nixVersions.stable is not a viable fix as restricted evaluation is broken on nix 2.6.0.

**Comment by L-as** [comment]
Do note that this also fixes https://github.com/NixOS/nix/pull/6036

**Comment by Artturin** [comment]
@ofborg build hydra-unstable

**Comment by NickCao** [comment]
I'm not in favor of blocking this indefinitely. as these bugs fixed are critical to our users. If nobody objects the hydra patch, shall we just merge this.

**Comment by NickCao** [comment]
> Let's merge, please submit the patch upstream
Shall I mark hydra-unstable as broken for now?

**Comment by Artturin** [comment]
> > Let's merge, please submit the patch upstream
> 
> Shall I mark hydra-unstable as broken for now?

No, I meant let's merge and submit the patch upstream

**Comment by NickCao** [comment]
Currently hydra's policy is to support the stable version of nix, upstream pr has no where to target until hydra have a staging branch for us.

**Pull request merged**
