### PR TITLE
dockertools: Update doc to use CommonMark

### LINKED ISSUE #105759: Convert dockertools from Docbook to CommonMark
This issue tracks the conversion of `/doc/builders/images/dockertools.xml` from Docbook to CommonMark per [RFC 72](https://github.com/NixOS/rfcs/blob/master/rfcs/0072-commonmark-docs.md).

If you intend to work on this conversion, please comment below!

# Conversion instructions

1. Comment here that you intend to work on it. (Please also post if you stop working on it.)
2. Checkout a new branch of nixpkgs master.
3. Edit `doc/builders/images.xml`: change `dockertools.xml` to `dockertools.section.xml`.
4. Rename `doc/builders/images/dockertools.xml` to `dockertools.section.md`.
5. Convert the contents from Docbook to [CommonMark](https://commonmark.org/). Follow [conversion best practices](https://github.com/NixOS/nixpkgs/issues/105243). Use existing `.md` sections for inspiration.
6. Use `nix-build` from the `doc/` folder to build the manual.
7. Preview the manual on your computer at `http://0.0.0.0:8000/manual.html` after running from `doc/` folder:
  ```
  nix-shell -p python3 --run 'python3 -m http.server --directory ./result/share/doc/nixpkgs'
  ```
8. When it looks good, submit a PR and reference this issue.

### PR DESCRIPTION
**Pull request by bryanasdev000**
###### Motivation for this change

Closes #105759.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bryanasdev000** [comment]
For now this PR have two problems, already described here https://github.com/NixOS/nixpkgs/issues/105759#issuecomment-757419599.

**Comment by roberth** [comment]
It seems like the anchors are missing. I don't know what's the right way to create the anchors for the examples, but perhaps we can insert docbook syntax for it, similar to [HTML](https://stackoverflow.com/a/7335259/428586).

I couldn't find anything about the `{anchor}` syntax suggested for headers [here](https://github.com/NixOS/nixpkgs/issues/105243) in the [spec](https://spec.commonmark.org/0.29) either.

@ryantm what's the best way to create anchors for examples?

> ```
> ...
> warning: failed to load external entity "functions/library/generated/overrides/lib.options.showOption.xml"
> jing doc-support/result/docbook.rng manual-full.xml
> /build/doc/manual-full.xml:13148:59: error: IDREF "ex-dockerTools-buildImage-runAsRoot" without matching ID
> /build/doc/manual-full.xml:12728:49: error: IDREF "ex-dockerTools-buildImage" without matching ID
> make: *** [Makefile:29: validate] Error 1
> builder for '/nix/store/yajds5xax6hjdjdqm4y23xvkvhpbr36r-nixpkgs-manual.drv' failed with exit code 2
> error: build of '/nix/store/yajds5xax6hjdjdqm4y23xvkvhpbr36r-nixpkgs-manual.drv' failed
> ```
> 
> For this I tried `(see <xref linkend="ex-dockerTools-buildImage"/>)` per #105243 but build fails with same error.
> 
> Any help is appreciated.

**Comment by ryantm** [comment]
@roberth We are using Pandoc's Bracketed Spans extension. It seems like it has decent popular support on the CommonMark forums: https://talk.commonmark.org.

You can add an anchor anywhere with `[]{#anchor-id}`, which we are doing in the GNOME section currently.

**Comment by bryanasdev000** [comment]
> It seems like the anchors are missing. I don't know what's the right way to create the anchors for the examples, but perhaps we can insert docbook syntax for it, similar to [HTML](https://stackoverflow.com/a/7335259/428586).
> 
> I couldn't find anything about the `{anchor}` syntax suggested for headers [here](https://github.com/NixOS/nixpkgs/issues/105243) in the [spec](https://spec.commonmark.org/0.29) either.
> 
> @ryantm what's the best way to create anchors for examples?
> 
> > ```
> > ...
> > warning: failed to load external entity "functions/library/generated/overrides/lib.options.showOption.xml"
> > jing doc-support/result/docbook.rng manual-full.xml
> > /build/doc/manual-full.xml:13148:59: error: IDREF "ex-dockerTools-buildImage-runAsRoot" without matching ID
> > /build/doc/manual-full.xml:12728:49: error: IDREF "ex-dockerTools-buildImage" without matching ID
> > make: *** [Makefile:29: validate] Error 1
> > builder for '/nix/store/yajds5xax6hjdjdqm4y23xvkvhpbr36r-nixpkgs-manual.drv' failed with exit code 2
> > error: build of '/nix/store/yajds5xax6hjdjdqm4y23xvkvhpbr36r-nixpkgs-manual.drv' failed
> > ```
> > 
> > 
> > For this I tried `(see <xref linkend="ex-dockerTools-buildImage"/>)` per #105243 but build fails with same error.
> > Any help is appreciated.



> @roberth We are using Pandoc's Bracketed Spans extension. It seems like it has decent popular support on the CommonMark forums: https://talk.commonmark.org.
> 
> You can add an anchor anywhere with `[]{#anchor-id}`, which we are doing in the GNOME section currently.

Will try, this is the same case for ocitools and snaptools.

**Comment by bryanasdev000** [comment]
Guys, sorry for taking so long.

**Review by roberth — APPROVED** [review]
Rebased and fixed two labels. Looks good!

**Comment by roberth** [comment]
Thanks @bryanasdev000 !

**Pull request merged**
