### PR TITLE
cryptominisat: 5.0.1 -> 5.6.6

### PR DESCRIPTION
**Pull request by Mic92**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build cryptominisat

**Comment by Mic92** [comment]
I mainly used the library. Now it builds with boost.

**Comment by xeji** [comment]
Did the darwin build already fail before you added boost?

**Comment by Mic92** [comment]
I don't remember. Looking at the error most likely.

**Comment by Mic92** [comment]
@GrahamcOfBorg build cryptominisat

Without a macOS vm this is hard to debug. I could remove python from buildInputs though on macOS.

**Comment by xeji** [comment]
looks fine now.

**Comment by Mic92** [comment]
@GrahamcOfBorg build cryptominisat

**Pull request merged**
