### PR TITLE
Update packages from libimobiledevice repository

### PR DESCRIPTION
**Pull request by tjni**
###### Description of changes

In addition:

1. Specify version in preAutoreconf instead of postPatch. I think it reads clearer.
2. Enable function that can toggle debug output using "--enable-debug". This is the default in upstream's release process (per their GitHub workflow).
3. Enable tests.
4. Add mainProgram attribute so that `nix run nixpkgs#libplist` works.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 236033` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>36 packages marked as broken and skipped:</summary>
  <ul>
    <li>almanah</li>
    <li>gnome-recipes</li>
    <li>gnome.gnome-music</li>
    <li>gnome.gvfs</li>
    <li>gnome2.gvfs</li>
    <li>grilo-plugins</li>
    <li>kodiPackages.inputstream-adaptive</li>
    <li>kodiPackages.inputstream-ffmpegdirect</li>
    <li>kodiPackages.inputstream-rtmp</li>
    <li>kodiPackages.joystick</li>
    <li>kodiPackages.libretro</li>
    <li>kodiPackages.libretro-genplus</li>
    <li>kodiPackages.libretro-mgba</li>
    <li>kodiPackages.libretro-snes9x</li>
    <li>kodiPackages.pvr-hdhomerun</li>
    <li>kodiPackages.pvr-hts</li>
    <li>kodiPackages.pvr-iptvsimple</li>
    <li>kodiPackages.steam-controller</li>
    <li>kodiPackages.vfs-libarchive</li>
    <li>kodiPackages.vfs-sftp</li>
    <li>kodiPackages.visualization-fishbmc</li>
    <li>kodiPackages.visualization-goom</li>
    <li>kodiPackages.visualization-matrix</li>
    <li>kodiPackages.visualization-pictureit</li>
    <li>kodiPackages.visualization-projectm</li>
    <li>kodiPackages.visualization-shadertoy</li>
    <li>kodiPackages.visualization-spectrum</li>
    <li>kodiPackages.visualization-starburst</li>
    <li>kodiPackages.visualization-waveform</li>
    <li>mate.mate-power-manager</li>
    <li>mojave-gtk-theme</li>
    <li>rpiplay</li>
    <li>vimix-gtk-themes</li>
    <li>waybar</li>
    <li>whitesur-gtk-theme</li>
    <li>xfce.xfce4-weather-plugin</li>
  </ul>
</details>
<details>
  <summary>22 packages failed to build:</summary>
  <ul>
    <li>evolution-data-server (gnome.evolution-data-server)</li>
    <li>evolution-data-server-gtk4</li>
    <li>evolution-data-server-gtk4.dev</li>
    <li>evolution-data-server.dev (gnome.evolution-data-server.dev)</li>
    <li>folks</li>
    <li>folks.dev</li>
    <li>folks.devdoc</li>
    <li>gnome-online-accounts</li>
    <li>gnome-online-accounts.dev</li>
    <li>gnome.gnome-calendar</li>
    <li>gvfs</li>
    <li>ideviceinstaller</li>
    <li>idevicerestore</li>
    <li>ifuse</li>
    <li>libimobiledevice</li>
    <li>libimobiledevice-glue</li>
    <li>libimobiledevice-glue.dev</li>
    <li>libimobiledevice.dev</li>
    <li>libirecovery</li>
    <li>libirecovery.dev</li>
    <li>libusbmuxd</li>
    <li>usbmuxd</li>
  </ul>
</details>
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>ldid</li>
    <li>libplist</li>
    <li>libplist.bin</li>
    <li>libplist.dev</li>
    <li>uxplay</li>
  </ul>
</details>

**Comment by dani0854** [comment]
I also have a similar PR #235806, but was building on x86_64-linux. There are approximately 250 rebuilds, and it takes forever to check if everything builds correctly. Only managed to build 30 packages in 10 hours, 5 of which failed(( Asked on discourse, waiting on answer.

<details><summary>Failed dependencies</summary>
    <pre>
error: builder for '/nix/store/p86hcxyzpiw1x414n1ji5qxagrmilrij-idevicerestore-1.0.0+date=2022-05-22.drv' failed with exit code 2;
       last 10 log lines:
       >  1075 |         SHA1_Final(tsha1, &sha1ctx);
       >       |         ^~~~~~~~~~
       > /nix/store/80rbkkz1jh3ybsc5r4dz2bmn02vljn1c-openssl-3.0.8-dev/include/openssl/sha.h:51:27: note: declared here
       >    51 | OSSL_DEPRECATEDIN_3_0 int SHA1_Final(unsigned char *md, SHA_CTX *c);
       >       |                           ^~~~~~~~~~
       > make[2]: *** [Makefile:660: idevicerestore-ipsw.o] Error 1
       > make[2]: Leaving directory '/build/source/src'
       > make[1]: *** [Makefile:431: all-recursive] Error 1
       > make[1]: Leaving directory '/build/source'
       > make: *** [Makefile:363: all] Error 2
       For full logs, run 'nix log /nix/store/p86hcxyzpiw1x414n1ji5qxagrmilrij-idevicerestore-1.0.0+date=2022-05-22.drv'.
error: builder for '/nix/store/aap2cg1zdf49147vdqc9l59c2ibm89m4-libgpod-0.8.3.drv' failed with exit code 2;
       last 10 log lines:
       > /build/libgpod-0.8.3/tools/ipod-lockdown.c:103: undefined reference to `plist_dict_insert_item'
       > /nix/store/shw0b6wv2xdvyj71b1fj147i83awrqfz-binutils-2.40/bin/ld: /build/libgpod-0.8.3/tools/ipod-lockdown.c:115: undefined reference to `plist_dict_insert_item'
       > /nix/store/shw0b6wv2xdvyj71b1fj147i83awrqfz-binutils-2.40/bin/ld: /build/libgpod-0.8.3/tools/ipod-lockdown.c:120: undefined reference to `plist_dict_insert_item'
       > /nix/store/shw0b6wv2xdvyj71b1fj147i83awrqfz-binutils-2.40/bin/ld: /build/libgpod-0.8.3/tools/ipod-lockdown.c:123: undefined reference to `plist_dict_insert_item'
       > collect2: error: ld returned 1 exit status
       > make[2]: *** [Makefile:844: ipod-read-sysinfo-extended] Error 1
       > make[2]: Leaving directory '/build/libgpod-0.8.3/tools'
       > make[1]: *** [Makefile:571: all-recursive] Error 1
       > make[1]: Leaving directory '/build/libgpod-0.8.3'
       > make: *** [Makefile:480: all] Error 2
       For full logs, run 'nix log /nix/store/aap2cg1zdf49147vdqc9l59c2ibm89m4-libgpod-0.8.3.drv'.
error: 1 dependencies of derivation '/nix/store/9xga6xhw5jahf8333ihlnm6ndjjmhyk7-gtkpod-2.1.5.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1bh2m2lm768i6701fqcwsikdsi3i32dj-rhythmbox-3.4.7.drv' failed to build
error: 1 dependencies of derivation '/nix/store/455radijwppc3ammqdkxlj9li2syizql-strawberry-1.0.17.drv' failed to build
error: builder for '/nix/store/afmhpw308nw5rpjirqxp6slcp4bbhzg1-usbmuxd-1.1.1+date=2022-04-04.drv' failed with exit code 2;
       last 10 log lines:
       > /build/source/src/conf.c:235: undefined reference to `plist_read_from_filename'
       > /nix/store/shw0b6wv2xdvyj71b1fj147i83awrqfz-binutils-2.40/bin/ld: /build/source/src/conf.c:259: undefined reference to `plist_write_to_filename'
       > /nix/store/shw0b6wv2xdvyj71b1fj147i83awrqfz-binutils-2.40/bin/ld: usbmuxd-conf.o: in function `config_set_device_record':
       > /build/source/src/conf.c:433: undefined reference to `plist_write_to_filename'
       > collect2: error: ld returned 1 exit status
       > make[2]: *** [Makefile:438: usbmuxd] Error 1
       > make[2]: Leaving directory '/build/source/src'
       > make[1]: *** [Makefile:426: all-recursive] Error 1
       > make[1]: Leaving directory '/build/source'
       > make: *** [Makefile:358: all] Error 2
       For full logs, run 'nix log /nix/store/afmhpw308nw5rpjirqxp6slcp4bbhzg1-usbmuxd-1.1.1+date=2022-04-04.drv'.
error: 1 dependencies of derivation '/nix/store/vnl4ca63pa3vivrihga3566crvcdvnkz-ideviceinstaller-1.1.1+date=2022-05-09.drv' failed to build
error: 1 dependencies of derivation '/nix/store/8xqwh8gdrsq35zv257hi53s0zhclbvrm-ifuse-1.1.4+date=2022-04-04.drv' failed to build
error: 1 dependencies of derivation '/nix/store/wjg11n0pylhnfbpmlphx6k9212s8sr5d-rapid-photo-downloader-0.9.34.drv' failed to build
error: builder for '/nix/store/w53gy6j16gqhcpnfdwwi0r3j8ljf5g8b-usbmuxd2-unstable-2022-02-07.drv' failed with exit code 2;
       last 10 log lines:
       >                     ^~~~~~~~~~~~~~~~~
       > /nix/store/5kg8q5vwsql7fi7yidsp8p2vcsyfy96i-libplist-2.3.0-dev/include/plist/plist.h:828:17: note: candidate function not viable: requires 4 arguments, but 3 were provided
       >     plist_err_t plist_from_memory(const char *plist_data, uint32_t length, plist_t *plist, plist_format_t *format);
       >                 ^
       > 1 error generated.
       > make[2]: *** [Makefile:638: usbmuxd-Client.o] Error 1
       > make[2]: Leaving directory '/build/source/usbmuxd2'
       > make[1]: *** [Makefile:433: all-recursive] Error 1
       > make[1]: Leaving directory '/build/source'
       > make: *** [Makefile:365: all] Error 2
       For full logs, run 'nix log /nix/store/w53gy6j16gqhcpnfdwwi0r3j8ljf5g8b-usbmuxd2-unstable-2022-02-07.drv'
    </pre>
</details>

I also switched gnutls to openssl in libimobiledevice, reasons for which I explained in my PR. So if you merge first, it will save me a lot of time)) Since by current estimates it can take up to week to rebuild all on my laptop (probably need to setup a build server). I will just rebase OpenSSL change on top of updates.

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 236033` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>46 packages marked as broken and skipped:</summary>
  <ul>
    <li>almanah</li>
    <li>evolution-data-server</li>
    <li>evolution-data-server-gtk4</li>
    <li>evolution-data-server-gtk4.dev</li>
    <li>evolution-data-server.dev</li>
    <li>folks</li>
    <li>folks.dev</li>
    <li>folks.devdoc</li>
    <li>gnome-recipes</li>
    <li>gnome.evolution-data-server</li>
    <li>gnome.evolution-data-server.dev</li>
    <li>gnome.gnome-calendar</li>
    <li>gnome.gnome-music</li>
    <li>gnome.gvfs</li>
    <li>gnome2.gvfs</li>
    <li>grilo-plugins</li>
    <li>kodiPackages.inputstream-adaptive</li>
    <li>kodiPackages.inputstream-ffmpegdirect</li>
    <li>kodiPackages.inputstream-rtmp</li>
    <li>kodiPackages.joystick</li>
    <li>kodiPackages.libretro</li>
    <li>kodiPackages.libretro-genplus</li>
    <li>kodiPackages.libretro-mgba</li>
    <li>kodiPackages.libretro-snes9x</li>
    <li>kodiPackages.pvr-hdhomerun</li>
    <li>kodiPackages.pvr-hts</li>
    <li>kodiPackages.pvr-iptvsimple</li>
    <li>kodiPackages.steam-controller</li>
    <li>kodiPackages.vfs-libarchive</li>
    <li>kodiPackages.vfs-sftp</li>
    <li>kodiPackages.visualization-fishbmc</li>
    <li>kodiPackages.visualization-goom</li>
    <li>kodiPackages.visualization-matrix</li>
    <li>kodiPackages.visualization-pictureit</li>
    <li>kodiPackages.visualization-projectm</li>
    <li>kodiPackages.visualization-shadertoy</li>
    <li>kodiPackages.visualization-spectrum</li>
    <li>kodiPackages.visualization-starburst</li>
    <li>kodiPackages.visualization-waveform</li>
    <li>mate.mate-power-manager</li>
    <li>mojave-gtk-theme</li>
    <li>rpiplay</li>
    <li>vimix-gtk-themes</li>
    <li>waybar</li>
    <li>whitesur-gtk-theme</li>
    <li>xfce.xfce4-weather-plugin</li>
  </ul>
</details>
<details>
  <summary>19 packages built:</summary>
  <ul>
    <li>gnome-online-accounts</li>
    <li>gnome-online-accounts.dev</li>
    <li>gvfs</li>
    <li>ideviceinstaller</li>
    <li>idevicerestore</li>
    <li>ifuse</li>
    <li>ldid</li>
    <li>libimobiledevice</li>
    <li>libimobiledevice-glue</li>
    <li>libimobiledevice-glue.dev</li>
    <li>libimobiledevice.dev</li>
    <li>libirecovery</li>
    <li>libirecovery.dev</li>
    <li>libplist</li>
    <li>libplist.bin</li>
    <li>libplist.dev</li>
    <li>libusbmuxd</li>
    <li>usbmuxd</li>
    <li>uxplay</li>
  </ul>
</details>

**Comment by wegank** [comment]
I've got 243 packages built on `x86_64-linux`, with the following regressions:

- ios-webkit-debug-proxy (ios-webkit-debug-proxy.dev)
- usbmuxd2
- libgpod (libgpod.dev, gtkpod, rhythmbox, strawberry)

**Comment by tjni** [comment]
Thank you for your help building everything so far. I still need to set up `darwin.builder` properly so that I can build on Linux and will try to do that soon.

**Comment by dani0854** [comment]
Any progress?

**Review by abustany — COMMENTED** [review]
`ios-webkit-debug-proxy` changes look good to me :+1: I can't really comment on the other changes, I don't think they affect the debug proxy.

**Comment by tjni** [comment]
I finally investigated the failures on Linux and fixed them, so this is ready for a review again. Thank you for your patience.

**Comment by wegank** [comment]
```
4 packages marked as broken and skipped:
gnomeExtensions.easyScreenCast mailnagWithPlugins mailnagWithPlugins.dist xmonad_log_applet

254 packages built:
adapta-gtk-theme almanah bubblemail bubblemail.dist budgie.budgie-control-center budgie.budgie-control-center.debug budgie.budgie-desktop budgie.budgie-desktop-with-plugins budgie.budgie-gsettings-ov
errides budgiePlugins.budgie-analogue-clock-applet budgiePlugins.budgie-user-indicator-redux calls calls.devdoc chatty cinnamon.cinnamon-common cinnamon.cinnamon-control-center cinnamon.cinnamon-gset
tings-overrides cinnamon.cinnamon-screensaver cinnamon.cinnamon-session cinnamon.cinnamon-settings-daemon cinnamon.cinnamon-settings-daemon.dev cinnamon.nemo cinnamon.nemo-fileroller cinnamon.nemo-py
thon cinnamon.nemo-with-extensions cinnamon.nemo.dev clementine clight droidcam dropbox-cli dropbox-cli.nautilusExtension eiciel eiciel.nautilusExtension endeavour eolie evolution evolution-data-serv
er evolution-data-server-gtk4 evolution-data-server-gtk4.dev evolution-data-server.dev evolution-ews evolutionWithPlugins folks folks.dev folks.devdoc gfbgraph gfbgraph.dev gfbgraph.devdoc gnome-brow
ser-connector gnome-inform7 gnome-online-accounts gnome-online-accounts.debug gnome-online-accounts.dev gnome-online-accounts.devdoc gnome-online-accounts.man gnome-photos gnome-photos.installedTests
 gnome-recipes gnome.cheese gnome.cheese.devdoc gnome.cheese.man gnome.file-roller gnome.geary gnome.gnome-applets gnome.gnome-bluetooth gnome.gnome-bluetooth.dev gnome.gnome-bluetooth.devdoc gnome.g
nome-bluetooth.man gnome.gnome-calendar gnome.gnome-contacts gnome.gnome-control-center gnome.gnome-control-center.debug gnome.gnome-disk-utility gnome.gnome-flashback gnome.gnome-initial-setup gnome
.gnome-music gnome.gnome-notes gnome.gnome-online-miners gnome.gnome-panel gnome.gnome-panel.dev gnome.gnome-panel.man gnome.gnome-power-manager gnome.gnome-session gnome.gnome-session.debug gnome.gn
ome-session.sessions gnome.gnome-settings-daemon gnome.gnome-settings-daemon43 gnome.gnome-shell gnome.gnome-shell.debug gnome.gnome-shell.devdoc gnome.gnome-terminal gnome.gnome-tweaks gnome.gpaste
gnome.gvfs gnome.gvfs.debug gnome.mutter gnome.mutter.debug gnome.mutter.dev gnome.mutter.devdoc gnome.mutter.man gnome.mutter43 gnome.mutter43.debug gnome.mutter43.dev gnome.mutter43.devdoc gnome.mu
tter43.man gnome.nautilus gnome.nautilus-python gnome.nautilus-python.dev gnome.nautilus-python.devdoc gnome.nautilus-python.doc gnome.nautilus.dev gnome.nautilus.devdoc gnome.nixos-gsettings-overrid
es gnome.totem gnomeExtensions.gsconnect gnomeExtensions.gsconnect.installedTests gnomeExtensions.gtk4-desktop-icons-ng-ding gnomeExtensions.system-monitor grilo-plugins gtkpod gvfs gvfs.debug idevic
einstaller idevicerestore ifuse ios-webkit-debug-proxy ios-webkit-debug-proxy.dev kodi kodi-gbm kodi-wayland kodiPackages.a4ksubtitles kodiPackages.archive_tool kodiPackages.iagl kodiPackages.inputst
ream-adaptive kodiPackages.inputstream-ffmpegdirect kodiPackages.inputstream-rtmp kodiPackages.invidious kodiPackages.joystick kodiPackages.kodi-platform kodiPackages.libretro kodiPackages.libretro-2
048 kodiPackages.libretro-fuse kodiPackages.libretro-genplus kodiPackages.libretro-mgba kodiPackages.libretro-snes9x kodiPackages.netflix kodiPackages.pvr-hdhomerun kodiPackages.pvr-hts kodiPackages.
pvr-iptvsimple kodiPackages.steam-controller kodiPackages.vfs-libarchive kodiPackages.vfs-rar kodiPackages.vfs-sftp kodiPackages.visualization-fishbmc kodiPackages.visualization-goom kodiPackages.vis
ualization-matrix kodiPackages.visualization-pictureit kodiPackages.visualization-projectm kodiPackages.visualization-shadertoy kodiPackages.visualization-spectrum kodiPackages.visualization-starburs
t kodiPackages.visualization-waveform ldid libgdata libgdata.dev libgdata.installedTests libgpod libgpod.dev libimobiledevice libimobiledevice-glue libimobiledevice-glue.dev libimobiledevice.dev libi
recovery libirecovery.dev libplist libplist.bin libplist.dev libusbmuxd libzapojit libzapojit.dev mate.mate-applets mate.mate-power-manager mate.mate-tweak mate.mate-tweak.dist mixxx mojave-gtk-theme
 monitor nautilus-open-any-terminal nautilus-open-any-terminal.dist obs-studio-plugins.droidcam-obs pantheon.elementary-calendar pantheon.elementary-greeter pantheon.elementary-gsettings-schemas pant
heon.elementary-mail pantheon.elementary-session-settings pantheon.elementary-tasks pantheon.file-roller-contract pantheon.gala pantheon.switchboard-plug-a11y pantheon.switchboard-plug-bluetooth pant
heon.switchboard-plug-keyboard pantheon.switchboard-plug-mouse-touchpad pantheon.switchboard-plug-onlineaccounts pantheon.switchboard-plug-pantheon-shell pantheon.switchboard-plug-power pantheon.swit
chboard-plug-security-privacy pantheon.switchboard-with-plugs pantheon.wingpanel pantheon.wingpanel-applications-menu pantheon.wingpanel-indicator-a11y pantheon.wingpanel-indicator-bluetooth pantheon
.wingpanel-indicator-datetime pantheon.wingpanel-indicator-keyboard pantheon.wingpanel-indicator-network pantheon.wingpanel-indicator-nightlight pantheon.wingpanel-indicator-notifications pantheon.wi
ngpanel-indicator-power pantheon.wingpanel-indicator-session pantheon.wingpanel-indicator-sound pantheon.wingpanel-with-indicators phoc phosh phosh-mobile-settings planify power-profiles-daemon power
-profiles-daemon.devdoc rabbitvcs rabbitvcs.cli rabbitvcs.dist rapid-photo-downloader rapid-photo-downloader.dist rhythmbox rpiplay strawberry thermald thermald.devdoc tracker-miners upower upower.de
v upower.devdoc usbmuxd usbmuxd2 uxplay valent vimix-gtk-themes waybar whitesur-gtk-theme wingpanel-indicator-ayatana xdg-desktop-portal-gtk xfce.xfce4-power-manager xfce.xfce4-power-manager.dev xfce
.xfce4-settings xfce.xfce4-settings.dev xfce.xfce4-weather-plugin
```

**Review by wegank — APPROVED** [review]

**Comment by wegank** [comment]
@ofborg build uxplay

**Pull request merged**
