### PR TITLE
Staging next 2022-01-12

### PR DESCRIPTION
**Pull request by veprbl**
constitutents: https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
jobset: https://hydra.nixos.org/jobset/nixpkgs/staging-next

Previous staging-next: #152145

### CODE REVIEW

**Comment by NickCao** [comment]
meson 0.60 now calls ldconfig in installPhase, causing cross compilations to fail, which is addressed in release 0.61, we should bump to that instead.

**Comment by vcunat** [comment]
[There is](https://hydra.nixos.org/build/164090656) completely broken x86_64-darwin: https://github.com/NixOS/nixpkgs/issues/154810

**Comment by veprbl** [comment]
- [ ] python39Packages.xhtml2pdf.x86_64-linux https://hydra.nixos.org/build/164647608 (allegedly https://github.com/NixOS/nixpkgs/commit/5461824edefaca2f0f3b44c13275dad3f26f007a#commitcomment-63969200)

**Comment by ncfavier** [comment]
The update to meson 0.60 causes all builds with unknown options to fail instead of warn (see https://github.com/NixOS/nixpkgs/pull/156160) for example. Is there a way to detect all such builds automatically, for example by searching for `ERROR: Unknown options:` in all the logs of a given evaluation?

**Comment by ncfavier** [comment]
I ended up doing it manually: https://github.com/NixOS/nixpkgs/pull/156192

**Comment by vcunat** [comment]
- [ ] [darwin.text_cmds.x86_64-darwin](https://hydra.nixos.org/build/164602799), transitively breaking some other builds as well

**Comment by vcunat** [comment]
aarch64-darwin [is still](https://hydra.nixos.org/eval/1739880?compare=nixpkgs-unstable-aarch64-darwin#tabs-now-fail) a disaster; on a quick glance because of
- [ ] failing [libredirect build](https://hydra.nixos.org/build/164632819)

**Comment by vcunat** [comment]
Other than that I can't see any large problems.  The smallish remains are often python stuff, usually with
```
ERROR: No matching distribution found for typing-extensions...
```

I expect we'll want to wait a bit for aarch64-darwin to progress, too.

**Comment by mweinelt** [comment]
> Other than that I can't see any large problems. The smallish remains are often python stuff, usually with
> 
> ```
> ERROR: No matching distribution found for typing-extensions...
> ```

Probably not worth picking up, since python-unstable is already queued for the next staging-next run.

**Review by jonringer — APPROVED** [review]
LGTM

There's excess hydra capacity, start another! :)

**Comment by mweinelt** [comment]
@veprbl We are coordinating staging cycles on #staging:nixos.org on matrix, if you care to join.

https://matrix.to/#/#staging:nixos.org

**Comment by veprbl** [comment]
@mweinelt Thank you for the invitation. I did not know there was a dedicated channel devoted to staging. I would be new to matrix, will have to look into setting up an account.

**Comment by jonringer** [comment]
https://github.com/NixOS/nixpkgs/pull/156750 will be a moderate size rebuild for x86_64-linux. going to merge both

**Comment by vcunat** [comment]
And further excess Hydra capacity will be utilized by 21.11: #156696

**Comment by jonringer** [comment]
> so we should probably wait a while before starting another iteration.

agreed

**Pull request merged**
