### PR TITLE
[19.03] Mark various versions of firefox and derivatives as vulnerable

### PR DESCRIPTION
**Pull request by stefano-m**
###### Motivation for this change

Mainly because of

https://www.mozilla.org/en-US/security/advisories/mfsa2020-03/

but there are also other older and unsupported packages.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @flokli due to https://github.com/NixOS/nixpkgs/issues/77361#issuecomment-572712011

### CODE REVIEW

**Comment by worldofpeace** [comment]
I believe the iso's and vms use firefox so they won't evaluate with this. And haven't we already declared 19.03 as EOL (and subsequently possibly having security vulnerabilities).
We'd in no way have the resources to mark every package with vulnerabilities on EOL releases.

**Comment by stefano-m** [comment]
See https://github.com/NixOS/nixpkgs/issues/77361#issuecomment-572712011 for why I created this. I understand 19.03 is EOL (although to be honest the information seems to be somewhat hidden in the release notes - also discussed in #77361).

I was in two minds about creating the PR, but I noticed that release-19.03 is still getting new commits, so I thought it might be worth marking the browsers as insecure because I believe they have a large impact on many users (sorry, I have no numbers to substantiate this claim, so take it as a personal opinion).

If you think it's not worth proceeding, I am OK with closing the PR and so be it. I can submit a new PR for master and 19.09 though.

Thank you very much.

**Comment by stefano-m** [comment]
Also, I don't know who to make the failed checks pass since it seems they fail exactly because the packages have been marked as insecure :sweat_smile:

**Comment by flokli** [comment]
Right, this fails evaluation and is by design… I also don't think a backport is trivial - usually firefox updates trigger world rebuilds due to nss updates, so it might be best to just close this PR, sorry for the fuzz.

We should indeed show more prominently on the website about how long we backport security fixes to older releases, I opened https://github.com/NixOS/nixos-homepage/issues/325.

**Comment by LnL7** [comment]
Something like #23590 would also help to provide more visibility to users about the state of their current channels.

**Pull request closed without merging**
