### PR TITLE
watchexec: init at 1.8.6

### PR DESCRIPTION
**Pull request by michalrus**
###### Motivation for this change

One of the few tools of this sort that actually work reliably.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
@GrahamcOfBorg build watchexec

**Comment by michalrus** [comment]
```
  = note: ld: framework not found CoreServices
          clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
```

Emmm. How do I add those?

**Comment by michalrus** [comment]
Fixed, hopefully.

**Comment by michalrus** [comment]
@GrahamcOfBorg build watchexec

**Comment by joachifm** [comment]
@GrahamcOfBorg build watchexec

**Comment by joachifm** [comment]
Maybe just leave darwin unsupported for now; testing via bot invocation is a little tedious :)

**Comment by michalrus** [comment]
@joachifm, OK, let’s try it one last time, and if it doesn’t work now, I’ll stick to `platforms.linux`. =) This tool shouldn’t have many complicated deps. A pity they don’t list them upstream.

**Comment by joachifm** [comment]
@GrahamcOfBorg build watchexec

**Comment by michalrus** [comment]
Huh, from quick Google™’ing, that `_CFURLResourceIsReachable` symbol is defined in `CoreFoundation`. ¯\\\_(ツ)\_/¯

I dunno then. Removing darwin.

**Comment by michalrus** [comment]
```
building of '/nix/store/r36md20sbgcvcnrv0qx4s9ck44kll2nr-rustc-1.22.1.drv' timed out after 3600 seconds
```

Hmmmm. It worked just a while ago. ;o

**Comment by michalrus** [comment]
@GrahamcOfBorg build watchexec

**Comment by michalrus** [comment]
Ohhhhh, arm64.

**Comment by joachifm** [comment]
Note that you need to register to use the bot :)

**Comment by michalrus** [comment]
A PR to https://github.com/NixOS/ofborg/blob/released/config.known-users.json? Probably not worth it for an occasional PR. Would you suggest I do this?

**Comment by joachifm** [comment]
A committer should be able to invoke the bot for you in most cases so it's not strictly necessary.

**Comment by michalrus** [comment]
I’m not entire sure why it tries to build it on arm64, if I explicitly stated: 

```diff
+    platforms = [ "x86_64-linux" ];
```

**Comment by michalrus** [comment]
Thank you!

**Pull request merged**
