### PR TITLE
expat: 2.4.6 -> 2.4.7

### PR DESCRIPTION
**Pull request by vcunat**
###### Motivation for this change
This primarily fixes regressions in various other packages after the expat security fixes.

I'm unsure if this should go to `staging-next` (current iteration) or the next one (`staging` branch).  It rebuilds stdenv on all platforms, but it also fixes some regressions from the expat security update.  Note that the commits are based in a way to allow easy merging to either/both branches.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
Oh and the revert in this PR... might better get adjusted?  @jonringer: the `nose` parts should remain?

**Comment by vcunat** [comment]
21.11 is already being built.  https://github.com/NixOS/nixpkgs/commit/b80b398c16

**Comment by risicle** [comment]
If `python3Packages.xmltodict` is easily broken by expat, it's worth adding it to `expat`'s `passthru.tests`.

**Comment by vcunat** [comment]
Well we could, but as `expat` rebuilds all stdenvs, the usual workflows won't work so well.

**Comment by risicle** [comment]
No but it would give manual reviewers a hint that it might be worth checking that package.

**Comment by mweinelt** [comment]
Feel free to push that change. In the meantime I've tested these changes on my local python-updates tree and it fixes a few regressions of the `xml.parsers.expat.ExpatError: out of memory: line 1, column 0` here and there.

**Review by mweinelt — APPROVED** [review]

**Comment by mweinelt** [comment]
Can always decide to pick this up for staging-next, but I want this for python-updates now because the number of failing tests is annoying and us hotpatching everything is not going to happen.

**Comment by vcunat** [comment]
I suspect that this regression is related to expat updates, in case someone wanted to have a closer look: https://hydra.nixos.org/build/169724144

**Pull request merged**
