### PR TITLE
Add support for booting as Xen dom0 on EFI systems

### LINKED ISSUE #12225: xen dom0 doesn't build with efi
At the time of writing this (4dc7cab40ec9370816bf67b786a35679a1ebf2d1) there is an assertion in 
nixos/modules/virtualizations/xen-dom0.nix which says `Xen currently does not support EFI boot`.  This is certainly true for NixOS but as far as I can tell from Googling is no longer true upstream.

I'm opening this issue to ask if anyone's looking at adding that support (i.e. to boot using gummiboot on annoyingly new hardware that doesn't understand the legacy bios boot process)

I've started work on it and seem to have cajoled it into building a boot.efi but I haven't got as far as running it.  As a relative newbie both to nixpkgs and to Xen I'd welcome any feedback as to whether I'm on the right lines

### PR DESCRIPTION
**Pull request by Shados**
Based on #12230, aims to fix #12225.

###### Progress
- [ ] Get Xen EFI binaries to build on current nixpkgs versions:
    - [ ] 4.5.x (Is it worth spending time on this, given security support ended Jan 2018...?)
    - [x] 4.8.x
    - [x] 4.10.x
- [x] Support booting NixOS as Xen dom0 under EFI for:
    - [x] grub2
    - [x] systemd-boot/gummiboot
- [x] Tested using:
    - [x] Nested virtualization within a qemu-kvm VM
    - [x] Hardware (I hope to do this within the next day or two)
- [x] Confirmed the combined EFI/BIOS grub menu entry works under both

###### Notes, Issues, Questions
- This boots Xen by having the bootloader chainload to Xen's EFI binary, which needs a `xen.cfg` file in the same directory as it, on the ESP, that contains paths to the kernel and initrd (also on the ESP) as well as the Xen and kernel command lines.
- It is apparently possible to have grub2 boot a standard xen.gz using multiboot2/module2, but I could not get this to work (the VM reboots itself part-way through Xen's boot process). I have been able to find very little documentation on this method, as well as only two examples of people using this 'in the wild', so it is possible that this code-path has bit-rotted in the couple of years since it was implemented...
- ~This basically assumes grub is only used for EFI booting on the system, not both EFI and BIOS booting -- all the Xen entries will use the Xen EFI binary if it is avaiable. I think this could be solved by using `grub_platform` within the menu entry to switch between the xen.efi and xen.gz methods?~
- ~A configuration that can boot Xen using either is still possible, using both BIOS-only grub + systemd-boot.~
- I don't much like Perl, and I'm not all that familiar with it, so the changes to `install-grub.pl` are probably due some extra scrutiny.

### CODE REVIEW

**Comment by Shados** [comment]
Added another commit, some updates:
- Tested OK on actual hardware
- Rewrote `addEntry` to include support for booting under either EFI or BIOS using Xen within the same menu entry (tested both)
- Tested non-Xen booting still works fine (NixOS boot tests succeed, and I ran through the affected boot configurations manually OK)
- Did some other minor improvements and bits of cleanup

I'll remove the [WIP] bit from the title now, only outstanding question I have is whether Xen 4.5 should get EFI support, or just be removed or marked broken. Is there a specific reason it's still in nixpkgs?

It would be nice to add NixOS tests for Xen booting, but from what I understand it would likely require some effort to get the test driver to talk to the Xen dom0 VM nested within the outer QEMU VM.

**Comment by danbst** [comment]
Can you add a test for this?

**Comment by Shados** [comment]
@danbst No, as per my previous comment:
> It would be nice to add NixOS tests for Xen booting, but from what I understand it would likely require some effort to get the test driver to talk to the Xen dom0 VM nested within the outer QEMU VM.

From what I remember, apparently Linux just doesn't run drivers for any QEMU devices if it has detected that it is a Xen guest; it doesn't expect to be *simultaneously* a QEMU and Xen guest. This includes the driver for the `virtio-serial` device that the NixOS test driver uses to talk to the test VMs. @cleverca22 should know more.

**Comment by danbst** [comment]
If xen 4.5 is outstanding old and doesn't receive updates, then yes, lets remove it. Maybe in separate PR?

**Comment by danbst** [comment]
cc @oxij

**Comment by oxij** [comment]
Yes, sure, let's remove 4.5. It's overdue.

**Comment by ilya-fedin** [comment]
Why the PR is closed? :thinking: 
I wanted to try Xen, but I use systemd-boot :(

**Pull request closed without merging**
