### PR TITLE
synth: fix build on darwin

### PR DESCRIPTION
**Pull request by r-burns**
###### Motivation for this change

ZHF 21.11 https://github.com/NixOS/nixpkgs/issues/144627

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by figsoda** [comment]
I updated synth and attempted to fix darwin build on staging and it is in staging-next now

https://github.com/NixOS/nixpkgs/blob/staging-next/pkgs/tools/misc/synth/default.nix

I am running a build to see if it builds on x86_64-darwin, if it doesn't, fixes should probably be submitted to staging-next too

**Comment by figsoda** [comment]
I cancelled the build, it was trying to build coreutils
https://github.com/figsoda/nixpkgs-test/runs/4116700550?check_suite_focus=true

**Comment by r-burns** [comment]
Oh nice, didn't see that. Remind me to check again when hydra completes its first darwin eval of the current staging-next cycle, and this can probably be closed.

**Comment by figsoda** [comment]
It didn't build, I created a new pull request to target staging-next: #144925 
builds: https://github.com/figsoda/nixpkgs-test/runs/4127483251

**Pull request closed without merging**
