### PR TITLE
qgis, qgis-ltr version bumps

### PR DESCRIPTION
**Pull request by willcohen**
###### Description of changes

qgis from 3.26 -> 3.28, and qgis-ltr from 3.22.10 -> 3.22.12

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by hqurve** [comment]
Based on the build logs and the error message, I thought that maybe it has something to do with sip. Also, from hydra the first failure was on 2022-10-10 which maybe corresponds to when https://github.com/NixOS/nixpkgs/pull/194833 was merged (? just a guess, since the build takes too long for me to try verify this).

Anyhow, I tried blindly upgrading sip to 6.9.4 and it fixes the build for qgis3.28.0. Process:
- fetch pull request (pull/199535/head which is currently 145dc693f07393de0d4461554945ab19aad27418)
- change the version of sip (https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/python-modules/sip/default.nix) to 6.7.4 (and update hash)
- build qgis and it works :)

However, I believe, it might be a really bit rebuild since this is the beginning message of `nixpkgs-review rev HEAD`

```
261 packages updated:
adl aj-snapshot anime-downloader anki ankisyncd asymptote audiality2 backintime-qt cadence calibre carla cemu CharacterCompressor CompBus constant-detune-chorus convertall corrscope cubeb-unstable cura dupeguru easyeffects easyeffects eddy electron-cash electrum electrum-grs electrum-ltc faust2jack faust2jaqt faustCompressors faustPhhysicalModeling faustPhysicalModeling ffado firewalld flent flowblade frescobaldi friture fs-uae-launcher giada-unstable git-annex-metadata-gui git-cola gmic-qt-krita gmic-qt-krita gnss-sdr gnuradio gnuradio gnuradio gnuradio gnuradio gnuradio-wrapped gnuradio-wrapped gnuradio-wrapped gr-ais gr-grnet-unstable gr-grnet-unstable gr-limesdr gr-osmosdr gr-rds hikounomizu hplip hplip ihaskell-with-packages inkcut inkcut-inkscape-plugin jack1 jack2 jack2 jackmix jellyfin-mpv-shim kcc kicad kicad kicad-base kicad-base kicad-small kicad-unstable kicad-unstable-small kmymoney knockpy koboredux koboredux krita krita krop labelImg LazyLimiter leo-editor littlegptracker-unstable lsp-plugins ltc-tools luppp maestral-qt manuskript MBdistortion MeerK40t midimonster mkchromecast-unstable mlt mlt mlt mnemosyne mooSpace-unstable nanovna-saver napari octave onionshare openlp openlp-full openshot-qt opensnitch-ui persepolis picard pluginUtils polychromatic puddletag pulseeffects pymol pyspread python3.10-ansible-kernel python3.10-arviz python3.10-augmax-unstable python3.10-binwalk-full python3.10-dalle-mini python3.10-einops python3.10-elegy python3.10-enamlx python3.10-gns3-gui python3.10-jupyter python3.10-lightparam python3.10-mayavi python3.10-napari python3.10-napari-console python3.10-phik python3.10-plover python3.10-pyls-flake8 python3.10-pyls-isort python3.10-pyls-spyder python3.10-pylsp-mypy python3.10-pymc python3.10-pymc python3.10-pyqt-builder python3.10-PyQt5 python3.10-PyQt5 python3.10-PyQt5 python3.10-PyQt6 python3.10-PyQt6_WebEngine python3.10-pyqtgraph python3.10-PyQtWebEngine python3.10-python-lsp-black python3.10-python-lsp-server python3.10-python-poppler-qt5 python3.10-pywebview python3.10-qimage2ndarray python3.10-qnotero python3.10-qreactor-unstable python3.10-qscintilla-qt5 python3.10-qt5reactor python3.10-qtawesome python3.10-qtconsole python3.10-quamash python3.10-scudcloud python310Packages.sip (6.7.1 → 6.7.4) python3.10-spyder python3.10-stytra python3.10-superqt python3.10-treex python3.10-uranium python3.10-vega python3.10-weboob python3.10-woob python3.10-wxPython python3.10-xarray-einstats python3.9-ansible-kernel python3.9-arviz python3.9-augmax-unstable python3.9-binwalk-full python3.9-dalle-mini python3.9-einops python3.9-elegy python3.9-enamlx python3.9-jupyter python3.9-lightparam python3.9-mayavi python3.9-napari python3.9-napari-console python3.9-phik python3.9-pyls-flake8 python3.9-pyls-isort python3.9-pyls-spyder python3.9-pylsp-mypy python3.9-pymc python3.9-pymc python3.9-pyqt-builder python3.9-PyQt5 python3.9-PyQt5 python3.9-PyQt5 python3.9-PyQt6 python3.9-PyQt6_WebEngine python3.9-pyqtgraph python3.9-PyQtWebEngine python3.9-python-lsp-black python3.9-python-lsp-server python3.9-python-poppler-qt5 python3.9-pywebview python3.9-qimage2ndarray python3.9-qreactor-unstable python3.9-qscintilla-qt5 python3.9-qt5reactor python3.9-qtawesome python3.9-qtconsole python3.9-quamash python39Packages.sip (6.7.1 → 6.7.4) python3.9-spyder python3.9-stytra python3.9-superqt python3.9-treex python3.9-uranium python3.9-vega python3.9-weboob python3.9-woob python3.9-wxPython python3.9-xarray-einstats qarte qgis-ltr (3.22.10 → 3.22.12) qgis (3.26.2 → 3.28.0) qpaeq qradiolink quarto qutebrowser qutebrowser-unstable rapid-photo-downloader rare retext RhythmDelay rmview sasview shelfMultiBand shotcut sonic-pi soundtracker spyder sumorobot-manager synfigstudio Tambura tetraproc tortoisehg touchosc trackma tribler tuxguitar urh veusz vimiv-qt virtscreen vivisect VoiceOfFaust vorta webcamoid webmacs zrythm
```

**Comment by willcohen** [comment]
As noted in #196432, I'll do whatever is easier for the broader python ecosystem. I don't want to start bumping stuff that other packages depend on etc, so I'll hold tight on this PR till something is settled!

**Comment by das-g** [comment]
PR #201400 has been merged, fixing the build problems reported in #196432. This means that QGIS (both LTR and non-LTR) is now again buildable on nixpkgs `master`¹. :tada:

(And that we can go forward with testing this PR here, I guess. :rocket:)

¹tested on 08b68b96729af13ba86a956199cd8a25a9754a39

**Comment by willcohen** [comment]
Closing in favor of #205339.

**Comment by das-g** [comment]
What about the bump to the LTR version?

**Comment by willcohen** [comment]
Sorry, was on autopilot there and forgot about the LTR. Added updated qgis-ltr in #205575.

**Pull request closed without merging**
