### PR TITLE
snapcast: init at 0.11.1

### PR DESCRIPTION
**Pull request by TealG**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by peterhoeg** [comment]
The server and client derivations are ALMOST exactly the same - please use a function instead. You can use this as a reference: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/vala/default.nix

**Comment by pSub** [comment]
@TealG Are you still interested in this and working on it?

**Comment by peterhoeg** [comment]
@fpletz added this in 4d37ce91992

**Comment by pSub** [comment]
@peterhoeg Thank you for spotting this!

**Pull request closed without merging**
