### PR TITLE
redshift: update 1.9.1 -> 1.10-git-20150222

### PR DESCRIPTION
**Pull request by oxij**

### CODE REVIEW

**Comment by domenkozar** [comment]
In general we don't prefer git builds over stable releases, any good reason for the bump?

**Comment by vcunat** [comment]
I was about to ask the same. There's a 1.10 release.

**Comment by oxij** [comment]
@domenkozar, @vcunat I updated for gamma preservation which is not in 1.10. But I don't understand what's the problem with revisions that are not marked "stable" when the changes commited after the "stable" are quite readable and contain mostly fixes.

**Comment by jagajaga** [comment]
I think it's ok to have git version.

**Comment by domenkozar** [comment]
@jagajaga @oxij Did you try running redshift-gtk? #6008 failed to do so.

**Comment by jagajaga** [comment]
This PR worked for me.

**Comment by vandenoever** [comment]
The problem from #6008 is still there:
autoreconf: running: intltoolize --automake --copy --force
Can't exec "intltoolize": No such file or directory at /nix/store/njr9a876l3p13ylj0vs8kbxc4lq6v5jj-autoconf-2.69/share/autoconf/Autom4te/FileUtils.pm line 345.
autoreconf: failed to run intltoolize: No such file or directory
autoreconf: autopoint is needed because this package uses Gettext
builder for ‘/nix/store/lf3zb7z8vryilzjz8ykg7mm97b8gk382-redshift-1.10-git-20150222.drv’ failed with exit code 1
error: build of ‘/nix/store/lf3zb7z8vryilzjz8ykg7mm97b8gk382-redshift-1.10-git-20150222.drv’ failed

**Comment by jagajaga** [comment]
@vandenoever  My fault. Have the same now (I think I've tested old `redshift` :open_mouth:).
@oxij can you fix this?

**Comment by oxij** [comment]
I played with this and the problem seems to come from the fact that the new redshift-gtk wants `python > 3.2` with `pygtk`. AFAIK, these two do not work together in nixpkgs yet.

**Pull request merged**
