### PR TITLE
mupdf: fix library linking

### PR DESCRIPTION
**Pull request by danielfullmer**
###### Motivation for this change

A recent change 47f099777cadb1110abde73279e0ebf148c05308 broke a package I maintain (`k2pdfopt`), which would complain about missing `openssl` symbols. While a quick fix would just be to link in `openssl` manually for my package, I believe this is the proper fix to make `libmupdf` behave more like a normal shared library.

Specifically, `libmupdf.so` does not have `DT_NEEDED` references to its
dependencies. Packages which link against `libmupdf.so` would have to also
manually link against its dependencies as well. This adds unnecessary complexity to packages which depend on it. (See also `llpp`, `jfbview`, and `zathura-pdf-mupdf`)

The first commit includes a patch which ensures that `libmupdf.so` is built with references to its own dependencies.
An additional commit fixes k2pdfopt, which uses a patched version of mupdf and requires another patch for an older version.

Output of `readelf -d libmupdf.so` before change:
>  ...
> 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
> 0x000000000000001d (RUNPATH)            Library runpath: [/nix/store/zpg78y1mf0di6127q6r51kgx2q8cxsvv-glibc-2.25-49/lib]
> ...

After change:
> ...
>  0x0000000000000001 (NEEDED)             Shared library: [libmupdfthird.so]
> 0x0000000000000001 (NEEDED)             Shared library: [libmuthreads.so]
> 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
> 0x0000000000000001 (NEEDED)             Shared library: [libfreetype.so.6]
> 0x0000000000000001 (NEEDED)             Shared library: [libharfbuzz.so.0]
> 0x0000000000000001 (NEEDED)             Shared library: [libjbig2dec.so.0]
> 0x0000000000000001 (NEEDED)             Shared library: [libjpeg.so.62]
> 0x0000000000000001 (NEEDED)             Shared library: [libopenjp2.so.7]
> 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
> 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
> 0x000000000000000e (SONAME)             Library soname: [libmupdf.so]
> 0x000000000000001d (RUNPATH)            Library runpath: [/nix/store/05j0i5jhbp1j0mv36mj08rvn7pk7a3s4-mupdf-1.11/lib:/nix/store/7rda899md2d4q26lxb43yg3cmrgcdr1r-freetype-2.7.1/lib:/nix/store/riicxh9dp1bx90fjcf2yr7gw3wj0x7fm-harfbuzz-1.5.1/lib:/nix/store/gdnvg9j2hr4fh43arflqbzx5a86f7gpc-openjpeg-2.1.2/lib:/nix/store/i8wz3m067dzbs5x2glhxvcg7lvds1942-zlib-1.2.11/lib:/nix/store/bsqid2phn9ad8fyw2d63anzrrxp7a9x4-libjpeg-turbo-1.5.2/lib:/nix/store/0yqg15g97va4xrdzkgjd74nfxgw1c3ij-jbig2dec-0.13/lib:/nix/store/zpg78y1mf0di6127q6r51kgx2q8cxsvv-glibc-2.25-49/lib]
> ...

I believe `llpp`, `jfbview`, and `zathura-pdf-mupdf` could also be cleaned to not have to refer to mupdf's dependencies. Those packages build anyway, so it's not strictly necessary. Finally, I'm not an expert on compilers or linking so let me know if I'm misunderstanding anything.

CC @abbradar  

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vyp** [comment]
cc mupdf maintainers: @viric @vrthra @fpletz

**Review by fpletz — APPROVED** [review]

**Review by abbradar — APPROVED** [review]
Nice, thank you for adding a proper way to build shared mupdf!

I can test and merge this tomorrow; if anyone wants to do this sooner please go ahead.

**Review by orivej — CHANGES_REQUESTED** [review]
I can not download `mupdf-1.10a-shared_libs-1.patch` from IPv6 enabled hosts because www.linuxfromscratch.org advertises an IPv6 address in the DNS but does not respond on it. Could you find another source?

**Review by orivej — APPROVED** [review]

**Comment by danielfullmer** [comment]
@orivej I've changed the url to a mirror which works on ipv6.

Just a note that there are some other derivations which use a linuxfromscratch.org url: `id3lib`, `cyrus-sasl`, `pycairo`, and even `chromium`.

**Comment by orivej** [comment]
Thank you! Maybe I have not downloaded from them, or maybe they were already cached by nixos cache servers, or maybe linuxfromscratch IPv6 is only temporarily down.

**Pull request merged**
