### PR TITLE
maintainers: add NewDawn0

### PR DESCRIPTION
**Pull request by NewDawn0**

### CODE REVIEW

**Comment by natsukium** [comment]
Hi, welcome to nixpkgs!
What package do you want to maintain?
Could you please commit this with the same PR as the addition or change to that package?
If you are not ready to maintain it yet, I would appreciate it if you would add the maintainer again when you are ready.
Thanks.

**Comment by NewDawn0** [comment]
Hi there,

Thank you for the warm welcome! I'm looking to maintain a package for an operating system I'm currently developing, and I wanted to ensure it's buildable using Nix. I figured adding myself here allows me to also include myself as a maintainer in the metadata section of my project.

Since this is my initial commit to the project, I'm still getting familiar with the process. If there are specific steps or guidelines you recommend, I'd greatly appreciate your advice.

Thanks again for your help!

Best regards,
NewDawn0

**Comment by h7x4** [comment]
Hello @NewDawn0.

Traditionally, we've been trying to avoid adding new maintainers to the maintainer list before they are marked as maintainers of a package or a module. This is in order to having lots and lots of package-less maintainers in this list. There are also PRs every now and then that cleans the maintainer-list by removing inactive maintainers and removing package/module-less maintainers from the list.

It's quite common to add yourself as maintainer on the first package you create. [You can probably find lots of examples of that here](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+is%3Aclosed+label%3A%2212.+first-time+contribution%22+init). Alternatively, if there are some packages that you care strongly for, you could add yourself to the list and then mark yourself as maintainer for those.

**Comment by NewDawn0** [comment]
Hello,

Thank you for your advice and guidance. I understand the rationale behind avoiding the addition of new maintainers to the list without an associated package or module.

In adherence to the rules and to prevent clutter, I will close this pull request for now. I plan to open a new one when I publish the package, and at that time, I will add myself again.

I'll also make sure to familiarize myself with the guidelines outlined in CONTRIBUTING.md, especially the commit conventions, to ensure that my future contributions meet the necessary standards.

Your assistance is greatly appreciated.

Best regards,
NewDawn0

**Pull request closed without merging**
