### PR TITLE
grocy: 4.0.3 -> 4.1.0

### PR DESCRIPTION
**Pull request by tebriel**
## Description of changes

https://github.com/grocy/grocy/releases/tag/v4.1.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by tebriel** [comment]
I updated the ref but the "No channel PR" Job didn't re-run.

**Review by jtbx — APPROVED** [review]

**Comment by dotlambda** [comment]
> I updated the ref but the "No channel PR" Job didn't re-run.

@zimbatm @Mic92 @cole-h @zowoq That should be fixed.

@ofborg eval

**Review by dotlambda — CHANGES_REQUESTED** [review]
```
Running phase: patchPhase
applying patch /nix/store/8h2qqpp7gxahrglqchs20l7kdr8lsy9k-0001-Define-configs-with-env-vars.patch
patching file app.php
Hunk #1 FAILED at 12 (different line endings).
Hunk #2 FAILED at 64 (different line endings).
Hunk #3 FAILED at 106 (different line endings).
3 out of 3 hunks FAILED -- saving rejects to file app.php.rej
patching file services/DatabaseService.php
Hunk #1 succeeded at 137 (offset 12 lines).
patching file services/FilesService.php
Hunk #1 FAILED at 10 (different line endings).
1 out of 1 hunk FAILED -- saving rejects to file services/FilesService.php.rej
patching file services/StockService.php
Hunk #1 FAILED at 1761.
1 out of 1 hunk FAILED -- saving rejects to file services/StockService.php.rej
error: builder for '/nix/store/8hwcg76i60hcz8sdhir8lj8mhhdwba8a-grocy-4.1.0.drv' failed with exit code 1;
```

**Comment by cole-h** [comment]
Once you push an updated commit (preferably with the above issue fixed :laughing: ) the GHA "No channel PR" check should succeed.

**Comment by dotlambda** [comment]
> Once you push an updated commit (preferably with the above issue fixed 😆 ) the GHA "No channel PR" check should succeed.

I know, but the workflow should re-run if the target branch is changed.

**Comment by tebriel** [comment]
creating dos patch files is pain on my system (or I'm just not experienced in it), lets see if this works

**Comment by tebriel** [comment]
nope didn't work.

**Comment by drupol** [comment]
It can now be built from sources using the PHP/Composer builder!

**Comment by tebriel** [comment]
> It can now be built from sources using the PHP/Composer builder!

I am overwhelmed with being unable to build this myself, hopefully someone can do that and make a PR to get this out!

**Pull request closed without merging**
