### PR TITLE
gpgme: 1.10.0 -> 1.11.1

### LINKED ISSUE #39124: notmuch: build broken with gnupg 2.2.6 (18.03)
## Issue description

Recent bump of  `gnupg: 2.2.5 -> 2.2.6`  ~~~in  ecc5a2bc153148f7e554c45ca6d6e2d0582d1bb5 (master) and~~~ 31ed7ab (18.03)
broke the build of `notmuch`. 

It still compiles but a number of test cases fail - looks like `gnupg` output has changed. 

Upstream doesn't appear to have updated the tests yet so we will probably have to disable or patch them ourselves.

/cc maintainers @garbas @the-kenny @flokli @chaoflow

### PR DESCRIPTION
**Pull request by flokli**
###### Motivation for this change
This fixes #39124 by bumping gpgme from 1.10.0 to 1.11.1 and libgpg-error from 1.27 to 1.28 (which needs a patch to systemd as well).

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by flokli** [comment]
@GrahamcOfBorg build notmuch

**Comment by flokli** [comment]
hrm. tried changing base as there are a lot of rebuilds, but it seems like `staging-18.03` isn't what it's supposed to be.

@vcunat, how should this go to 18.03?

**Comment by vcunat** [comment]
I used staging-18.03 for a commit a week ago.

**Comment by flokli** [comment]
@vcunat Okay, will rebase to `staging-18.03`.

So you're also fine with bumping that library globally, instead of overriding it just for `notmuch` (as suggested [here](https://github.com/NixOS/nixpkgs/issues/39124#issuecomment-383589956))?

**Comment by vcunat** [comment]
Hmm.  The updates mix features and fixes, as most projects do, though I see nothing scary in there.  Rebuilding is the least part, as that occasionally happens anyway; we even seem to have a CVE open against systemd on 18.03 ATM.  The worst part is probably that gpgme only hit master now and it isn't in the unstable channel yet.

**Comment by flokli** [comment]
I rebased this PR to `staging-18.03` for now. I'll leave it up to you to decide whether we should merge this together with the CVE fix or afterwards ;-)

**Comment by xeji** [comment]
notmuch build failed with this on staging-18.03: https://hydra.nixos.org/eval/1451405.
@flokli maybe there's something missing on the staging branch?

**Comment by flokli** [comment]
That's really weird, that's a completely other test failing:
> FAIL Ignore files and directories specified in new.ignore (regexp)

**Comment by flokli** [comment]
@xeji https://github.com/NixOS/nixpkgs/pull/39481 should fix the last test, at least it did for me.

**Comment by flokli** [comment]
@vcunat can you merge this into `release-18.03`?

**Comment by vcunat** [comment]
Yes, thanks.  I forgot we had some commits in `release-18.03..staging-18.03`

**Pull request merged**
