### PR TITLE
vagrant: 2.0.1 -> 2.0.2

### PR DESCRIPTION
**Pull request by ryantm**
Semi-automatic update. These checks were performed:

- built on NixOS
- found 2.0.2 with grep in /nix/store/32zly5yhz0hcqgk6w5y0ish2rssfc6y9-vagrant-2.0.2

cc "@aneeshusa"

### CODE REVIEW

**Comment by aneeshusa** [comment]
@ryantm thanks for sending this in!
In the future, could you please avoid cc'ing me in the commit message? I find I get a bunch of email from the same commit as it bounces around GitHub. One mention on the PR is a lot friendlier to my inbox :)

**Comment by ryantm** [comment]
@aneeshusa thanks for the feedback, you're the second person to request this. I will try to update my tools to make that happen.

**Comment by phunehehe** [comment]
Do you think a `vagrant version` can be included in the automatic checks?

**Comment by ryantm** [comment]
@phunehehe my bot tried to do vagrant version, but it failed. I have since added a warning when no binary responds to version or help.

**Comment by aneeshusa** [comment]
@phunehehe I also added an explicit `installCheckPhase` in #36283 that checks the output of `vagrant --version`.

**Pull request merged**
