### PR TITLE
[17.03] firefox: 54.02 -> 55.0.2

### PR DESCRIPTION
**Pull request by tokudan**
###### Motivation for this change

Firefox update

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Note: I'm unable to test the build on my local system due to low battery issues, so I have to rely on the CI check.

### CODE REVIEW

**Comment by tokudan** [comment]
Doesn't build yet:
DEBUG: configure:10890:23: error: #error "Insufficient libpng version (10629 required)."

**Comment by tokudan** [comment]
Added libpng update required by firefox (minimum version 1.6.29)

**Comment by tokudan** [comment]
Yep... firefox also needs a newer sqlite...

**Comment by bjornfor** [comment]
Is the commit order so that the required library updates come before the Firefox update?

**Comment by tokudan** [comment]
@bjornfor no, its in the order of firefox's "i need newer versions!" complaints.

During the night I confirmed that the build works. Haven't had the time to verify that it actually runs, though.

**Comment by bjornfor** [comment]
@tokudan: Please reorder the commits to not break "git bisect". (PRs shouldn't introduce breakage, even temporary, if it's easy to avoid.)

**Comment by tokudan** [comment]
@bjornfor is there is a way to do that through the github website? If not, i probably won't be able to do that before tomorrow evening.

**Comment by bjornfor** [comment]
@tokudan: I don't think so. Better use the ```git rebase -i ...``` on the command line. (No rush.)

**Comment by tokudan** [comment]
Let's have another go at this... I have reordered the commits and am trying to build this right now.

**Comment by tokudan** [comment]
Ok... the build is finally done and firefox 55.0.2 actually runs.
I've updated the checks in the first box. I believe this PR can be merged now.

Please note: I have NOT checked all packages that depend on libpng and sqlite... that would take weeks.

**Pull request merged**
