### PR TITLE
Remove KDE 4 desktop packages

### PR DESCRIPTION
**Pull request by ttuegel**
Here I begin to remove the KDE 4 desktop packages.

Discussion period until 25 Feb 2017. To be announced on the mailing list.

The NixOS module for KDE 4 has already been removed. Relevant discussion is at #15866.

I have removed as many core packages as possible at this time. To facilitate this, I have removed third-party applications that depend on KDE 4 if I think they are unlikely to be updated. The remainder should be updated as soon as possible to remove the remaining KDE 4 libraries. The major offenders here are:

- Calligra
- Zanshin
- KDE Telepathy
- Amarok

In the process of removing core libraries, I discovered that we have not been keeping up-to-date on Nepomuk libraries. This happened because upstream bundles Nepomuk with kdelibs, but our builder was separating them. As a result, we had new kdelibs with old Nepomuk. It is possible there are undisclosed vulnerabilities with our old KDE 4 packages and users should be moved away from them as soon as possible.

ATTN: @grahamc

### CODE REVIEW

**Comment by ttuegel** [comment]
A terse change log:

## Removed Now

### Removed Outright

- semnotes
- psi
- partition-manager
- liblikeback
- libkvkontakte
- libalkimia
- kuickshow
- kvirc
- kmymoney
- kdesvn
- kbibtex
- choqok
- basket
- bangarang
- rekonq and kwebkitpart
- rsibreak
- kwooty
- qtcurve
- oxygen-gtk
- eventlist
- kde-wacomtablet

### Already Updated
Removed KDE 4 versions.

- digikam
- kdeconnect
- kdevelop
- kdiff3
- kile
- krename
- konversation
- quassel
- skrooge
- yakuake
- bluedevil
- colord-kde
- kde-gtk-config
- ksshaskpass
- plasma-nm, libmm-qt, and libnm-qt
- polkit-kde-agent
- ktorrent and libktorrent
- kipi-plugins

## To Be Removed Dec 2017

### Update Available

- calligra (#22966)
- kmplayer (#22959)
- krusader (#22952)
- telepathy (#22954)

### Development Version Available

- k3b
- kadu (#22956)
- kgraphviewer (#22958)
- ktikz (#22961)
- massif-visualizer (#22963)
- zanshin (#22964)

**Comment by ttuegel** [comment]
I should add, upstream will stop updating kdelibs4 around Dec 2017. At that time, I will simply remove any package which still depends on it.

**Comment by 7c6f434c** [comment]
>### Removed Outright
>- psi

it actually does have an unreleased qt5 version (and maybe it can even
be made independent of KDE)

**Comment by ttuegel** [comment]
> it actually does have an unreleased qt5 version (and maybe it can even be made independent of KDE)

@7c6f434c Thank you for pointing this out! I was operating from information I got through the KDE packagers mailing list, which was apparently incorrect.

**Comment by 7c6f434c** [comment]
>> it actually does have an unreleased qt5 version (and maybe it can even be made independent of KDE)
>
>@7c6f434c Thank you for pointing this out! I was operating from information I got through the KDE packagers mailing list, which was apparently incorrect.

Right now I understand how to build it with Qt5 and QCA2-Qt5, but it 
segfaults for some reason…

**Comment by tosky** [comment]
In the "removed outright" section there are various applications with a Frameworks 5 version, at least:
- choqok
- kmymoney
- partition-manager
- kdesvn
- rsibreak

PSI, semnotes are not by KDE.
Basket is not by KDE anymore but it has a Frameworks-based beta .

**Comment by ttuegel** [comment]
> In the "removed outright" section there are various applications with a Frameworks 5 version, at least:
> 
>     choqok
>     kmymoney
>     partition-manager
>     kdesvn
>     rsibreak
> 
> PSI, semnotes are not by KDE.
> Basket is not by KDE anymore but it has a Frameworks-based beta .

I am aware that these are not part of KDE.

I was not able to find the Frameworks releases for these packages. I also didn't look hard, because they don't have maintainers in NixOS, anyway. If somebody wants to step forward and take the responsibility to be a maintainer, then I'll gladly put them back in.

**Comment by ttuegel** [comment]
The Travis failure is a spurious build timeout.

**Pull request merged**
