### PR TITLE
add textlint rules and plugins

### PR DESCRIPTION
**Pull request by matthew-piziak**
###### Motivation for this change

This is a continuation of https://github.com/NixOS/nixpkgs/pull/53981. That pull request installed `textlint`; this one installs rules and plugins. 

Question: these are separate npm packages, but should I be grouping these under a common label in nix somehow? I'm assuming not, but let me know if there's a way to keep things more organized. Thanks!

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthew-piziak** [comment]
@Mic92 Hi! Like this:  
``` 
textlint \
--rule write-good \
--rule no-start-duplicated-conjunction \
--rule max-comma \
--rule terminology \
--rule period-in-list-item \
--rule period-in-list-item \
--rule unexpanded-acronym \
--rule abbr-within-parentheses \
--rule alex \
--rule common-misspellings \
--rule en-max-word-count \
--rule diacritics \
--rule stop-words \
file_to_check
```

**Comment by matthew-piziak** [comment]
@Mic92 Does that make sense?

**Comment by matthew-piziak** [comment]
> Is this sufficient? This is all I did in the previous PR. However I'm also happy to go through the checklist—is there documentation on how to "test using sandboxing"?

Bump. Looking for some beginner device here. I've only make one other nixpkgs PR before, and that one was just merged without further ceremony.

**Comment by matthew-piziak** [comment]
@adisbladis @6AA4FD Does this look okay to you?

**Comment by matthew-piziak** [comment]
Looks like I can't get any attention here. I will try to contribute to NUR instead.

**Comment by veprbl** [comment]
@matthew-piziak
This is very unfortunate. I think there is a problem with contributing Node.js packages to nixpkgs. The changes to the generated node-packages-v10.nix will quickly run into merge conflicts and PRs will get stalled and buried. I also suspect that we might not have enough people with node knowledge and time to review those PR's in the first place.

I think the pull requests should only update the .json file so that .nix file is updated by nodejs maintainers in a more synchronized fashion. Perhaps we could try doing this for your contribution.

**Comment by matthew-piziak** [comment]
@veprbl That sounds _great_! Thank you so much for helping me out. My thinking is that the `.nix` generation step happening as a hook or a CI step makes sense. That way there will be no merge conflicts and reviewers only have to review a dozen lines instead of thousands.

I will remove the generate `.nix` file for now since I think that's what you're suggesting. Let me know if I can do anything else to help!

**Comment by matthew-piziak** [comment]
@veprbl Okay, now the diff is restricted to `node-packages-v10.json`.

**Comment by Mic92** [comment]
Sorry, your pr got burden under the other one.
You said you would use, one would use it like this:

```console
$ textlint \
  --rule write-good \
  --rule no-start-duplicated-conjunction \
  --rule max-comma \
  --rule terminology \
  --rule period-in-list-item \
  --rule period-in-list-item \
  --rule unexpanded-acronym \
  --rule abbr-within-parentheses \
  --rule alex \
  --rule common-misspellings \
  --rule en-max-word-count \
  --rule diacritics \
  --rule stop-words \
  file_to_check
```

How can I bring the other packages get into scope?
Do they just provide a binary each, that is picked up by texlint or do they need to be loaded as a library?

**Comment by matthew-piziak** [comment]
All these packages are so-called "plugins" of `textlint`, each one is an `npm` module, and I believe they are loaded dynamically at runtime. There is more documentation here: https://textlint.github.io/docs/plugin.html

I'm not exactly sure how plugin discovery works...I've never used `npm` before. Hopefully it doesn't actually require `npm` to exist in order to wire in the plugins. I believe this is where rules are loaded in `textlint`: https://github.com/textlint/textlint/blob/master/packages/textlint/src/engine/textlint-module-loader.ts

**Comment by matthew-piziak** [comment]
If I were doing this myself and guessing, I'd probably just make all the rules _dependencies_ of `textlint` and hope that that'd be enough to get them loaded. That does make it less granular, where rule installation becomes all or nothing. Maybe there's a better way.

**Comment by endgame** [comment]
I wonder if the correct thing is to relax checks on the node stuff in nixpkgs so that we get more users and npm-aware nixpkgs contributors?

I don't have a dog in this race, because I don't do any JS, but it's a thought.

**Comment by matthew-piziak** [comment]
@endgame I think you're right.

**Comment by Mic92** [comment]
@astro  do you know if there was a way to extend the modules search path via environment variables?

**Comment by astro** [comment]
@Mic92 Not npm itself, but node evaluates `NODE_PATH` from the environment. As per its man page:
```
NODE_PATH=path[:...]
       ':'-separated list of directories prefixed to the module search path.
```

**Comment by matthew-piziak** [comment]
@astro I'm looking at `node2nix` now. It includes this:
```
      # Provide the dependencies in a development shell through the NODE_PATH environment variable
      inherit nodeDependencies;
      shellHook = stdenv.lib.optionalString (dependencies != []) ''
        export NODE_PATH=$nodeDependencies/lib/node_modules
      '';
```

Does that mean we should be including all these packages as `dependencies` of `textlint` so that `textlint` can pick them up?

**Comment by astro** [comment]
@matthew-piziak Yes.

If that doesn't do the trick, `makeWrapper`/`wrapProgram` may be used to add the env to the textlint entrypoint.

**Comment by matthew-piziak** [comment]
Hmm, I don't know how to do either of those things. That is, I do not know how to add a dependency to the `node-packages-v10.json` so that the generation script will pick it up (there appear to be no analogous examples); and I do not know how to use `makeWrapper` or `makeProgram`. @astro can you show me how to do either one?

One thing I did try is, I cloned `textlint`, added the rules to its dependencies, and ran `node2nix` on it directly. However when I run `nix-build -A package`, this always happens on the last dependency:
```
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to http://www.example.com/@textlint%2fast-node-types failed, reason: getaddrinfo ENOTFOUND www.example.com www.example.com:80
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /nix/store/iw009dc4rpla6i6gx98fdz22k8kjah28-node-dependencies-textlint-11.2.3/textlint/.npm/_logs/2019-04-05T01_31_17_744Z-debug.log
builder for '/nix/store/nraxcsn2d3lgmnpwzqv6njhilfkmiak3-node-dependencies-textlint-11.2.3.drv' failed with exit code 1
error: build of '/nix/store/nraxcsn2d3lgmnpwzqv6njhilfkmiak3-node-dependencies-textlint-11.2.3.drv' failed
```

**Comment by matthew-piziak** [comment]
You can see my experimentation here: https://github.com/textlint/textlint/compare/6aa579afc98c05e2d123818ffd46ab2d97b9a672...matthew-piziak:master

**Comment by matthew-piziak** [comment]
Can a maintainer help me get this merged? Textlint without the rules is basically useless, and I've been trying to get this merged for three months now.

**Comment by ryantm** [comment]
@GrahamcOfBorg build nodePackages.textlint-plugin-latex

**Pull request merged**
