### PR TITLE
hamlib: fix darwin

### PR DESCRIPTION
**Pull request by rmcgibbo**
###### Motivation for this change
https://nix-cache.s3.amazonaws.com/log/w6i388ykg1b1mjdy5s5nax8wsbmga5sd-hamlib-3.3.drv
ZHF: #122042
Just added `gettext`.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rmcgibbo** [comment]
Result of `nixpkgs-review pr 122996` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>hamlib</li>
    <li>xlog</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 122996` at cdb6f154 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>gnuradio3_7Packages.ais</li>
    <li>gnuradio3_7Packages.gsm</li>
    <li>gnuradio3_7Packages.osmosdr</li>
  </ul>
</details>
<details>
  <summary>3 packages skipped due to time constraints:</summary>
  <ul>
    <li>fldigi</li>
    <li>pothos</li>
    <li>sdrangel</li>
  </ul>
</details>
<details>
  <summary>19 packages built successfully:</summary>
  <ul>
    <li>cqrlog</li>
    <li>cubicsdr</li>
    <li>direwolf</li>
    <li>gnss-sdr</li>
    <li>gnuradio3_8Packages.osmosdr</li>
    <li>gpredict</li>
    <li>gqrx</li>
    <li>hamlib</li>
    <li>klog</li>
    <li>python38Packages.soapysdr-with-plugins</li>
    <li>python39Packages.soapysdr-with-plugins</li>
    <li>qradiolink</li>
    <li>qsstv</li>
    <li>rtl_433</li>
    <li>soapyaudio</li>
    <li>soapysdr-with-plugins</li>
    <li>tlf</li>
    <li>welle-io</li>
    <li>xlog</li>
  </ul>
</details>
<details>
  <summary>5 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

pkg-config is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/development/libraries/hamlib/default.nix:13:3:
```
   |
13 |   buildInputs = [
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

swig is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/development/libraries/hamlib/default.nix:13:3:
```
   |
13 |   buildInputs = [
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

pkg-config is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/applications/radio/xlog/default.nix:19:3:
```
   |
19 |   buildInputs = [ glib pkg-config gtk2 hamlib ];
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`gpl3` is a deprecated license, please check if project uses `gpl3Plus` or `gpl3Only` and change `meta.license` accordingly.

Near pkgs/applications/radio/xlog/default.nix:33:5:
```
   |
33 |     license = licenses.gpl3;
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

libtool is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/development/libraries/hamlib/default.nix:13:3:
```
   |
13 |   buildInputs = [
   |   ^
```
</li>
  </ul>
</details>

**Comment by risicle** [comment]
Hmmmm, on macos 10.15, fails for me with:

```
make[2]: Entering directory '/private/tmp/nix-build-hamlib-3.3.drv-0/hamlib-3.3/bindings'
  CC       hamlibpy_wrap.lo
  CCLD     _Hamlib.la
  CC       hamlibtcl_wrap.lo
  CCLD     hamlibtcl.la
Undefined symbols for architecture x86_64:
  "_TclFreeObj", referenced from:
      _SWIG_Tcl_MethodCommand in hamlibtcl_wrap.o
      _SWIG_Tcl_ObjectDelete in hamlibtcl_wrap.o
      _SWIG_Tcl_ObjectConstructor in hamlibtcl_wrap.o
      __wrap_hamlib_version_get in hamlibtcl_wrap.o
      __wrap_hamlib_copyright_get in hamlibtcl_wrap.o
  "_Tcl_AppendElement", referenced from:
      _SWIG_Tcl_MethodCommand in hamlibtcl_wrap.o
  "_Tcl_AppendResult", referenced from:
      __wrap_new_Rig in hamlibtcl_wrap.o
      _SWIG_Tcl_GetArgs in hamlibtcl_wrap.o
      __wrap_Rig_open in hamlibtcl_wrap.o
      __wrap_Rig_close in hamlibtcl_wrap.o
      __wrap_Rig_set_freq in hamlibtcl_wrap.o
      __wrap_Rig_set_mode in hamlibtcl_wrap.o
      __wrap_Rig_set_ptt in hamlibtcl_wrap.o
...
...
...
  "_Tcl_SetVar2", referenced from:
      _Hamlib_Init in hamlibtcl_wrap.o
      __wrap_hamlib_version_get in hamlibtcl_wrap.o
      __wrap_hamlib_copyright_get in hamlibtcl_wrap.o
  "_Tcl_TraceVar2", referenced from:
      _Hamlib_Init in hamlibtcl_wrap.o
  "_Tcl_VarEval", referenced from:
      _SWIG_Tcl_ConvertPtr in hamlibtcl_wrap.o
ld: symbol(s) not found for architecture x86_64
```

**Comment by jonringer** [comment]
@GrahamcOfBorg build hamlib

**Pull request closed without merging**
