### PR TITLE
pythonPackages.pyyaml: 5.4.1 -> 5.4.1.1

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
There are actually no changes for us, but it shouldn't show as outdated on Repology.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dotlambda** [comment]
@ofborg build python2.pkgs.pyyaml python3.pkgs.pyyaml

**Comment by dotlambda** [comment]
Changed base so ofborg will produce a result. Will change back later.
@ofborg build python2.pkgs.pyyaml python3.pkgs.pyyaml

**Comment by risicle** [comment]
`python3.pkgs.pyyaml` builds happily, macos 10.15. `nixpkgs-review` claims `python2.pkgs.pyyaml` is unchanged.

**Comment by dotlambda** [comment]
> `nixpkgs-review` claims `python2.pkgs.pyyaml` is unchanged.

because `python2Packages` are not recursed into

**Comment by risicle** [comment]
Ah ok, I shall insist.

**Comment by risicle** [comment]
`python2.pkgs.pyyaml` happy too, macos 10.15.

**Comment by dotlambda** [comment]
I'm running `nix-build -A pkgsCross.aarch64-multiplatform.python3.pkgs.pyyaml` right now. If that fails, I'll add back `buildPackages.stdenv.cc`.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 128754` at 92d207f9 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>69 packages marked as broken and skipped:</summary>
  <ul>
    <li>adobe-reader</li>
    <li>adoptopenjdk-hotspot-bin-13</li>
    <li>adoptopenjdk-hotspot-bin-14</li>
    <li>adoptopenjdk-jre-hotspot-bin-13</li>
    <li>adoptopenjdk-jre-hotspot-bin-14</li>
    <li>adoptopenjdk-jre-openj9-bin-13</li>
    <li>adoptopenjdk-jre-openj9-bin-14</li>
    <li>adoptopenjdk-openj9-bin-13</li>
    <li>adoptopenjdk-openj9-bin-14</li>
    <li>airtame</li>
    <li>autotrace</li>
    <li>cassandra_2_1</li>
    <li>cassandra_2_2</li>
    <li>clickshare-csc1</li>
    <li>curaByDagoma</li>
    <li>cura_stable</li>
    <li>displaycal</li>
    <li>dvd-slideshow</li>
    <li>electron_3</li>
    <li>electron_4</li>
    <li>electron_5</li>
    <li>epsxe</li>
    <li>erlang_basho_R16B02</li>
    <li>evilvte</li>
    <li>gnash</li>
    <li>googleearth-pro</li>
    <li>grass</li>
    <li>green-pdfviewer</li>
    <li>hadoop</li>
    <li>hadoop_2_7</li>
    <li>hadoop_2_8</li>
    <li>hadoop_2_9</li>
    <li>hplipWithPlugin_3_16_11</li>
    <li>hplip_3_16_11</li>
    <li>impressive</li>
    <li>invoice2data</li>
    <li>jboss</li>
    <li>k2pdfopt</li>
    <li>keyfinder</li>
    <li>linuxPackages_hardkernel_4_14.akvcam</li>
    <li>linuxPackages_hardkernel_4_14.virtualbox</li>
    <li>linuxPackages_hardkernel_latest.akvcam</li>
    <li>linuxPackages_hardkernel_latest.virtualbox</li>
    <li>loxodo</li>
    <li>metamorphose2</li>
    <li>obinskit</li>
    <li>odpdown</li>
    <li>opentsdb</li>
    <li>pcsxr</li>
    <li>pdfdiff</li>
    <li>pdfread</li>
    <li>pgadmin</li>
    <li>pig</li>
    <li>plover.stable</li>
    <li>riak</li>
    <li>scribus</li>
    <li>scyther</li>
    <li>spark</li>
    <li>staruml</li>
    <li>stepmania</li>
    <li>termplay</li>
    <li>torchat</li>
    <li>tvheadend</li>
    <li>twinkle</li>
    <li>unicap</li>
    <li>vdrPlugins.xineliboutput</li>
    <li>winpdb</li>
    <li>xpdf</li>
    <li>yaxg</li>
  </ul>
</details>
<details>
  <summary>14418 packages skipped due to time constraints:</summary>
  <ul>
    <li>AusweisApp2</li>
    <li>DisnixWebService</li>
    <li>EBTKS</li>
    <li>MIDIVisualizer</li>
    <li>OSCAR</li>
    <li>R</li>
    <li>SDL_Pango</li>
    <li>SDL_mixer</li>
    <li>Sylk</li>
    <li>_1password-gui</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>12 packages built successfully:</summary>
  <ul>
    <li>djvulibre</li>
    <li>gdk-pixbuf</li>
    <li>gi-docgen</li>
    <li>librsvg (gnome.librsvg)</li>
    <li>pango (gnome2.pango)</li>
    <li>imagemagick</li>
    <li>libinput</li>
    <li>python38Packages.pyyaml</li>
    <li>python38Packages.sphinx</li>
    <li>python39Packages.markdown</li>
    <li>python39Packages.pyyaml</li>
    <li>sphinx (python39Packages.sphinx)</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
> I'm running `nix-build -A pkgsCross.aarch64-multiplatform.python3.pkgs.pyyaml` right now. If that fails, I'll add back `buildPackages.stdenv.cc`.

Doesn't seem to be needed anymore.

**Pull request merged**
