### PR TITLE
neohtop: init at 1.0.8

### LINKED ISSUE #354007: Package request: neohtop
**Project description**

A modern, cross-platform system monitor built on top of Svelte, Rust and Tauri.

**Metadata**

* homepage URL: https://abdenasser.github.io/neohtop
* source URL: https://github.com/Abdenasser/neohtop
* license: mit
* platforms: darwin, linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by andreaskrath**
NeoHtop is a new cross-platform desktop application for system monitoring.

It was released recently and has already gotten quite a bit of attention, including requests for it to be packaged.

Close #354007

I have pretty much just followed the approach of [Hoppscotch](https://github.com/NixOS/nixpkgs/blob/b50cd02c4e76f111c38fe9ac11ff8ba326de416a/pkgs/by-name/ho/hoppscotch/package.nix#L4), as they are both Tauri applications and they should function similarly.

I would also appreciate feedback on darwin, as I have no way to test that myself.

This is my first time contributing, so I appreciate any and all feedback.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by istudyatuni** [comment]
Please [include word fix/close](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue) before issue mention to close it automatically on merge

**Review by pluiedev — CHANGES_REQUESTED** [review]
If possible, I think it would be better if it's built from source via `cargo-tauri.hook` — repacking binary artifacts from upstream should only be used for closed-source packages or as a last resort (e.g. exceedingly complicated compilation/circular dependencies/bootstrapping issues)

**Comment by thegrubster** [comment]
> If possible, I think it would be better if it's built from source via `cargo-tauri.hook` — repacking binary artifacts from upstream should only be used for closed-source packages or as a last resort (e.g. exceedingly complicated compilation/circular dependencies/bootstrapping issues)

Been messing around with it for a couple of hours now and I don't think I can progress further or build it from source as is (although this is likely a skill issue).

NeoHtop is a tauri v2 application, but `cargo-tauri` for the time being is still in v1 (waiting on #346277).

I have tried overwriting the version of tauri in `cargo-tauri` similar to [this](https://github.com/NixOS/nixpkgs/blob/717248d7283b98c0ab5d5f67cff1ceaffbdd81be/pkgs/by-name/su/surrealist/package.nix#L25) but I have been unsuccessful and get some errors from the tauri derivation that I do not know how to get around.

So unless someone else wants to take a crack at it, I will probably not be able to progress further till `cargo-tauri` is updated to v2.

Should I move my PR to a draft for the time being?

**Comment by pluiedev** [comment]
I think you can just base your PR on the tauri v2 PR and not merge until that one is merged

**Comment by thegrubster** [comment]
I am closing the PR.
I have tried to the best of my ability to package this, but I cannot get it to work.

From my understanding as of tauri v2, tauri is affected by a bug in cargo in relation to weak dependencies (I do not think this is unique to neohtop, rather this affects all tauri v2 projects).

This means that `hyper-tls` cannot be found in the vendored dependencies (because it is an optional dependency) and is therefore not added correctly.

The fix to this is to copy what has been done with [surrealist](https://github.com/NixOS/nixpkgs/blob/4f589591492b3c38988b2b9f1787d4787de4fddd/pkgs/by-name/su/surrealist/package.nix#L69), which involves patching `Cargo.toml` and `Cargo.lock` to correctly include the `hyper-tls` dependency. But I cannot get this approach to work, and I cannot be bothered wasting more of my time trying to get this to work.

**Pull request closed without merging**
