### PR TITLE
busybox: 1.31.1 -> 1.32.0

### PR DESCRIPTION
**Pull request by j4m3s-s**
###### Things done
The patches removed are on the 1.32.0 branch now.

Building works and `nix-build pkgs/stdenv/linux/make-bootstrap-tools.nix -A test` also works as asked in the file.

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by j4m3s-s** [comment]
@TethysSvensson

**Comment by TethysSvensson** [comment]
This looks good to me. It is a (hopefully simple) version bump with two patches removed.

What I've tested that:

* It builds
* A few of the applets work as expected
* The removed patches are in fact present upstream
* The fix for the udhcpc script still works as expected

**Comment by rissson** [comment]
Result of `nixpkgs-review pr 104433` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>hercules-ci-agent</li>
    <li>nix-exec</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>fusionInventory</li>
    <li>python37Packages.nixpkgs</li>
  </ul>
</details>
<details>
  <summary>60 packages built:</summary>
  <ul>
    <li>bundix</li>
    <li>busybox</li>
    <li>busybox-sandbox-shell</li>
    <li>cabal2nix</li>
    <li>cachix</li>
    <li>common-updater-scripts</li>
    <li>crate2nix</li>
    <li>crystal2nix</li>
    <li>dep2nix</li>
    <li>disnix</li>
    <li>disnixos</li>
    <li>epson-escpr2</li>
    <li>fcron</li>
    <li>go2nix</li>
    <li>hydra-unstable</li>
    <li>lazpaint</li>
    <li>lightdm</li>
    <li>lightdm-enso-os-greeter</li>
    <li>lightdm-mini-greeter</li>
    <li>lightdm-tiny-greeter</li>
    <li>lightdm_gtk_greeter</li>
    <li>lightdm_qt</li>
    <li>lispPackages.quicklisp-to-nix</li>
    <li>lispPackages.quicklisp-to-nix-system-info</li>
    <li>molly-guard</li>
    <li>nix (nixStable)</li>
    <li>nix-binary-cache</li>
    <li>nix-bundle</li>
    <li>nix-direnv</li>
    <li>nix-doc</li>
    <li>nix-du</li>
    <li>nix-index</li>
    <li>nix-pin</li>
    <li>nix-plugins</li>
    <li>nix-prefetch</li>
    <li>nix-prefetch-bzr</li>
    <li>nix-prefetch-cvs</li>
    <li>nix-prefetch-docker</li>
    <li>nix-prefetch-git</li>
    <li>nix-prefetch-hg</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-prefetch-svn</li>
    <li>nix-review (nixpkgs-review)</li>
    <li>nix-serve</li>
    <li>nix-update</li>
    <li>nix-update-source</li>
    <li>nixFlakes (nixUnstable)</li>
    <li>nixos-generators</li>
    <li>nixos-shell</li>
    <li>nixui</li>
    <li>pantheon.elementary-greeter</li>
    <li>pipework</li>
    <li>python37Packages.nix-kernel</li>
    <li>python37Packages.pythonix</li>
    <li>python38Packages.nix-kernel</li>
    <li>python38Packages.nixpkgs</li>
    <li>python38Packages.pythonix</li>
    <li>update-nix-fetchgit</li>
    <li>vgo2nix</li>
    <li>vulnix</li>
  </ul>
</details>

**Comment by rissson** [comment]
It's weird `python38Packages.nixpkgs` builds but not `python37Packages.nixpkgs`...

**Comment by TethysSvensson** [comment]
This is mostly replicable on my system:

Result of `nixpkgs-review pr 104433` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>nix-exec</li>
  </ul>
</details>
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>tests.nixos-functions.nixos-test</li>
    <li>tests.nixos-functions.nixosTest-test</li>
  </ul>
</details>
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>fusionInventory</li>
    <li>pantheon.elementary-greeter</li>
    <li>python37Packages.nixpkgs</li>
  </ul>
</details>
<details>
  <summary>62 packages built:</summary>
  <ul>
    <li>bundix</li>
    <li>busybox</li>
    <li>busybox-sandbox-shell</li>
    <li>cabal2nix</li>
    <li>cachix</li>
    <li>common-updater-scripts</li>
    <li>crate2nix</li>
    <li>crystal2nix</li>
    <li>dep2nix</li>
    <li>disnix</li>
    <li>disnixos</li>
    <li>epson-escpr2</li>
    <li>fcron</li>
    <li>go2nix</li>
    <li>haskellPackages.cachix</li>
    <li>haskellPackages.hocker</li>
    <li>haskellPackages.nix-paths</li>
    <li>haskellPackages.update-nix-fetchgit</li>
    <li>hydra-unstable</li>
    <li>lazpaint</li>
    <li>lightdm</li>
    <li>lightdm-enso-os-greeter</li>
    <li>lightdm-mini-greeter</li>
    <li>lightdm-tiny-greeter</li>
    <li>lightdm_gtk_greeter</li>
    <li>lightdm_qt</li>
    <li>lispPackages.quicklisp-to-nix</li>
    <li>lispPackages.quicklisp-to-nix-system-info</li>
    <li>molly-guard</li>
    <li>nix (nixStable)</li>
    <li>nix-bundle</li>
    <li>nix-direnv</li>
    <li>nix-doc</li>
    <li>nix-du</li>
    <li>nix-index</li>
    <li>nix-pin</li>
    <li>nix-plugins</li>
    <li>nix-prefetch</li>
    <li>nix-prefetch-bzr</li>
    <li>nix-prefetch-cvs</li>
    <li>nix-prefetch-docker</li>
    <li>nix-prefetch-git</li>
    <li>nix-prefetch-hg</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-prefetch-svn</li>
    <li>nix-serve</li>
    <li>nix-update</li>
    <li>nix-update-source</li>
    <li>nixFlakes (nixUnstable)</li>
    <li>nixos-generators</li>
    <li>nixos-shell</li>
    <li>nixpkgs-review</li>
    <li>nixui</li>
    <li>pipework</li>
    <li>python37Packages.nix-kernel</li>
    <li>python37Packages.pythonix</li>
    <li>python38Packages.nix-kernel</li>
    <li>python38Packages.nixpkgs</li>
    <li>python38Packages.pythonix</li>
    <li>update-nix-fetchgit</li>
    <li>vgo2nix</li>
    <li>vulnix</li>
  </ul>
</details>

However I as far as I can tell `python37Packages.nixpkgs` is broken on master as well.

**Comment by rissson** [comment]
It seems alright to merge though. @j4m3s-s do you have any time to look into why those few dependencies fail, if they weren't broken on master before?

**Review by r-burns — APPROVED** [review]
python37Packages.nixpkgs is broken due to python37Packages.pythonix, which builds but fails to import on non-python-3.8 (see https://github.com/NixOS/nixpkgs/pull/103151#issuecomment-723638622). I think this is ready to be merged.

Result of `nixpkgs-review pr 104433` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>nix-exec</li>
  </ul>
</details>
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>tests.nixos-functions.nixos-test</li>
    <li>tests.nixos-functions.nixosTest-test</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>python37Packages.nixpkgs</li>
  </ul>
</details>
<details>
  <summary>64 packages built:</summary>
  <ul>
    <li>bundix</li>
    <li>busybox</li>
    <li>busybox-sandbox-shell</li>
    <li>cabal2nix</li>
    <li>cachix</li>
    <li>common-updater-scripts</li>
    <li>crate2nix</li>
    <li>crystal2nix</li>
    <li>dep2nix</li>
    <li>disnix</li>
    <li>disnixos</li>
    <li>epson-escpr2</li>
    <li>fcron</li>
    <li>fusionInventory</li>
    <li>go2nix</li>
    <li>haskellPackages.cachix</li>
    <li>haskellPackages.hocker</li>
    <li>haskellPackages.nix-paths</li>
    <li>haskellPackages.update-nix-fetchgit</li>
    <li>hydra-unstable</li>
    <li>lazpaint</li>
    <li>lightdm</li>
    <li>lightdm-enso-os-greeter</li>
    <li>lightdm-mini-greeter</li>
    <li>lightdm-tiny-greeter</li>
    <li>lightdm_gtk_greeter</li>
    <li>lightdm_qt</li>
    <li>lispPackages.quicklisp-to-nix</li>
    <li>lispPackages.quicklisp-to-nix-system-info</li>
    <li>molly-guard</li>
    <li>nix (nixStable)</li>
    <li>nix-bundle</li>
    <li>nix-direnv</li>
    <li>nix-doc</li>
    <li>nix-du</li>
    <li>nix-index</li>
    <li>nix-pin</li>
    <li>nix-plugins</li>
    <li>nix-prefetch</li>
    <li>nix-prefetch-bzr</li>
    <li>nix-prefetch-cvs</li>
    <li>nix-prefetch-docker</li>
    <li>nix-prefetch-git</li>
    <li>nix-prefetch-hg</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-prefetch-svn</li>
    <li>nix-serve</li>
    <li>nix-update</li>
    <li>nix-update-source</li>
    <li>nixFlakes (nixUnstable)</li>
    <li>nixos-generators</li>
    <li>nixos-shell</li>
    <li>nixpkgs-review</li>
    <li>nixui</li>
    <li>pantheon.elementary-greeter</li>
    <li>pipework</li>
    <li>python37Packages.nix-kernel</li>
    <li>python37Packages.pythonix</li>
    <li>python38Packages.nix-kernel</li>
    <li>python38Packages.nixpkgs</li>
    <li>python38Packages.pythonix</li>
    <li>update-nix-fetchgit</li>
    <li>vgo2nix</li>
    <li>vulnix</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 104433` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package marked as broken and skipped:
</summary>
<ul>
<li>nix-exec</li>
</ul>
</details>
<details>
<summary>
2 packages blacklisted:
</summary>
<ul>
<li>tests.nixos-functions.nixos-test</li>
<li>tests.nixos-functions.nixosTest-test</li>
</ul>
</details>
<details>

  <summary>3 packages failed to build and are new build failures:</summary>
  <ul>
<li>cachix: log was empty</li>
<li>haskellPackages.cachix: log was empty</li>
<li>python37Packages.nixpkgs: log <a href="https://hastebin.com/raw/gikoyizegi">https://hastebin.com/raw/gikoyizegi</a></li>
  </ul>
</details>
<details>
<summary>
62 packages built:
</summary>
<ul>
<li>bundix</li>
<li>busybox</li>
<li>busybox-sandbox-shell</li>
<li>cabal2nix</li>
<li>common-updater-scripts</li>
<li>crate2nix</li>
<li>crystal2nix</li>
<li>dep2nix</li>
<li>disnix</li>
<li>disnixos</li>
<li>epson-escpr2</li>
<li>fcron</li>
<li>fusionInventory</li>
<li>go2nix</li>
<li>haskellPackages.hocker</li>
<li>haskellPackages.nix-paths</li>
<li>haskellPackages.update-nix-fetchgit</li>
<li>hydra-unstable</li>
<li>lazpaint</li>
<li>lightdm</li>
<li>lightdm-enso-os-greeter</li>
<li>lightdm-mini-greeter</li>
<li>lightdm-tiny-greeter</li>
<li>lightdm_gtk_greeter</li>
<li>lightdm_qt</li>
<li>lispPackages.quicklisp-to-nix</li>
<li>lispPackages.quicklisp-to-nix-system-info</li>
<li>molly-guard</li>
<li>nix (nixStable)</li>
<li>nix-bundle</li>
<li>nix-direnv</li>
<li>nix-doc</li>
<li>nix-du</li>
<li>nix-index</li>
<li>nix-pin</li>
<li>nix-plugins</li>
<li>nix-prefetch</li>
<li>nix-prefetch-bzr</li>
<li>nix-prefetch-cvs</li>
<li>nix-prefetch-docker</li>
<li>nix-prefetch-git</li>
<li>nix-prefetch-hg</li>
<li>nix-prefetch-scripts</li>
<li>nix-prefetch-svn</li>
<li>nix-serve</li>
<li>nix-update</li>
<li>nix-update-source</li>
<li>nixFlakes (nixUnstable)</li>
<li>nixos-generators</li>
<li>nixos-shell</li>
<li>nixpkgs-review</li>
<li>nixui</li>
<li>pantheon.elementary-greeter</li>
<li>pipework</li>
<li>python37Packages.nix-kernel</li>
<li>python37Packages.pythonix</li>
<li>python38Packages.nix-kernel</li>
<li>python38Packages.nixpkgs</li>
<li>python38Packages.pythonix</li>
<li>update-nix-fetchgit</li>
<li>vgo2nix</li>
<li>vulnix</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

python38Packages.nixpkgs:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>

**Comment by SuperSandro2000** [comment]
All build failures are known and unrelated to this PR.

**Pull request merged**
