### PR TITLE
onlyoffice-bin: 7.2.0 -> 7.4.1

### LINKED ISSUE #225249: Update request: onlyoffice-bin 7.2.0 → 7.3.3
- Package name: onlyoffice-bin
- Latest released version: 7.3.3

- Current version on the unstable channel: 7.2.0
- Current version on the stable/release channel: 7.2.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@nh2
@GTrunSec 

-----

Note for maintainers: Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by fin444**
## Description of changes

* Bumped version to 7.4.1 ([changelog](https://github.com/ONLYOFFICE/DesktopEditors/blob/master/CHANGELOG.md#741))
* Added `libgbm` (`mesa`) as a dependency for the newly-bundled `libcef`
* Wrapped in `buildFHSEnv` because the plugin download feature [directly references `/usr/bin/curl`](https://github.com/ONLYOFFICE/core/blob/7a822494aabb1edce441a12e44aa05c3a6501766/Common/Network/FileTransporter/src/transport_external.h#L76) (I am new to Nix, this seemed like the best solution to me but I may be wrong)

Maintainers: @nh2 @GTrunSec 
Closes: #225249

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by GTrunSec** [comment]
I tested this PR on Wayland env, which is pretty slow when opening a tab(even crashed after a few seconds).

**Comment by nh2** [comment]
@GTrunSec Is that a regression / is it fine on Wayland in the current version?

**Comment by GTrunSec** [comment]
@nh2  Based on my testing, the experience under Wayland is inferior and nearly unusable. Do I need some special args for the wayland desktop?

**Comment by fin444** [comment]
It seems to work perfectly fine for me on Wayland, just as good as on X11.

**Comment by GTrunSec** [comment]
> It seems to work perfectly fine for me on Wayland, just as good as on X11. 

@fin444  Did you enable the `QT_QPA_PLATFORM=wayland` with onlyoffice-bin? 

Are you running that app on hyprland/sway ?

**Comment by fin444** [comment]
@GTrunSec running with `QT_QPA_PLATFORM` unset or set to `wayland` produces no issues. I am using Plasma.

**Comment by fin444** [comment]
It seems this is a problem with 7.3+ on all wlroots environments

https://github.com/ONLYOFFICE/DesktopEditors/issues/1208

**Comment by GTrunSec** [comment]
How about keeping two versions here?  the 7.2 is still to be a default, but the latest version would be in `passthru.latest`.

**Comment by fin444** [comment]
Something like this?

**Review by GTrunSec — APPROVED** [review]

**Comment by GTrunSec** [comment]
@nh2 The latest 7.4+ version has been placed in the bin.latest as an alternative while still retaining 7.2 as the default version.

**Comment by nh2** [comment]
@fin444 @GTrunSec Looks good overall and both work in X11 (I didn't test wayland), but a request:

* The explanatory contents of the commit message of the previous commit in this PR (https://github.com/NixOS/nixpkgs/commit/0d5de6501c043803ce7736f3a7af3ba2eff7d832) should be retained in comments. There should never be non-obvious code that's "just there" without explanation.

And a question:

* It seems a bit weird to add another package into `passthru.latest` (though I couldn't find anything technically wrong with it). Most packages in `pkgs/top-level/all-packages.nix` add an independent package with `_latest` suffix. Maybe this package should do it as well?

**Comment by fin444** [comment]
@nh2 My bad, I explained it in the commit but not in the comments. Will fix. Which version naming would be preferable?

`onlyoffice-bin_latest` and `onlyoffice-bin`

or

`onlyoffice-bin` and `onlyoffice-bin_7_2`?

**Comment by nh2** [comment]
Based on the above report that on Wayland only the old version works, I propose:

```
onlyoffice-bin_7_2 = ...
onlyoffice-bin_7_4 = ...

onlyoffice-bin = onlyoffice-bin_7_2;
onlyoffice-bin_latest = onlyoffice-bin_7_4;
```

**Comment by nh2** [comment]
Looks good, merging. Thanks @fin444 for your contribution!

**Comment by scvalex** [comment]
For reference, 7.4 works fine on Plasma (Wayland) for me too.  There's definitely some bugginess (e.g. I opened a second spreadsheet and the tab was blank; this fixed itself when I closed and repopened the tab), but it's about the level of bugginess I've come to expect from OnlyOffice.

**Comment by fin444** [comment]
@scvalex The problem does not occur on all Wayland systems, only on [wlroots](https://gitlab.freedesktop.org/wlroots/wlroots/#wlroots)-based compositors.

**Pull request merged**
