### PR TITLE
Update django guardian

### PR DESCRIPTION
**Pull request by lsix**
###### Things done

- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@lsix Btw. We are in the progress of moving python packages out of `pkgs/top-level/python-packages.nix` into dedicated files in `./pkgs/development/python-modules` because it is getting to big. 
Unfortunate this is a manual process, so we move new and upgrades python packages there.

**Comment by lsix** [comment]
OK, lets go for that.

Is there a particular layout to follow or everything will be dropped flat in `./pkgs/development/python-modules` (there will be a huge amount of files)? I did not see a mail on the ML about that (I might have missed it) and the closest I see in the issues is #11567 (again, I might probably have missed something).

Could you point me to the appropriate updated guideline ?

**Comment by FRidh** [comment]
@lsix there wasn't any mail about this. At some point I started moving new packages into new files and asked others to do the same.

I will update #11567 to reflect this change.

**Comment by lsix** [comment]
OK, I’ve moved it out of the `python-packages.nix` file. I’ve also moved `pytest` while I was at it (but I am not quite satisfied of hew the overrides ends up being written, any better idea?).

Also, the question still remains. Do we lay out all the new `*.nix` files flat in `pkgs/development/python-modules`? There will be a huge amount of files at the end. This is not unmanageable, but if we want another organization (thematic as in the rest of nixpkgs or other), it is a good time to make the choice ;)

**Comment by FRidh** [comment]
> OK, I’ve moved it out of the python-packages.nix file. I’ve also moved pytest while I was at it (but I am not quite satisfied of hew the overrides ends up being written, any better idea?).

I think we should copy the expressions instead of overriding them. 

> Also, the question still remains. Do we lay out all the new *.nix files flat in pkgs/development/python-modules? There will be a huge amount of files at the end. This is not unmanageable, but if we want another organization (thematic as in the rest of nixpkgs or other), it is a good time to make the choice ;)

If we need to subgroup, then in my opinion we should subgroup on first character of the name.

**Comment by lsix** [comment]
I’ve updated the PR, removed the overridings in the `pytest` declarations and added an update of `pytest-3.0`branch. `nox-review` passes successfully.

**Comment by FRidh** [comment]
Excellent, thank you. Hopefully soon we can get rid of the old versions of pytest.

**Comment by lsix** [comment]
@FRidh yes, changing the default pytest to pytest_30 is defensively on my TODO list, but there are too much derivations impacted for my laptop… Do you know an hydra instance that could be used to see what would be broken if we did this change?

**Pull request merged**
