### PR TITLE
nixos/exwm: fix services.xserver.windowManager.exwm.enable option

### LINKED ISSUE #319541: Remove deprecated option `services.xserver.windowManager.exwm.enableDefaultConfig`
The default EXWM configuration has been deprecated upstream. See https://github.com/emacs-exwm/exwm/commit/382bdd899c818d5019b53093c5d8eee332203e73

`services.xserver.windowManager.exwm.enableDefaultConfig` should thus probably be deprecated too.

### Notify maintainers
Not sure who I should be mentioning here. Thanks!

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #361706: 24.11: windowManager.exwm option broken
## Describe the bug

  services.xserver.windowManager.exwm.enable = true;
in configuration.nix does not compile:

       error: 'emacsWithPackages' has been renamed to/replaced by 'emacs.pkgs.withPackages'

See also:

https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/window-managers/exwm.nix
- it explicitly mentions: `pkgs.emacsWithPackages`
- it still has the option  `enableDefaultConfig` which is deprecated upstream

## Steps To Reproduce

in configuration.nix, add:

  `services.xserver.windowManager.exwm.enable = true;`

and rebuild 

## Expected behavior

The option   services.xserver.windowManager.exwm.enable = true;
should not result in an error when rebuilding the system config

## Additional context

enableDefaultConfig issue was already reported but overlooked:
https://github.com/NixOS/nixpkgs/issues/319541

## Notify maintainers

@adisbladis  ?

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by stanleyj-edsn**
Fix: #319541
Fix: #361706
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by stanleyj-edsn** [comment]
Needs backport to 24.11 because this is broken in NixOS 24.11

**Review by thiagokokada — CHANGES_REQUESTED** [review]
Code wise looks good, but please squash your commits accordingly to the [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions) guidelines. You should have only one commit similar to:

```
nixos/exwm: remove services.xserver.windowManager.exwm.enableDefaultConfig
```

**Review by thiagokokada — APPROVED** [review]

**Comment by jian-lin** [comment]
I took the liberty to remove the mention of `enableDefaultConfig` in the `description` of `loadScript`.

**Review by jian-lin — APPROVED** [review]
LGTM.  Thanks.

**Comment by jian-lin** [comment]
I also changed the backport label from `staging-24.11` to `release-24.11` since this PR does not cause massive rebuilds.

**Pull request merged**
