### PR TITLE
factorio: add .desktop file

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

Add a desktop file for factorio.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
The icons are not yet showing for me in wofi.

**Comment by doronbehar** [comment]
Why draft?

**Comment by mweinelt** [comment]
> Why draft?

https://github.com/NixOS/nixpkgs/pull/94821#issuecomment-670228594

**Review by piegamesde — APPROVED** [review]
Works for me.

**Comment by mweinelt** [comment]
Works in rofi, doesn't work in wofi. Probably a wofi issue. :shrug:

**Comment by priegger** [comment]
I think this broke the *-headless builds.

**Comment by mweinelt** [comment]
Ah, sorry we missed that. Guess we can move the steps into an alpha and demo specific installPhase.

**Pull request merged**
